<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_surv</name>
   <tag></tag>
   <elementGuidId>3b6c4423-8566-4518-b488-02314e87d2d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ActeAdministratif_DateSurvenance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActeAdministratif_DateSurvenance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7f5b8b3-e4a6-4695-b004-fd88a5995f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>a593a59a-c4cc-4a5e-bf4f-bb545e8f64ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7fa6093-f18a-4b91-9fa8-6e6b4301dba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer la date de survenance de l'évènement catastrophique</value>
      <webElementGuid>565b6711-cf9a-44cb-a6ed-fb7c049a5dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ActeAdministratif_DateSurvenance</value>
      <webElementGuid>b5892f99-b926-4d4e-8204-ed4c71bef40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ActeAdministratif.DateSurvenance</value>
      <webElementGuid>0a98f3b4-e1fe-41db-9599-27e0a3d9357b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActeAdministratif_DateSurvenance&quot;)</value>
      <webElementGuid>18ac2368-ffb3-4522-bb06-febb1317354d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ActeAdministratif_DateSurvenance']</value>
      <webElementGuid>1b8c1ef0-71c9-4a02-9f52-42235621c378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div/div[2]/input</value>
      <webElementGuid>1f865643-8ec0-4aea-82b0-195d25909df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/input</value>
      <webElementGuid>47125037-b1ac-4f12-b350-8ea6a63e8e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'ActeAdministratif_DateSurvenance' and @name = 'ActeAdministratif.DateSurvenance']</value>
      <webElementGuid>ee6f4f58-3d46-40bf-861a-a8a838a79a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
