<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_rec</name>
   <tag></tag>
   <elementGuidId>1e864f54-0761-439b-aac2-05eba1afc27d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ActeAdministratif_DateReconnaissance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActeAdministratif_DateReconnaissance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddfe51dd-4771-440e-9367-343021b6ab2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>a6dbcba6-17bb-44bb-8ff7-db5c8f8ef291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f5ab197-9460-49a0-8c51-cefa9cd90e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer la date de reconnaissance de l'EVCAT</value>
      <webElementGuid>32477f04-0648-4d2c-b4d6-65932754cb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ActeAdministratif_DateReconnaissance</value>
      <webElementGuid>9307c167-cd9f-4127-a1b5-8b436117cc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ActeAdministratif.DateReconnaissance</value>
      <webElementGuid>f8c78f5c-3632-407a-86ef-57868f24dd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActeAdministratif_DateReconnaissance&quot;)</value>
      <webElementGuid>331cca74-7a30-4f09-9878-e10e7b0916d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ActeAdministratif_DateReconnaissance']</value>
      <webElementGuid>d9ab9c3c-f2db-403e-8082-099a2a7edcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div[3]/div/input</value>
      <webElementGuid>33781264-5ec4-42e2-b92b-a13308938cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/input</value>
      <webElementGuid>946f9145-c921-4ad8-942c-5cc47e9d9436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'ActeAdministratif_DateReconnaissance' and @name = 'ActeAdministratif.DateReconnaissance']</value>
      <webElementGuid>0003ee77-c437-47cb-93f2-4c5c5a2d5568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
