<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Duree</name>
   <tag></tag>
   <elementGuidId>89bd91fd-fd66-40ad-8a5d-fd339082e4f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DureeEvenement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DureeEvenement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>759c79e9-d4d1-4aa7-8698-0304a0df7175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>66ebaef0-cb15-4cc8-abb3-c7084fa1feda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DureeEvenement</value>
      <webElementGuid>e4eecf2c-a3db-4afd-a542-990d277acb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1a63b9d-1631-42ab-851c-23feb10790a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Duree must be a number.</value>
      <webElementGuid>27262947-48a5-4a7d-aa72-91116c409353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Valeur non valide</value>
      <webElementGuid>43258a39-699b-4314-b6c8-732bfd7b6adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>f25bd711-99b4-46e0-8945-ae1189c6dd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b272658c-8a3a-46d8-bbb6-7ccad08bac6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer la durée de l'évènement </value>
      <webElementGuid>af419b6a-9c1a-4336-85f8-479e341d5071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Duree</value>
      <webElementGuid>ee65f436-699f-44dc-b8c1-8b4670a9fd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DureeEvenement&quot;)</value>
      <webElementGuid>a84dccfd-d182-4845-9041-5ca02d323788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DureeEvenement']</value>
      <webElementGuid>e7dac29f-5e9d-40e3-9892-baca88ce30a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DureeDiv']/input</value>
      <webElementGuid>7a403af7-2beb-4d50-b9f0-5364062cb6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>90fc6f55-38a9-4052-b9cf-1a4dc5234339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'DureeEvenement' and @name = 'Duree']</value>
      <webElementGuid>701a1be0-5296-42a7-bbaa-4689061a547e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
