<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>connexion</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a3324f0a-9a5b-4fc2-b206-c9e495be85d1</testSuiteGuid>
   <testCaseLink>
      <guid>50ff5c08-628e-49bb-80d9-d7cf31905045</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Connexion/Cas de test Positive</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>56ca75a6-1729-4cfe-bf96-d15a66bb15ac</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Resp_Exp</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>56ca75a6-1729-4cfe-bf96-d15a66bb15ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c60a6130-6795-46d6-aecf-106a63b0c9ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>56ca75a6-1729-4cfe-bf96-d15a66bb15ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>cb3065f4-8213-4998-ba3d-669d4efe2ee2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>56ca75a6-1729-4cfe-bf96-d15a66bb15ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Statut</value>
         <variableId>734010af-f8b8-42b9-89f9-224943270430</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca883e0c-8f0c-426c-8efa-e146d3644ee1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Connexion/Cas de test negative</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
