<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Connexion</name>
   <tag></tag>
   <elementGuidId>d36c578a-7049-4031-a025-dc48cbc6d439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.lf-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbe31e85-0b63-4dbe-8803-58c9d4ad5038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-button</value>
      <webElementGuid>6bd2e587-f123-4770-b9ce-ae2077040847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>6cf745cc-a0fe-4794-b491-1bbf6a556d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account&quot;)/div[@class=&quot;back&quot;]/div[@class=&quot;authentification&quot;]/div[@class=&quot;container ogul&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;log-in&quot;]/button[@class=&quot;lf-button&quot;]</value>
      <webElementGuid>60d145e7-5e6c-440b-ba2b-586c8c9e1d44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>a8e2c2d1-55ad-448a-97b2-669ef386fe59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connexion'])[1]/following::button[1]</value>
      <webElementGuid>90d7c9a1-dce8-44e4-a3b2-8400c86d337a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe oublié?'])[1]/preceding::button[1]</value>
      <webElementGuid>b29a76c5-384d-4754-95ee-3a0128b5e742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2d40ac9b-88c5-4d9c-9279-d14c392f9c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Connexion' or . = 'Connexion')]</value>
      <webElementGuid>054fc23d-85e9-4147-8b0e-e412bb8ee2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
