<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TPE_GarantieIndustriel.DateEffet</name>
   <tag></tag>
   <elementGuidId>d16b166e-290b-4974-8061-71f10b3a7cdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GarantieIndustriel_DateEffet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieIndustriel_DateEffet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c290367e-aa1a-4caa-9f2c-f890460576bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>0602336c-95e7-42ee-b22b-bcd65c428ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>e29e95f7-a210-4d14-b91a-82d14f294048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0d3f474-1a05-4a4d-88c6-c3a2d2fc0eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'Date d’effet' is invalid.</value>
      <webElementGuid>6f6f8560-9aa2-4e68-a975-add3bf22755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.DateEffet,*.DateSinistre</value>
      <webElementGuid>97dfa9e4-a1e2-483e-b160-c1d98346b6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>7a432d94-359c-4730-bf24-6a6f38fcc17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/Date-compare/compare-dates-effet-sinistre</value>
      <webElementGuid>315abde3-aaf6-48f4-a919-9e79ad1eb932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Date d'effet est obligatoire</value>
      <webElementGuid>5b8f0e13-630c-4c93-818b-2f367906e4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieIndustriel_DateEffet</value>
      <webElementGuid>14f1bd14-592b-4f79-bfa8-5b691a109c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieIndustriel.DateEffet</value>
      <webElementGuid>396c7cd8-ebad-440b-942d-d897d1393b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieIndustriel_DateEffet&quot;)</value>
      <webElementGuid>30b6e6db-bec1-4030-ab49-5cb4accfc785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieIndustriel_DateEffet']</value>
      <webElementGuid>807d9837-da83-4e16-b569-aedebdb274d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>fbb7099c-507e-4aa1-be0f-0fc6723cb0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>cd0106c0-1f2e-49c6-99c9-7d3d13090613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'GarantieIndustriel_DateEffet' and @name = 'GarantieIndustriel.DateEffet']</value>
      <webElementGuid>3a1973d0-e8e6-4bff-9c87-d5b30c785945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
