<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TPE_GarantieIndustriel.DateEcheance</name>
   <tag></tag>
   <elementGuidId>59089295-d669-4f09-a5e0-5d33d1bf4a12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GarantieIndustriel_DateEcheance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieIndustriel_DateEcheance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ae8a471-2bee-4df9-b508-176c6cdf79b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>883bb43c-774a-485f-9168-9bfeb0beb618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>e3008a04-d36e-456a-97b0-32f79c10c51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>264881c7-b0d3-461d-8f98-593f60ef8cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>La date d'échéance doit être supérieur ou égale à la date d'effet</value>
      <webElementGuid>8c9d3a2c-ede1-4100-b530-1314b59c5bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.DateEcheance,*.DateEffet,*.DateSinistre</value>
      <webElementGuid>16286116-9644-4a55-a005-21df1dc16cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>51b20889-c52b-4e2a-a205-6cebb845ff71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/Date-compare/compare-dates-effet-echeance</value>
      <webElementGuid>0b34a64f-9b26-4bbb-b736-d65aca94fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Date d'échéance est obligatoire</value>
      <webElementGuid>39ba70f1-7cce-4ee2-97e9-047bd319f6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieIndustriel_DateEcheance</value>
      <webElementGuid>325f89fa-79e6-4163-a934-2b0ac7c51e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieIndustriel.DateEcheance</value>
      <webElementGuid>b7443391-b925-4f7e-a183-302e1ce33ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieIndustriel_DateEcheance&quot;)</value>
      <webElementGuid>e70465ed-7c72-40db-b42c-501f32fb2479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieIndustriel_DateEcheance']</value>
      <webElementGuid>5a736e53-aac6-4cc4-9d9d-4cf45128b0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>2eaa6933-be7a-4141-8bc3-32fb526d20bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>ca28dff8-6341-4dde-bfc1-dc13255b1195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'GarantieIndustriel_DateEcheance' and @name = 'GarantieIndustriel.DateEcheance']</value>
      <webElementGuid>76d3d306-45db-44c7-a404-d477bf530125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
