<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tremblement_terre</name>
   <tag></tag>
   <elementGuidId>4842575e-7ecf-45a3-b024-02cca8284d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tail-select.no-classes.deselect.active > div.select-dropdown > div.dropdown-inner > ul.dropdown-optgroup > li.dropdown-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/section/div[1]/div/div/div/div/div[2]/div/form/div/div[4]/div/div/div[4]/div/div/div/div[2]/div/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b429c97f-cf04-4d3d-9b0d-317d78358d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>a996abe8-a7fb-4d82-a144-23df9e0899bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>92de3640-c187-4c9e-b505-5c0eb633e394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>458f797c-0542-4b87-9bd9-e24e005ccefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CNIE</value>
      <webElementGuid>f902b050-cd16-4131-9d06-48d47d0b31d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;Demendeur-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>f2f3db57-d7bc-444e-b5bc-dabc05e55efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[2]/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>b7d694fa-f5f5-45af-9038-ef97572f55f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner ...'])[1]/following::li[1]</value>
      <webElementGuid>ece6feb0-aa56-4f07-9679-0297dd876965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/following::li[1]</value>
      <webElementGuid>3e0b21d8-a759-4452-8309-2dc6b2bcb921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passeport'])[2]/preceding::li[1]</value>
      <webElementGuid>8a67b59b-bb37-4afc-9672-9bb1515c4396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carte de résidence'])[2]/preceding::li[2]</value>
      <webElementGuid>745425b2-c9df-4a9e-9fb0-0462126b1ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>48f4b890-2287-4102-9a40-9deb79811bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'CNIE' or . = 'CNIE')]</value>
      <webElementGuid>a8be2e91-e1e7-43c6-bd44-d66a03259f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
