<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Attachement.FichierContratAssuranceRemorque</name>
   <tag></tag>
   <elementGuidId>1c9d5c84-772b-4e16-acd7-7919aae9fda0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierContratAssuranceRemorque</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Attachement_FichierContratAssuranceRemorque']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2d1303e-8438-4f6e-8e60-7081d2385fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d78dcb3-37e5-40a9-8aa2-fd0270061f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>0294b9c9-50c0-459d-9372-9fcf46950fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>a58d41b0-01a4-4e0e-824f-519211969968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierContratAssuranceRemorque</value>
      <webElementGuid>c4895f6c-eefd-433d-ae36-a0d51c65f734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierContratAssuranceRemorque</value>
      <webElementGuid>2252c03f-4d42-4914-a19b-d4a28a1ad8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierContratAssuranceRemorque&quot;]</value>
      <webElementGuid>5194487b-5fa6-4124-9ba6-e9c54f3356d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierContratAssuranceRemorque'])[2]</value>
      <webElementGuid>592b1f6c-fd56-4c0b-a9b0-2ccfe4a76698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>3802f64d-772d-47a6-8d13-3291c433af5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>96e74591-709e-482f-92d7-bb0342017fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierContratAssuranceRemorque' and @name = 'Attachement.FichierContratAssuranceRemorque']</value>
      <webElementGuid>2e80e4a9-8ae1-4515-9b1f-a07826053e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
