<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Attachement.FichierIdentiteAssure</name>
   <tag></tag>
   <elementGuidId>4128ca79-9b10-40b9-a637-c96539652bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierIdentiteAssure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Attachement_FichierIdentiteAssure'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d9c1f9d-0e66-4257-8542-c7eee8d897eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc3f1206-575b-4619-bb0b-acc779285ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>6dbb9575-d7cd-44a8-88da-9b8a5205cb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>a971ca77-737f-4828-9bfa-11c90a06c16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierIdentiteAssure</value>
      <webElementGuid>cb4db665-780e-4d8a-8362-ae2a90239579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierIdentiteAssure</value>
      <webElementGuid>c0b9be30-dbed-4cbf-82d9-4d41d7cebf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierIdentiteAssure&quot;]</value>
      <webElementGuid>cc44e2ca-323f-4dfb-9798-dfdf6c2ee693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierIdentiteAssure'])[2]</value>
      <webElementGuid>a5dcce60-542f-4def-a12b-04180c9ccd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>5b8a3b0a-9ddf-4db6-8955-a75172f470ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>334be0b9-c25d-4295-8b61-b8eba370270d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierIdentiteAssure' and @name = 'Attachement.FichierIdentiteAssure']</value>
      <webElementGuid>545f1cdd-b09b-4e4f-8baa-d79c4834cf15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
