<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Attachement.FichierCarteGriseRemorque</name>
   <tag></tag>
   <elementGuidId>62501625-d5d8-45cf-bb32-40569957df4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierCarteGriseRemorque</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Attachement_FichierCarteGriseRemorque']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c67ca9de-cc2a-4c84-b317-838f2a493e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a53e9211-0f1b-4165-8281-d6917b8aa32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>ab1c8de4-bfe7-4e1c-b8dd-94e7a0c26015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>be67467c-1dd2-4db3-90e2-1bdcfbfc295e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierCarteGriseRemorque</value>
      <webElementGuid>a28e2def-491e-409e-b7ed-3d54167e3e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierCarteGriseRemorque</value>
      <webElementGuid>24cf98fe-04df-402c-8310-36bcc6651ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierCarteGriseRemorque&quot;]</value>
      <webElementGuid>8261bbf2-4cad-4172-9af1-4a46b382706a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierCarteGriseRemorque'])[2]</value>
      <webElementGuid>d459c5b1-432c-4281-9e78-39d2e4506164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div[3]/div/div/input</value>
      <webElementGuid>996ef262-721a-40f6-afd3-7e499ea8cf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div/input</value>
      <webElementGuid>39d2cd5f-dbc1-4a3f-90fd-118144027dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierCarteGriseRemorque' and @name = 'Attachement.FichierCarteGriseRemorque']</value>
      <webElementGuid>95d49c74-3142-4326-936c-38d16113efd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
