<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ville_GarantieResidentiel.Ville</name>
   <tag></tag>
   <elementGuidId>85538c7b-7fad-42c8-8200-b4e776403084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieResidentiel_Ville']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GarantieResidentiel_Ville</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f93a079-6bc8-4814-bff2-602b12f74776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>cad2a0af-ffa0-4ffb-b890-1bc0d4b2c022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05cc708e-3f73-4e22-ab3d-27095f98cf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0e70194-5f76-4794-8e2d-ba10ccfce70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Ville est obligatoire</value>
      <webElementGuid>cec74802-2c51-4050-b0c8-ce9d5520a540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieResidentiel_Ville</value>
      <webElementGuid>d5a09029-05c5-4b46-bfc8-d2bcc83ee603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieResidentiel.Ville</value>
      <webElementGuid>ef2650b7-8142-44a8-ab53-27e975664547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieResidentiel_Ville&quot;)</value>
      <webElementGuid>0e902fa9-f512-4233-ae85-7f176d9467e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieResidentiel_Ville']</value>
      <webElementGuid>45873772-2165-47f0-8f7e-0a6be24522f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>30112a38-6426-402f-b9e9-0e03376fbc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>b36edd81-484a-4596-8e8f-ab1d3d98f608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GarantieResidentiel_Ville' and @name = 'GarantieResidentiel.Ville']</value>
      <webElementGuid>3fc2ac24-1679-4115-bd2e-5972b314c1f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
