<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Crer</name>
   <tag></tag>
   <elementGuidId>1d26ec3c-2637-4d25-91b5-7dcc781529fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='creationMission']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#creationMission</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>317d746a-9e4a-40cb-bcd4-8dac15f9ffca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>483a0ffa-26bf-498b-b479-22e3040af6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creationMission</value>
      <webElementGuid>dee0d94a-3ff8-4ae3-897f-23c1817acdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>80d154b8-7de1-4415-ab37-db1e1eec635e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Créer
                        </value>
      <webElementGuid>d9d924d8-0b78-4a25-aae7-5ea842ab8979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creationMission&quot;)</value>
      <webElementGuid>8faf3b13-a418-4d21-bf55-1e3300feb250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='creationMission']</value>
      <webElementGuid>a8661fd9-2065-4143-b2ff-021c1c084ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createMission']/div[3]/button</value>
      <webElementGuid>411ba9c3-1d45-41fc-8196-23ee015552ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Les fichiers selectionnés'])[1]/following::button[1]</value>
      <webElementGuid>fef1a748-54b3-4570-9762-8efa29a765d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parcourir'])[1]/following::button[1]</value>
      <webElementGuid>9db59f6e-7d66-4f34-8239-19a54bb3e23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lignes par page :'])[1]/preceding::button[1]</value>
      <webElementGuid>334b8278-ca35-48e7-9199-0a700940d0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réference du dossier sinistre'])[1]/preceding::button[1]</value>
      <webElementGuid>1476ef26-5f09-4b85-bf9a-9244d1feca93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Créer']/parent::*</value>
      <webElementGuid>cd1fb426-f3bc-4352-886e-833e72a6d8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>62b7063b-9a2b-4de3-af46-e29cc344a887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'creationMission' and (text() = '
                            Créer
                        ' or . = '
                            Créer
                        ')]</value>
      <webElementGuid>ee10e377-c49d-4acc-aedd-23b083503201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
