<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_BENI BOUAYACH</name>
   <tag></tag>
   <elementGuidId>c3d7ac67-869d-41c3-b514-10384487cc36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-spec']/div[4]/div/div/div/div[2]/div[2]/ul/li[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>257d390d-8ce8-4570-b391-c351eca82d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>690ba2da-03cd-4b3b-b6a2-57ad90fe3875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>27a91916-413f-44c2-80c7-855b03afa8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b9458c81-3019-4759-a75e-4dad6bbe232a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BENI BOUAYACH</value>
      <webElementGuid>7c1d2ff8-c516-4395-bc76-fb03a64395da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div-spec&quot;)/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes open-top active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>fd15cb4d-b89c-4140-b173-2b4841131e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-spec']/div[4]/div/div/div/div[2]/div[2]/ul/li[7]</value>
      <webElementGuid>2d06b7b8-8c18-4642-9636-cee44b3565be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AL HOCEIMA'])[2]/following::li[1]</value>
      <webElementGuid>adf0f87b-220b-4c71-b3d2-134a0c1960bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMZOUREN'])[2]/following::li[2]</value>
      <webElementGuid>453bd3ac-5c5d-4ce4-8b5d-b61ebedc89b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TARGUIST'])[2]/preceding::li[1]</value>
      <webElementGuid>fcc58e9f-6aef-43dc-91b8-8e8a3cae03a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TICHLA'])[2]/preceding::li[2]</value>
      <webElementGuid>2d4350d2-fe04-4d4e-9de4-7fa606ab5a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div[2]/ul/li[7]</value>
      <webElementGuid>c1676d67-ad41-4f2a-9d39-3018f2d45095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'BENI BOUAYACH' or . = 'BENI BOUAYACH')]</value>
      <webElementGuid>ebba7ac9-1882-4b53-8fa4-6922ffef0c4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
