<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_IND.MAR.2022.8DC1_MAT82DM1</name>
   <tag></tag>
   <elementGuidId>34c21fe3-0cd9-43c6-9190-a8e8221ea5c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-spec']/div/div/div/div[2]/div[2]/ul/li[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0dc131ca-91f7-4d16-b1be-dd7215337c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>db88e53f-ef25-4526-a63f-c35d61031212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>4003f9cd-8fb1-45f7-820f-773e26972e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>be01da9e-c83d-41ab-8ff6-f341e3d76d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IND.MAR.2022.8/DC1_MAT/82/DM1</value>
      <webElementGuid>98d839ae-d449-456c-a420-bf1bccb9c64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div-spec&quot;)/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>1faf2dea-cd56-4b66-81ee-e61357e5428f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-spec']/div/div/div/div[2]/div[2]/ul/li[5]</value>
      <webElementGuid>5e5efe77-b506-4a24-9e6f-85879f30db19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D.EVCAT15032022/DC3_MAT/91/DM7'])[2]/following::li[1]</value>
      <webElementGuid>73b64b45-b8a4-4237-974a-0c2530bed07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D.EVCAT15032022/DC18_COR/82/DM6'])[2]/following::li[2]</value>
      <webElementGuid>48092e51-0ca9-46e5-a9b0-a324eea6108e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D.EVCAT15032022/DC19_MAT/82/DM8'])[2]/preceding::li[1]</value>
      <webElementGuid>1a057b1c-37db-42b3-8dd3-868ad1012385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D.EVCAT15032022/DC20_MAT/91/DM9'])[2]/preceding::li[2]</value>
      <webElementGuid>2d6b0834-93f4-4890-82e6-d85dc244c31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/ul/li[5]</value>
      <webElementGuid>c0ff66d0-7a57-4252-916e-0d0ea18448d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'IND.MAR.2022.8/DC1_MAT/82/DM1' or . = 'IND.MAR.2022.8/DC1_MAT/82/DM1')]</value>
      <webElementGuid>f47c8ca5-5332-44d5-bea8-a94dec9b2d47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
