<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Parcourir</name>
   <tag></tag>
   <elementGuidId>d251b4fb-8c26-49cd-bad2-d6fe9f3802d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section/div[1]/div/div/div/div/div[2]/div/form/div[5]/div/div[2]/div/label[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.multi-Upload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>65365d5d-b1ab-45c1-b0f8-1bfeaa6d365c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multi-Upload</value>
      <webElementGuid>c4a97d73-2441-4625-8b70-d22c01ddd16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Parcourir </value>
      <webElementGuid>84ee4f96-78c4-48b4-8ea1-8ab1c1657b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-12&quot;]/label[@class=&quot;multi-Upload&quot;]</value>
      <webElementGuid>e5a305fa-c4e0-4362-8f92-6b411dab5198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div[2]/div/label[2]</value>
      <webElementGuid>8cf2551a-f4cb-43bb-89e4-8ba426b1d131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autres'])[1]/following::label[1]</value>
      <webElementGuid>4f910128-bb5a-43cd-8c63-63b107c132ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parcourir'])[1]/following::label[2]</value>
      <webElementGuid>0f5e3a2a-7598-45ac-8264-5df4ed79b633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Les fichiers selectionnés'])[1]/preceding::label[1]</value>
      <webElementGuid>9700b944-c6a7-4861-9c7a-52958ee47463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enregistrer le brouillon'])[1]/preceding::label[1]</value>
      <webElementGuid>60da4a53-ca79-466b-a332-ab9907e0b2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label[2]</value>
      <webElementGuid>79027971-83c2-4e0b-ba52-7b17afb77d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '  Parcourir ' or . = '  Parcourir ')]</value>
      <webElementGuid>12854240-1dc8-4de5-b285-5b6015eaf8ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
