<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_D.EVCAT15032022DC12_MAT82DM2</name>
   <tag></tag>
   <elementGuidId>f7dda660-a794-47e9-b2a1-998792111206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='MissionForm']/div/div[5]/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>179b753b-baf3-456b-876f-ddb84a9d0d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Réference du dossier sinistre</value>
      <webElementGuid>24f905c5-a95f-4396-99f6-1639e90b3a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>D.EVCAT15032022/DC12_MAT/82/DM2</value>
      <webElementGuid>5793f149-96f5-47a4-8b76-3cbd78b5b5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MissionForm&quot;)/div[@class=&quot;row MissionTable&quot;]/div[@class=&quot;col-lg-12 responsive-table-line custom-table-css&quot;]/table[@class=&quot;omn-table table table-condensed table-body-center actions&quot;]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>8b052e62-9759-4ab5-9730-7a21dc2bde2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MissionForm']/div/div[5]/table/tbody/tr/td</value>
      <webElementGuid>92716331-134d-47b1-b071-fe2919183955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::td[1]</value>
      <webElementGuid>1b6b82e5-9441-4936-9f81-a7e457807267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Date d', &quot;'&quot;, 'affectation')])[2]/following::td[1]</value>
      <webElementGuid>1ee0c2a3-be8d-4a5a-b24f-943785e22ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmé'])[1]/preceding::td[1]</value>
      <webElementGuid>9c5427c2-754c-4c18-baa0-05b5fe2c91f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVCAT.MAT.0315/OM_0062'])[1]/preceding::td[2]</value>
      <webElementGuid>4f914d29-9633-475d-98aa-585adf37e996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>1f2897f0-268f-4bf7-b63c-64d5404f91d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'D.EVCAT15032022/DC12_MAT/82/DM2' or . = 'D.EVCAT15032022/DC12_MAT/82/DM2')]</value>
      <webElementGuid>8214b1f5-d5af-4b9f-957d-b3f6f590e105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
