<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Caschocher</name>
   <tag></tag>
   <elementGuidId>f7b27910-9973-4f1d-9374-2b4582889e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/section/div[1]/div/div/div/div/div[2]/form/div[2]/div/div[2]/div[5]/div[1]/div[2]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Input_Login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a634bd0d-2399-4b45-b114-7da99445a253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>070dce24-e80a-48d1-ab31-6faa590d9d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55fa8d29-0067-4804-ae75-34802123e712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc2138d4-2fc0-42a5-a778-ecec6df36819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Login field is required.</value>
      <webElementGuid>129a5993-8a56-419c-a09c-30c2f93c4df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Login</value>
      <webElementGuid>f18cd057-6477-4cfb-b12b-48066d31ece5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Login</value>
      <webElementGuid>98771619-76db-4485-8ed8-83a6feb231ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_Login&quot;)</value>
      <webElementGuid>2e8f9020-2dfe-4af4-96a3-ef0e665cc4a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_Login']</value>
      <webElementGuid>224ad55d-9c86-4c60-9010-f60ce9bb84a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>fe015394-7b54-406b-a84b-e706a290999e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fb59ed06-d953-49d4-9afc-285cbfdad963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Login' and @type = 'text' and @id = 'Input_Login' and @name = 'Input.Login']</value>
      <webElementGuid>360bf5e1-61f4-407c-8803-d0c259701666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
