<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AGADIR</name>
   <tag></tag>
   <elementGuidId>4c60d6c0-dfcf-435e-8d2d-28f35e7b90e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='tail-select no-classes']//div[@class='select-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div-spec > div.row.mb-3 > div.col-sm-6 > div.box > div.tail-select.no-classes > div.select-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcafa85b-2624-4548-b92e-3a18496f3498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-label</value>
      <webElementGuid>98ead6e5-f455-42e2-aac4-8766e6e25b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AGADIR</value>
      <webElementGuid>50b3eea6-8d3c-43f6-9c51-c1d56fb0cec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div-spec&quot;)/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes&quot;]/div[@class=&quot;select-label&quot;]</value>
      <webElementGuid>7a947894-255f-4f77-b9ce-10b20f8e01c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@class='tail-select no-classes']//div[@class='select-label']</value>
      <webElementGuid>256a21cc-9037-4226-906b-b837036edd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[3]</value>
      <webElementGuid>1d79b90e-26b6-4016-bb73-f4a3edaabcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AGADIR'])[3]/preceding::div[2]</value>
      <webElementGuid>656ac5a8-fc97-4184-abfd-ced1c8d81bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>d74adba1-c21f-4a10-9f54-90d7d368e432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AGADIR' or . = 'AGADIR')]</value>
      <webElementGuid>a7fceddc-b082-4651-bd9a-647a2aa39067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
