<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lignes par page_searchString</name>
   <tag></tag>
   <elementGuidId>d2f2b7b4-ab8b-4bac-89f7-148d15a6b623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchString&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d09ff97d-cefc-4c7d-9f77-ee79effdd48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50c6bb84-ac0c-4440-b700-5c66feffdb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>9c091fbd-de7f-4531-ba91-d16e3a0e617f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchString</value>
      <webElementGuid>f4ab3f10-77ae-483d-832f-0ec6cc963759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userForm&quot;)/div[@class=&quot;row UserTable&quot;]/div[@class=&quot;col-sm-6 6 mt-1 barre-tab&quot;]/input[1]</value>
      <webElementGuid>f103b63d-e636-4daf-bf6b-3b6098c3830c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchString']</value>
      <webElementGuid>1ccb92ae-e274-4359-8419-4338dfbde509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userForm']/div/div[3]/input</value>
      <webElementGuid>a02b6261-ef9b-49cd-8eae-c012098c1a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4ad7070e-2eee-4eb7-bea2-6d5bc03ed35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Rechercher' and @name = 'searchString']</value>
      <webElementGuid>bb7295b0-faaa-49e4-9c6b-9d9aefb9d238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
