<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ville_GarantieIndustriel.Ville</name>
   <tag></tag>
   <elementGuidId>2a8749e2-f1b0-47b8-8378-4beea9b6d8bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GarantieIndustriel_Ville</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieIndustriel_Ville']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01235b63-1432-43cd-afca-4a729202f89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>e5f53254-951a-445d-bc98-f85373a3ad9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>389c7c74-826c-4c56-96c7-f799d89b9943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eeb52329-68ed-49c9-89ae-399f1bfacb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Ville est obligatoire</value>
      <webElementGuid>cad8c79b-c33a-47d8-b430-9b5499f89f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieIndustriel_Ville</value>
      <webElementGuid>4e86089d-3f22-46ac-8061-4bc027c37a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieIndustriel.Ville</value>
      <webElementGuid>9d3578f8-26b1-4029-8bce-092ebc9882cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieIndustriel_Ville&quot;)</value>
      <webElementGuid>b3e88465-ac36-4ce2-b435-706b40324693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieIndustriel_Ville']</value>
      <webElementGuid>fe11eee2-6d08-4f1b-a5bd-8c87654783a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>59d0c387-0693-4f80-a43b-4545b6667d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>52883506-315f-4698-bb78-210f4fc01e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GarantieIndustriel_Ville' and @name = 'GarantieIndustriel.Ville']</value>
      <webElementGuid>52deafd7-1652-45e5-b0e7-363a0a71d1cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
