<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adresse_GarantieIndustriel.Adresse</name>
   <tag></tag>
   <elementGuidId>ee0eb943-dc23-4417-9063-40f2c3f0be14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GarantieIndustriel_Adresse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieIndustriel_Adresse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f17e206c-2cfa-400c-ac66-e15e0a2993ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>dc9298a6-044c-4b90-969c-fe7069d20b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f197800f-0dd4-4fd1-9382-f62ebe9bef8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc5f7fca-5e58-4acb-9d3d-24a4799c3c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Adresse est obligatoire</value>
      <webElementGuid>095d75fa-5022-42f2-8c2f-ebd49b6e3b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieIndustriel_Adresse</value>
      <webElementGuid>f5fb8c3e-ad1b-45fa-b0ee-3ce558f0353d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieIndustriel.Adresse</value>
      <webElementGuid>7c93c873-d909-4982-bb8c-84eaf15fc6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieIndustriel_Adresse&quot;)</value>
      <webElementGuid>d8846862-1a8c-453f-aba6-4c3993338398</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieIndustriel_Adresse']</value>
      <webElementGuid>fc0778a2-6dc6-48a1-955a-9f51836ed991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>7d237da1-ee48-4391-b6b1-542cc3eee7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>5efbb37a-dbf0-467c-b3b2-a113d45e5329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GarantieIndustriel_Adresse' and @name = 'GarantieIndustriel.Adresse']</value>
      <webElementGuid>a703fa20-b921-42ec-8d8e-0767627ee5c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
