<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Connexion</name>
   <tag></tag>
   <elementGuidId>e57c9fde-1f85-4252-b4ab-07fc6549496a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.lf-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9f78755-160a-4c96-980a-4094d1d2d1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-button</value>
      <webElementGuid>d09c2690-f0fe-409c-badf-466e5b8017d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>5184cdf0-9f9b-4f98-bf12-357f9a780c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account&quot;)/div[@class=&quot;back&quot;]/div[@class=&quot;authentification&quot;]/div[@class=&quot;container ogul&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;log-in&quot;]/button[@class=&quot;lf-button&quot;]</value>
      <webElementGuid>c4c7dfcc-e0c8-4e57-8774-3e90d3295619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>ed65f6ac-007d-4d85-a484-071a09d135fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connexion'])[1]/following::button[1]</value>
      <webElementGuid>bd1bfbc7-0559-42f5-8067-4dd5a655127d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe oublié?'])[1]/preceding::button[1]</value>
      <webElementGuid>ea64bdea-44d8-4e11-a83d-355fd98b9850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>159d7500-f3b0-4305-aab4-96ddf0265f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Connexion' or . = 'Connexion')]</value>
      <webElementGuid>2b307f98-f772-4cc6-ab9d-d4dd375419ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
