<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ajouter</name>
   <tag></tag>
   <elementGuidId>f5057d8b-f556-47c9-b571-31a388c0f262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='paramForm']/div/div[2]/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.out</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>190f6e71-b021-4d2f-8a3f-94aab642f8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1be63b2-7274-4e34-b7b9-4ac812a893ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>f64d006e-7adb-4710-9c9e-62d411b4bd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsDropDown</value>
      <webElementGuid>c51bf463-1bd3-4aff-967b-ac8186477d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidationParam</value>
      <webElementGuid>a931274a-1a28-4d8a-b518-b5536687b597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#add-parametres</value>
      <webElementGuid>963c478c-c962-4cd1-bce6-d39cf10d31c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>after</value>
      <webElementGuid>79fedd3c-9f0a-4a5e-b4b3-6c4b8826c1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Parametre/AddNewParametre</value>
      <webElementGuid>4208a313-9c88-4b29-a61d-8a25d1547d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>HelloWorld</value>
      <webElementGuid>e1f28d00-5bf6-4f08-ae05-69400949060d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn out</value>
      <webElementGuid>39f8d71b-f9b9-42f1-bf98-11c4d4aee907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajouter
                                                </value>
      <webElementGuid>7929f22a-b49d-41b1-b430-065bc10d79c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paramForm&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 text-right&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-lg-12 text-right&quot;]/a[@class=&quot;btn out&quot;]</value>
      <webElementGuid>6460eb12-2b9b-480d-bdcd-67ccf0156b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paramForm']/div/div[2]/div[2]/div/div/a</value>
      <webElementGuid>f01a7f1d-a181-4a67-8004-7b475a3f5f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ajouter')]</value>
      <webElementGuid>a3848dda-c1d0-4e10-bcb9-3009b076f9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enregistrer'])[1]/following::a[1]</value>
      <webElementGuid>f30ea7d8-73db-4c72-94fa-aa5be4b0f262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre de dossier à traiter par la CAT'])[1]/following::a[1]</value>
      <webElementGuid>7cc72453-50a2-43c2-95f8-e109690d6a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lignes par page :'])[1]/preceding::a[1]</value>
      <webElementGuid>5be96151-c40a-444c-98d9-80dc14141957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Référence EVCAT'])[1]/preceding::a[1]</value>
      <webElementGuid>76d9d288-211c-4ca2-a2dd-26dd3fb4ee3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajouter']/parent::*</value>
      <webElementGuid>31ec7659-8f3b-4559-a563-4728e35eaaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Parametre/AddNewParametre')]</value>
      <webElementGuid>13967fc6-6558-4507-82af-44147d74e080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>30932e3e-2b80-4a45-8d64-0a34761edd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Parametre/AddNewParametre' and (text() = 'Ajouter
                                                ' or . = 'Ajouter
                                                ')]</value>
      <webElementGuid>6e5377ed-a8e7-42b6-a55f-c45ae9f03f19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
