<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lignes par page_searchString</name>
   <tag></tag>
   <elementGuidId>b0bd4970-c652-498f-849a-9acbd4a57954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchString&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a974751b-264d-42c1-aa6e-72c718ed3fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33e72d2b-19c2-4485-9a6e-d189cce9c1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>dddd288b-bb0c-4995-9b4c-84d027e3fdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchString</value>
      <webElementGuid>673ae188-7294-4039-8b05-6efe671f9df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parametreForm&quot;)/div[@class=&quot;row parametreTable&quot;]/div[@class=&quot;col-sm-6 6 mt-1 barre-tab&quot;]/input[1]</value>
      <webElementGuid>28cc3719-623c-418c-bc08-f4ed2f305100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchString']</value>
      <webElementGuid>38cef00a-09c9-449c-b876-015e861502d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='parametreForm']/div/div[3]/input</value>
      <webElementGuid>111de677-9dce-4670-bc6a-5e091218100d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b5f950f5-85c1-46b8-89d4-3fc24e536e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Rechercher' and @name = 'searchString']</value>
      <webElementGuid>a3a13441-aa9d-49aa-a366-d709ae63318a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
