<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre de dossier  traiter par la CAT_e0563b</name>
   <tag></tag>
   <elementGuidId>95ae09d5-8f85-4608-bdc4-43c20e3cbd2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dossiers_e8eea55d-3309-4d1e-8085-9dda9fbb45c6__NumberDossier</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01dafd89-6213-40f0-9923-1018d98b089c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a7b852b-6f33-4112-b8f7-0da7bbb13d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e309e06-b52e-4f5e-a219-46bfefa3e485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Seules les valeurs entières sont autorisées</value>
      <webElementGuid>439239f1-34d5-43b3-8494-25cc3149635f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>[0-9]+</value>
      <webElementGuid>89c9e47c-5134-472d-a9e3-d3907e5a2799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer un nombre de dossier</value>
      <webElementGuid>e474bcaf-de00-4655-aedb-7cf407f012d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dossiers_e8eea55d-3309-4d1e-8085-9dda9fbb45c6__NumberDossier</value>
      <webElementGuid>a894c7e5-4ea1-4449-b28b-0a32d055632e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dossiers[e8eea55d-3309-4d1e-8085-9dda9fbb45c6].NumberDossier</value>
      <webElementGuid>73337ef8-8f16-4ef9-8933-1e4fed94f37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dossiers_e8eea55d-3309-4d1e-8085-9dda9fbb45c6__NumberDossier&quot;)</value>
      <webElementGuid>03e9249a-fad4-4bf0-971a-55153b60e3a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Dossiers_e8eea55d-3309-4d1e-8085-9dda9fbb45c6__NumberDossier']</value>
      <webElementGuid>811a8043-6faf-4cf3-a0ca-8330b5cdf838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e8eea55d-3309-4d1e-8085-9dda9fbb45c6']/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>2f1d5bb0-6df0-4779-9cc0-e629bc197140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/input</value>
      <webElementGuid>95da77fd-5975-49dc-b616-a3741c32e7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Dossiers_e8eea55d-3309-4d1e-8085-9dda9fbb45c6__NumberDossier' and @name = 'Dossiers[e8eea55d-3309-4d1e-8085-9dda9fbb45c6].NumberDossier']</value>
      <webElementGuid>1dd85627-4286-4eaa-b918-31150469ab2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
