<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OrdreAvocat</name>
   <tag></tag>
   <elementGuidId>08383c5e-3cbd-44d2-9994-86378186d564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OrdreAvocat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OrdreAvocat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31fdcf6a-ed41-48c4-be41-78f40ceed7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c04d3e0-4036-4c88-b6fe-6f88b6cc5415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6730f136-022c-4d82-8370-63bb24527006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Valeur non valide</value>
      <webElementGuid>e87750d7-ffbe-4576-bc7b-917c16af13d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>.*\S+.*$</value>
      <webElementGuid>e688dcf2-db33-46bc-b3e2-f8db29ad260d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'Ordre des Avocats</value>
      <webElementGuid>c64f28e1-0f37-4a45-9eab-34a9208aa88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OrdreAvocat</value>
      <webElementGuid>76437688-de86-45e7-9964-5ae0ad9521bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OrdreAvocat</value>
      <webElementGuid>3831fc9e-c201-4989-8aac-c7b1fd2e4355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OrdreAvocat&quot;)</value>
      <webElementGuid>94e8575d-c1ef-46a9-8532-90883b5e2a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OrdreAvocat']</value>
      <webElementGuid>ac89a86f-8860-4c30-8c22-8634f2cdd6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/form/div/div[7]/div/input</value>
      <webElementGuid>f608ce98-cdbc-4a91-8ea3-742158175c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>84501579-90ce-47dd-89f2-efa6e0f588eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'OrdreAvocat' and @name = 'OrdreAvocat']</value>
      <webElementGuid>33a04fb5-ff96-483c-adb5-c8c7410658de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
