<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__JuridicationTPI</name>
   <tag></tag>
   <elementGuidId>f35a42b2-87c7-49ed-9cbd-1fbd0845a266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JuridicationTPI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JuridicationTPI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e982cb7-ae4f-46e9-94b5-557b3d608dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f3fd9ee-c7f4-4c80-aba9-f1d5e0dd1b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3afb5976-fc57-4b5e-97f9-9207c3e58abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Valeur non valide</value>
      <webElementGuid>54faee1f-e943-41c2-b66d-f159aa3e8204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>.*\S+.*$</value>
      <webElementGuid>f472ebfd-ebe1-496b-9eb2-2e5c0765e59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir la Juridication TPI</value>
      <webElementGuid>f553b448-efe3-4348-8a4d-bf31178af376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JuridicationTPI</value>
      <webElementGuid>20f0fa38-e294-4055-a8e1-f19fa0707bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JuridicationTPI</value>
      <webElementGuid>aa43a5b5-0e8b-4576-8f74-59affca942ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JuridicationTPI&quot;)</value>
      <webElementGuid>afaef6dd-45fb-4c84-8ff1-51275db1f4ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JuridicationTPI']</value>
      <webElementGuid>95db0a4e-0dee-47c9-b116-806764fe6ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/form/div/div[8]/div/input</value>
      <webElementGuid>3212621b-56ae-4f25-8cac-a1e89c7bd81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>ec3eee8d-0ecb-4aba-bdc0-3ca40a7d004b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'JuridicationTPI' and @name = 'JuridicationTPI']</value>
      <webElementGuid>e30ed792-0bd4-4467-9244-a26d11007b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
