<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__JuridicationCA</name>
   <tag></tag>
   <elementGuidId>a6449ad1-0e24-44e3-ac49-f32c69b4172d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JuridicationCA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JuridicationCA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65102014-ffab-4a41-966a-be01ebdfd621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>537088ce-43d3-4536-afbd-a69e250dddd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f497926-6b8f-4a0a-87e8-80e27b8b6447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Valeur non valide</value>
      <webElementGuid>a746c478-7fdb-41fb-b8f4-9157a2b574aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>.*\S+.*$</value>
      <webElementGuid>f4e30011-391a-4233-94ba-06646ff28bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir la Juridication CA</value>
      <webElementGuid>4118fc51-8a46-45ec-86cf-4fa0fcfb6fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JuridicationCA</value>
      <webElementGuid>ab9dd0df-5e0e-4dce-9731-644e7f2a9328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JuridicationCA</value>
      <webElementGuid>1bcc0bec-3b5f-4e4b-b43e-ee34abd9a446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JuridicationCA&quot;)</value>
      <webElementGuid>26e2277c-f1f5-4400-aa9c-7e24f7a27c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JuridicationCA']</value>
      <webElementGuid>2fb6a6fa-c6b2-4a3a-ae0b-50962c39ff6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/form/div/div[7]/div[2]/input</value>
      <webElementGuid>48c8dda5-ed0b-49b5-9092-dd8e27da53e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>e2225854-0d72-4d26-bba7-6d100db8dec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'JuridicationCA' and @name = 'JuridicationCA']</value>
      <webElementGuid>0e2db9db-24c0-4f95-8d91-a148cec90f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
