<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GSM</name>
   <tag></tag>
   <elementGuidId>471ef977-77f0-4cc4-b684-fd7bef17b397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GSM']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GSM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9f7cadb-0853-4df4-8a50-4e0af8f8497f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a21c796c-1221-4829-9733-623a4bb673ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94d6a911-8ed9-4ca3-ba9f-b3b2c3c12cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Numéro de téléphone non valide</value>
      <webElementGuid>7ea724de-de17-406d-85d5-5514e7dd18ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(?:(?:\+|0)?|0)[1-9](?:(?:[\s]?\d{2}){4}|\d{2}(?:\d{3}){2})$</value>
      <webElementGuid>0d81083a-9d74-478c-8672-e821fa7b7b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro GSM</value>
      <webElementGuid>bdfa0f37-4977-42af-a647-7fbb255e88d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GSM</value>
      <webElementGuid>7ac0bd28-1b3a-42a9-aa6b-6e03e5005f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GSM</value>
      <webElementGuid>c2d9a26c-245d-4bdb-9f49-01ef4101b3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GSM&quot;)</value>
      <webElementGuid>dadc776e-fa35-481a-b06c-9746fe476ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GSM']</value>
      <webElementGuid>3824651d-37a4-4938-be26-9bcaa0e1a763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/form/div/div[2]/div/input</value>
      <webElementGuid>87ce97e9-5b86-4919-ba8c-cd450fe35d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>648897b3-ea8a-4edf-a803-5818d511bc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GSM' and @name = 'GSM']</value>
      <webElementGuid>54e0175e-1e6a-4c22-be62-3fd25a58ac27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
