<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Connexion</name>
   <tag></tag>
   <elementGuidId>67bdc02e-415e-47be-88f3-b52a814f3b0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.lf-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>718179d2-47b9-46b7-9879-254e7476243e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-button</value>
      <webElementGuid>9c7a0f7b-41dc-4ab9-b9ba-a2d6baba9ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>2605215f-14b7-4710-98b6-702e24861c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account&quot;)/div[@class=&quot;back&quot;]/div[@class=&quot;authentification&quot;]/div[@class=&quot;container ogul&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;log-in&quot;]/button[@class=&quot;lf-button&quot;]</value>
      <webElementGuid>a84e5521-29c1-40e0-936d-00e85b9cfc9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>d275f96c-5df8-4fd9-b791-0bbb32437ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connexion'])[1]/following::button[1]</value>
      <webElementGuid>a65a7c11-2b17-487c-9972-2d066a91f121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe oublié?'])[1]/preceding::button[1]</value>
      <webElementGuid>95888adc-ec89-42e9-afd5-f20c3ab7ae47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>85ca8e56-7f4d-4ce5-be9f-79cd9c7837a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Connexion' or . = 'Connexion')]</value>
      <webElementGuid>2c040433-73e8-427f-b3e6-03f1e3dc13b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
