<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adresse_GarantieResidentiel.Adresse</name>
   <tag></tag>
   <elementGuidId>9b2592a8-48e5-43da-8744-5c96582eec03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieResidentiel_Adresse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GarantieResidentiel_Adresse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee740e2d-33e3-46b2-9ba6-56bc36f0bacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>a33528f4-4e71-480e-a0ba-3e9786a835bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcae64b9-ef0b-4627-a8d4-cfb9f458b9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44c21a05-da95-47e9-bad9-17c4406f5677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Adresse est obligatoire</value>
      <webElementGuid>8f33545b-db95-4cdd-bd6a-6e228848835c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieResidentiel_Adresse</value>
      <webElementGuid>9274d514-b410-49f1-9806-9c2256dceb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieResidentiel.Adresse</value>
      <webElementGuid>4df41471-ccdd-47c0-8d94-478520257001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieResidentiel_Adresse&quot;)</value>
      <webElementGuid>b25259b2-dd36-4674-ab0f-cac4df74c83e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieResidentiel_Adresse']</value>
      <webElementGuid>a27fba3e-185b-4e49-89b1-4e0d8085c0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>5673ad1d-439d-4f4d-a183-1dbd2d24cd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>a0e89055-d3ec-4a54-9084-cd076809a279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GarantieResidentiel_Adresse' and @name = 'GarantieResidentiel.Adresse']</value>
      <webElementGuid>e5ac1e5f-2f94-415d-bcfe-5fc0dd49acb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
