<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Assure.Gsm</name>
   <tag></tag>
   <elementGuidId>75e12054-b5ca-47ba-bb4c-0c99b6028eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Assure_Gsm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Assure_Gsm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cba07c5-16db-4566-8f4b-1b6d5a61a7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0aa10c0-a14d-4c49-9bdd-65ace1be210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>c8dd2e10-cc36-426a-944d-a3fc69da03c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31cd13e4-6044-4793-a46e-429ab04605eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Numéro de téléphone non valide</value>
      <webElementGuid>335be0d3-b621-4ec5-a9ad-62f1d45360ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(?:(?:\+|0)?|0)[1-9](?:(?:[\s]?\d{2}){4}|\d{2}(?:\d{3}){2})$</value>
      <webElementGuid>2b709e34-1906-4ad1-8dcf-db1ef7c1512a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro GSM</value>
      <webElementGuid>797cc4bc-4977-48db-b618-b30163d4d888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assure_Gsm</value>
      <webElementGuid>ee29697f-60f8-4e29-bac7-de35e890f97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Assure.Gsm</value>
      <webElementGuid>e5c66bd2-dce0-4cef-9532-e61ab57067be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47ce48f1-416c-4cb1-9893-3b21628a4a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__ __ __ __ __</value>
      <webElementGuid>74defe21-6b53-4379-8e14-d15cfeea6c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assure_Gsm&quot;)</value>
      <webElementGuid>eade6868-2933-4b0d-aff4-b38cc74c1f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Assure_Gsm']</value>
      <webElementGuid>de5081d8-69ad-4dc1-8a4e-be75d80a2d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autreQualiteDemandeur']/div/div/div[3]/div[2]/input</value>
      <webElementGuid>f835d725-e39f-4fc9-ad99-5dba1513e3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[2]/input</value>
      <webElementGuid>bff848c6-7e54-4565-a294-f86d91e3f87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Assure_Gsm' and @name = 'Assure.Gsm' and @placeholder = '__ __ __ __ __']</value>
      <webElementGuid>58c86b4a-31d5-451c-9cdb-048f63f1ffad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
