<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IF du dclarant_Declarant.IF</name>
   <tag></tag>
   <elementGuidId>bf31964e-a0cb-4327-a137-7edd1e04d0c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Declarant_IF</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_IF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85b14d7b-91b5-4e9c-b288-0a4a277e8fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9faa0b4-bb2e-4cc6-9bef-0416b6ba45ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_IF</value>
      <webElementGuid>78b03519-a557-4f6b-9dd2-83f79a7a3276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.IF</value>
      <webElementGuid>e9e766a3-391a-4566-94e6-e2f3b7518de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_IF&quot;)</value>
      <webElementGuid>6c2d2373-3c7d-4685-8ce6-73988033f3d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_IF']</value>
      <webElementGuid>f554d1d7-a036-4547-8632-8c1dc3725926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>5da7ea28-5605-4a9f-9112-d4347e4d51f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>9c6e96b0-938e-433f-8efa-b995cb221fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_IF' and @name = 'Declarant.IF']</value>
      <webElementGuid>86a640ce-0d13-46f0-b623-cdf76c987538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
