<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lvnement a t cr avec succs sous la rfre_f62dbc</name>
   <tag></tag>
   <elementGuidId>13654bec-1456-45db-9e09-c31848274847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.toast-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f80c076a-02f1-4b73-b336-386afd3bab98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast-title</value>
      <webElementGuid>606414cb-5c55-4920-8813-d9914bb97a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>L’événement a été créé avec succès sous la référence P.2023.05.11.TER</value>
      <webElementGuid>ae2d9caa-6b28-4845-9f2d-f876de776a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;toast toast-success&quot;]/div[@class=&quot;toast-title&quot;]</value>
      <webElementGuid>a0051bff-1996-4bc9-8396-ae466d63cdab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div/div</value>
      <webElementGuid>4a2dab6d-9b61-44e5-9b23-44005e2c53b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 All Rights Reserved.'])[1]/following::div[3]</value>
      <webElementGuid>15308082-8085-403c-aeca-ae6bb3c21822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/following::div[4]</value>
      <webElementGuid>4317eab1-75e9-4433-9b29-bd8d532d5386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='L’événement a été créé avec succès sous la référence P.2023.05.11.TER']/parent::*</value>
      <webElementGuid>41d9f068-1063-4fa2-8347-31a3ecbf1c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>9841627d-0f73-4a71-96b1-b1229ab70206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'L’événement a été créé avec succès sous la référence P.2023.05.11.TER' or . = 'L’événement a été créé avec succès sous la référence P.2023.05.11.TER')]</value>
      <webElementGuid>3dec7061-627d-499b-8b4f-24bb2e2f5676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
