<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Identification de la dclaration</name>
   <tag></tag>
   <elementGuidId>d07e856e-5f26-4043-b624-e6a3832f6f29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuer'])[1]/preceding::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tableDeclarationForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c11468e-0545-4bcd-ab22-e1a96ea9d420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b927de7-8b69-4916-87e3-258cc374963b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>c77fa104-34cd-4815-9a9d-fd5ace09e9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/get-table-demande</value>
      <webElementGuid>b2d88dac-383d-48df-ba1d-e228ccf86942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>b4a60b49-b879-4b1b-a017-8de10510c27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-begin</name>
      <type>Main</type>
      <value>ajaxBeforeSubmit</value>
      <webElementGuid>c2b3f0b7-0d43-4eb5-a277-081eddb6fb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsSinistre</value>
      <webElementGuid>69c285ff-0479-40d5-9333-669ad4cfa87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidationSinistre</value>
      <webElementGuid>8b76bb50-43b0-4ca5-b7a1-0d4df2137151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#declartionIdentity</value>
      <webElementGuid>d85d494f-8624-4a36-acd9-f0ae592d39e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>a0818f1a-ee8e-4961-94b3-9bc9253eae35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn link out</value>
      <webElementGuid>209605db-312e-40ff-9781-4720e1bfe25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identification de la déclaration
                                                </value>
      <webElementGuid>46a10f83-af2e-43db-935f-7ef6c0868389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableDeclarationForm&quot;)</value>
      <webElementGuid>e8073c07-b2e7-4806-a73d-49f84017d4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tableDeclarationForm']</value>
      <webElementGuid>692d6679-4cb1-4e96-8493-0f5dad58ec1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dommageInfos']/div[5]/div/div/a</value>
      <webElementGuid>8f73de42-57d9-446c-bcbd-ec784369d543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Identification de la déclaration')]</value>
      <webElementGuid>9cc66315-622d-4141-a34b-73381b17410b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::a[1]</value>
      <webElementGuid>c56b3d77-f18a-4026-8fb5-f312326254ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuer'])[1]/preceding::a[1]</value>
      <webElementGuid>8521a680-3dda-48e4-b8c6-827b9abeb0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/preceding::a[1]</value>
      <webElementGuid>69879920-1741-441d-99ce-4e0ea1f4fb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Identification de la déclaration']/parent::*</value>
      <webElementGuid>2bfa8f89-232c-47a1-bd85-54cf2759847a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a</value>
      <webElementGuid>fa941634-a0bb-4fe1-a77c-bd753848b491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tableDeclarationForm' and (text() = 'Identification de la déclaration
                                                ' or . = 'Identification de la déclaration
                                                ')]</value>
      <webElementGuid>7d2a65b5-0d2e-4e4c-9edd-13f6098dba98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
