<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SuccessLa demande dindeminisation avec _34d358</name>
   <tag></tag>
   <elementGuidId>e2ea3515-4822-4b54-b9ed-895461ffac80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.toast.toast-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b911f303-8ce6-482c-bfec-5c465de6e60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast toast-success</value>
      <webElementGuid>41ae8e1a-74f5-4880-811e-109afdee5bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>ed48b730-539c-45b2-a650-6cc260afefc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×SuccessLa demande d'indeminisation avec la référence suivante : &quot;Hg92/DC3_MAT/82/DM1&quot;</value>
      <webElementGuid>3a2442d2-33e6-4374-a1b7-ed3e467d60f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;toast toast-success&quot;]</value>
      <webElementGuid>6093953e-bbb3-4f2d-b7dc-a89f2d2a44aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>ed92d292-db1f-46c7-be9a-6b7e27811ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 All Rights Reserved.'])[1]/following::div[2]</value>
      <webElementGuid>3f5f60fe-5671-468f-a5e5-a46da298bff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/following::div[3]</value>
      <webElementGuid>e4e55412-9fbb-4ba3-9185-c543de3b6030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>5443206e-8392-4336-a2a7-d9fc7a0ce034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;×SuccessLa demande d&quot; , &quot;'&quot; , &quot;indeminisation avec la référence suivante : &quot;Hg92/DC3_MAT/82/DM1&quot;&quot;) or . = concat(&quot;×SuccessLa demande d&quot; , &quot;'&quot; , &quot;indeminisation avec la référence suivante : &quot;Hg92/DC3_MAT/82/DM1&quot;&quot;))]</value>
      <webElementGuid>649586bf-5697-480b-8079-6118e041820e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
