<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Demandeur.N_Type_Doc</name>
   <tag></tag>
   <elementGuidId>0d91dd35-28f1-497f-9be5-b1a24ba0e7a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Demandeur_N_Type_Doc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Demandeur_N_Type_Doc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fab3892-3a69-49a1-ae71-1b40bf3c463b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19e2c9d3-d607-4e4e-bef6-6313a17aa31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>92ee284c-cedb-4e48-be7b-7ca2c1d8ba56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>demandeurInfos</value>
      <webElementGuid>080874a9-7290-4cab-ac85-3533bd196091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b52c1b55-cd77-4aba-ae3b-146cd83a928a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N_Type_Doc' is invalid.</value>
      <webElementGuid>f0233245-2388-4aee-bc7c-3ed9bf22728a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Type_Doc,*.Type_Doc_Id</value>
      <webElementGuid>28d0d9af-32d1-4b05-af02-0fcaef7ef0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>1643a2af-6006-461b-95ce-232e897c4c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/FieldVerification/RegexCINE</value>
      <webElementGuid>700bf3c3-6168-41f3-a968-7e80a8c7569e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'identifiant du document</value>
      <webElementGuid>4f07e8bd-37c5-4eca-a041-158bbeecab16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Demandeur_N_Type_Doc</value>
      <webElementGuid>084bdbbc-2d44-4e56-ad4f-f2fee4182121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Demandeur.N_Type_Doc</value>
      <webElementGuid>440234a3-17a5-40ab-9512-5ee45c7b3e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Demandeur_N_Type_Doc&quot;)</value>
      <webElementGuid>7bf0dffb-6222-409e-a1f2-e7485e7f90ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Demandeur_N_Type_Doc']</value>
      <webElementGuid>77368aca-f749-4ae6-ad3c-1533dd30c234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>cec4b817-b159-4a16-946e-1b922c5f6176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>6724cd97-c38e-4cf1-85dc-f92e4603052c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Demandeur_N_Type_Doc' and @name = 'Demandeur.N_Type_Doc']</value>
      <webElementGuid>e5ee4e83-3c90-4cb2-badb-462892edeecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
