<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Demandeur.Gsm</name>
   <tag></tag>
   <elementGuidId>27d467ca-4918-4b06-9a66-238b99ceebaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Demandeur_Gsm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Demandeur_Gsm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0be7400-1130-45bb-a856-3e3399ee6ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>875fc7c4-94e9-458c-9d55-195d48eacc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>47510840-005d-4bb3-9b3e-3e4efdccf478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>demandeurInfos</value>
      <webElementGuid>ea059a86-3389-467b-afda-79ec4d728159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>8c065e20-14f0-4d59-b87a-f2dc1fddb884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b74e471-2cb1-41ca-8b9e-e81eb677e0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Numéro de téléphone non valide</value>
      <webElementGuid>9fe3972d-b7b0-4e75-8744-432a97c2ea30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(?:(?:\+|0)?|0)[1-9](?:(?:[\s]?\d{2}){4}|\d{2}(?:\d{3}){2})$</value>
      <webElementGuid>f4468f59-3d36-4ea9-9a8a-8e53d96451f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro GSM</value>
      <webElementGuid>45569e02-3be5-43f2-8bf1-9b544a2e64e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Demandeur_Gsm</value>
      <webElementGuid>3fa8a627-2da2-4243-8bf7-655ecfde3b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Demandeur.Gsm</value>
      <webElementGuid>64710113-f26b-47a5-84c8-5065a952ef6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f73810b5-6a50-4126-b63d-7bdbff786fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__ __ __ __ __</value>
      <webElementGuid>2f9ae120-3e67-4328-9195-8bb1b65accc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Demandeur_Gsm&quot;)</value>
      <webElementGuid>611cf7ca-7723-4fae-bb26-8486062f2619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Demandeur_Gsm']</value>
      <webElementGuid>74275a99-e9ec-4be9-be98-3ee8fd5c2f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[3]/div/input</value>
      <webElementGuid>c8610067-f148-4726-93f3-b78f65996d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/input</value>
      <webElementGuid>034fc593-3e5e-4c95-bced-603145d6de93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Demandeur_Gsm' and @name = 'Demandeur.Gsm' and @placeholder = '__ __ __ __ __']</value>
      <webElementGuid>d69b59f6-b18d-4ef0-bcc7-b0466babeb05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
