<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Demandeur.Nom</name>
   <tag></tag>
   <elementGuidId>cd05caf0-f36f-4596-9a34-0dad10f1f9e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Demandeur_Nom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Demandeur_Nom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>108ded23-d725-48e5-a18e-e12a6d889a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e00b904-6000-4047-861b-1291230407f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>98995805-b11d-43df-bfc1-df1286cd075a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>demandeurInfos</value>
      <webElementGuid>f0ba8667-8bf0-4b97-ad19-a1a4922c9e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db9db670-2ef3-4e52-b51f-545ac73db49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le nom</value>
      <webElementGuid>79138617-3059-4c1e-bb3d-f39a52c3670e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Demandeur_Nom</value>
      <webElementGuid>2df63a3c-cbe9-4f2c-99fa-71cb3a90b9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Demandeur.Nom</value>
      <webElementGuid>c9125200-274a-4b53-9967-1fe924ee2a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Demandeur_Nom&quot;)</value>
      <webElementGuid>d1b3da1f-54f1-44a6-9c3e-10df2036f6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Demandeur_Nom']</value>
      <webElementGuid>fd2a6176-2cfa-4653-8609-32577d66e4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div/div/input</value>
      <webElementGuid>7b306600-2972-486b-9481-3039a0469613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[2]/div/div/div/input</value>
      <webElementGuid>b54093ec-6c76-4591-91e3-d20dbf986765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Demandeur_Nom' and @name = 'Demandeur.Nom']</value>
      <webElementGuid>1cddc2cc-7e08-4806-b553-2de5a5f5587d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
