<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Parcourir</name>
   <tag></tag>
   <elementGuidId>8c5ba13f-d4ed-424f-8e16-aca0d904f5ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formSinistre']/div[5]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.browse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>061f5f6d-679f-4fa1-8f6d-a6ba2cd00fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>db27683d-13af-478e-b693-527f6b96c4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parcourir</value>
      <webElementGuid>07775c03-b2ad-4a8e-866e-e675a7e13dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/span[@class=&quot;browse&quot;]</value>
      <webElementGuid>e81b7825-3ce5-4beb-b6c8-9cabb55a15ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div/div/div/span</value>
      <webElementGuid>4f41073b-4ed7-47d5-aec5-7eb3150409da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[32]/following::span[1]</value>
      <webElementGuid>15098587-dfd0-43e2-adee-5086e8233b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[33]/preceding::span[2]</value>
      <webElementGuid>fca181a7-3024-46ff-abfd-600c61da609b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Parcourir']/parent::*</value>
      <webElementGuid>6264970b-763a-4dba-9b8d-8f496ceb0a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[5]/div/div/div/div/span</value>
      <webElementGuid>3d7ab7f3-92d6-416a-9044-801b8a214c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Parcourir' or . = 'Parcourir')]</value>
      <webElementGuid>917707f2-f863-4816-b90a-5c8e600c62e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
