<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Assure.Adresse</name>
   <tag></tag>
   <elementGuidId>4f75d098-da8c-43a2-a067-3be84c55e964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Assure_Adresse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Assure_Adresse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0774862f-b092-4c76-ae09-4764d73b42ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4f8dc1df-a619-4bb3-889b-1ae9353eb99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8776c19b-a111-4eb2-b134-4e6217b54978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'adresse</value>
      <webElementGuid>33fd0146-ee42-4ab3-b7c4-ae9fc3585bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assure_Adresse</value>
      <webElementGuid>a583cb61-da59-491a-8f26-0b6c8fa8a1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Assure.Adresse</value>
      <webElementGuid>d58cb8aa-4f04-46fb-8c6c-a237d03dc7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assure_Adresse&quot;)</value>
      <webElementGuid>c2f3e6ed-a89d-4ee9-afa6-d0351157e17e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Assure_Adresse']</value>
      <webElementGuid>0450efc9-f874-42df-a30e-ce2906c1e46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autreQualiteDemandeur']/div/div/div[5]/div/textarea</value>
      <webElementGuid>5346379e-d502-4932-b040-6cef68dbf601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/textarea</value>
      <webElementGuid>7f8a86ef-fbec-4add-bd37-68f8da9c9d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Assure_Adresse' and @name = 'Assure.Adresse']</value>
      <webElementGuid>8ebd79a1-39af-45aa-a67a-75593ce27923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
