<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rsidentiel_Type_Dommage_Id</name>
   <tag></tag>
   <elementGuidId>a817054d-9f97-4588-9b83-2bc2c9ba6437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Type_Dommage_Id'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dac537fd-6edb-4b89-b13e-d38d124b23e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>cefb1e2b-0338-4f9b-821d-f9cc1b23544e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>2a4fcd97-2cb7-4191-911a-92faabbb79b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c3bf4ef1-ad8e-4eda-b719-0911050fc4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>192268f4-eef8-4bc0-81fd-78419f0f7f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_Type_Dommage_Id&quot;)/label[@class=&quot;my-radio&quot;]/input[@id=&quot;Type_Dommage_Id&quot;]</value>
      <webElementGuid>d7810125-8369-457e-8050-72bfdb096426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Type_Dommage_Id'])[3]</value>
      <webElementGuid>b8b46f50-34f1-463c-837f-fece724f1575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_Type_Dommage_Id']/label[4]/input</value>
      <webElementGuid>cc6ada81-dc38-4605-8fdd-fbcbe056821a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>ece4db50-d68d-4cdc-9ca5-d75f7374c5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Type_Dommage_Id' and @name = 'Type_Dommage_Id' and @type = 'radio']</value>
      <webElementGuid>1ec66304-7cc9-41bb-9bd1-874ec70ea824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
