<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ajouter_assureur</name>
   <tag></tag>
   <elementGuidId>9482508b-071e-47ed-8e89-d760e72193d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='autreAssuranceBlock']/div/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.out</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4954f7d5-bf54-44a8-a4d6-ee84e4d9db06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0b9b448-5525-4ece-8dd3-3092f51451c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>428028c8-44ea-4095-bc08-c5abe5a35bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsSinistre</value>
      <webElementGuid>96a14fd7-2d84-4286-9a81-9f493c719cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidation</value>
      <webElementGuid>71cb3386-e0b4-4ab5-9b61-fd4d228a9276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#divAutreContrat</value>
      <webElementGuid>67a36fe8-680e-4642-a553-60b12ea24fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>after</value>
      <webElementGuid>1bec8eb9-b92b-4f65-9436-dc4a77f516fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/autre-contrat-assurance</value>
      <webElementGuid>da76913a-88d0-4503-8fc6-04d7be36aa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>HelloWorld</value>
      <webElementGuid>13ef5952-8fda-41bb-94ad-eb3ac54e5b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn out</value>
      <webElementGuid>e973100c-b655-414f-a1c7-4200c0572b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajouter
                                                </value>
      <webElementGuid>cde0e9f0-ef3d-43cb-bc4b-1b56ca4e6ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autreAssuranceBlock&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;AutConAss-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-lg-12 text-right&quot;]/a[@class=&quot;btn out&quot;]</value>
      <webElementGuid>2ef4ff83-0a2b-4ce4-a3c9-2d7be9829216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autreAssuranceBlock']/div/div/div[2]/div/a</value>
      <webElementGuid>4147f29d-22dc-44a8-bca6-2aac034f131c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ajouter')]</value>
      <webElementGuid>ac454779-0efd-4203-b37b-ef109f34cdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/following::a[1]</value>
      <webElementGuid>3189acb0-99f8-4411-b110-760534f1677c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descriptif des dommages matériels subis:'])[1]/preceding::a[1]</value>
      <webElementGuid>c263904c-fb2a-4b4d-b906-233c05799205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajouter']/parent::*</value>
      <webElementGuid>e86d10e6-6f28-4bdf-ab29-86b0c6c15937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/autre-contrat-assurance')]</value>
      <webElementGuid>96dd9de6-802a-4d88-b0c7-ec099f20cd63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>2cd1c50b-c774-4490-b000-2eccc6498766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/autre-contrat-assurance' and (text() = 'Ajouter
                                                ' or . = 'Ajouter
                                                ')]</value>
      <webElementGuid>1d67efed-722e-4ca4-9ee3-6581599ea8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
