<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Parcourir</name>
   <tag></tag>
   <elementGuidId>9170325e-22b1-4550-8344-5d79186408d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formSinistre']/div[5]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.browse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6d7596b-b26b-4f62-b6c1-45ea6f18820d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>dfa78f8e-0012-4413-9673-f531f81186f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parcourir</value>
      <webElementGuid>e5336679-2006-4ca6-81f9-e0779d0d0cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/span[@class=&quot;browse&quot;]</value>
      <webElementGuid>513e6e1d-322b-4584-9f84-f9813b1ba949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div/div/div/span</value>
      <webElementGuid>4121ac8f-a2a0-4e56-80a7-947e29735e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[27]/following::span[1]</value>
      <webElementGuid>a559cb7a-aaa3-47fe-a69c-cdf796663027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autres'])[1]/preceding::span[2]</value>
      <webElementGuid>5fc54d8f-81d8-4f23-9d79-388c36d1341a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parcourir'])[2]/preceding::span[2]</value>
      <webElementGuid>13b05e2e-0b7d-4e5f-a054-f61aa13a9618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Parcourir']/parent::*</value>
      <webElementGuid>7579672d-4972-45ea-a343-affae7a584a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span</value>
      <webElementGuid>e5fabcc7-000b-4268-880c-4c4fa58133bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Parcourir' or . = 'Parcourir')]</value>
      <webElementGuid>30286081-908b-42f6-a5ed-9999db210c40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
