<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Attachement.FichierIdentiteDemandeur</name>
   <tag></tag>
   <elementGuidId>3fcc63fc-73a5-4023-b70f-14b1655c1f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Attachement_FichierIdentiteDemandeur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierIdentiteDemandeur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c361d53e-c1bb-4da6-af39-d88be57841c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b206fcb5-270f-4ead-95e1-90c78aed40d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>50941072-a2b9-4bfd-88b3-527fecdfea6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>40852b9a-eed8-4478-88ae-2d8b47ca0e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierIdentiteDemandeur</value>
      <webElementGuid>e294b987-2c21-418a-8718-6b571affcb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierIdentiteDemandeur</value>
      <webElementGuid>3487d3a6-081f-47ef-ba36-e0ba8ab9ab99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierIdentiteDemandeur&quot;]</value>
      <webElementGuid>f8da27b9-eb28-4d84-b1b7-67d7f85530e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierIdentiteDemandeur'])[2]</value>
      <webElementGuid>f18a6dd9-fcaf-418e-ac7a-dbf79062a314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>3f8d33be-d085-4dd8-b8e2-03e45f38dcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>00e249ee-4621-4ea4-bc98-e9cdeaf1dc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierIdentiteDemandeur' and @name = 'Attachement.FichierIdentiteDemandeur']</value>
      <webElementGuid>adfd5ce7-a057-4d5a-825e-84d68ed9b6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
