<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Attachement.FichierContratAssuranceResidence</name>
   <tag></tag>
   <elementGuidId>16975299-694d-411c-8117-e9507941b7b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Attachement_FichierContratAssuranceResidence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierContratAssuranceResidence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79b89664-c035-4fd0-a612-c522b6203e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bcda81d-36fe-437c-be53-99a1a9a9f60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>522417ad-e26d-4579-8b3b-1a34993c7cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e02e15c4-d306-42fe-8966-4ed553c04080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierContratAssuranceResidence</value>
      <webElementGuid>41c1ea47-44eb-442f-819b-32d4095161ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierContratAssuranceResidence</value>
      <webElementGuid>1c4e0d7c-50b4-49af-b464-d77c27031297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierContratAssuranceResidence&quot;]</value>
      <webElementGuid>f8ef9476-5d3f-4469-8f3b-9ea8c98740c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierContratAssuranceResidence'])[2]</value>
      <webElementGuid>cb3c4be6-2f1c-4132-a198-b106f25d4ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>1086778a-e675-4a27-b835-51c0a22a6ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>aaa234de-5a2f-4b01-b03f-8ab78b9a41c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierContratAssuranceResidence' and @name = 'Attachement.FichierContratAssuranceResidence']</value>
      <webElementGuid>32e3d02b-e70a-4bb5-a810-4846b1f337f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
