<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DateSinistre</name>
   <tag></tag>
   <elementGuidId>a0f9d868-e747-4fba-b236-a3c2964d4645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DateSinistre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DateSinistre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ae9870e-d50f-4298-844e-b20dca261a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ec1224eb-e9fe-4125-8085-d91c66090c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c0b909a-efd4-4c17-9f52-4572d31b9b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>La date doit être inférieur ou égale à la date d'aujourd'hui</value>
      <webElementGuid>abefea1d-4398-497d-aa17-729c55f12613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.DateSinistre</value>
      <webElementGuid>7f57f2d6-a7db-4912-9454-7eaa6c5385bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>ea2d1b76-18db-471f-afd9-7bc4b2c321eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/Date-compare/compare-dates-sinistre-dateNow</value>
      <webElementGuid>a756fe74-7c68-4529-af49-ca4266dba44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez choisir la date du sinistre</value>
      <webElementGuid>10256327-7ae9-4d57-b064-b491d64e6690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DateSinistre</value>
      <webElementGuid>e9325fef-88ba-469c-8214-a57b60043726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DateSinistre</value>
      <webElementGuid>42032862-0ae2-4b05-b70b-e5e55e1ccbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DateSinistre&quot;)</value>
      <webElementGuid>5bec9ba1-8eba-47b3-bd02-4d51ee2825b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DateSinistre']</value>
      <webElementGuid>78217170-2e94-4729-bb0a-ca2335970207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existInfo']/div/div/input</value>
      <webElementGuid>b8d7e36d-2cc8-4363-b797-eb86bf168493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>07baed2b-82c8-4a75-b633-79dd2cbe2358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'DateSinistre' and @name = 'DateSinistre']</value>
      <webElementGuid>904cbc84-4c2d-4ca6-8998-241ac999566c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
