<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commune sinistre_checkbox</name>
   <tag></tag>
   <elementGuidId>86808291-310d-4456-9efb-d5de79fae4bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='checkbox'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd2b6084-d63d-40c9-8b7a-c5f7b7db2696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f208aff3-efa3-428d-ba9b-fce2bcdb8b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box read-commune</value>
      <webElementGuid>e4d54f1b-e527-45b5-9589-6a40321be984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>438b0b83-d5c6-4db4-a6b6-281bd683057b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>366b0711-40fc-438d-9660-ee9741a6edf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existInfo&quot;)/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-sm-6&quot;]/label[@class=&quot;label-check-box&quot;]/input[@class=&quot;check-box read-commune&quot;]</value>
      <webElementGuid>07b84e6c-e018-4a5a-86ed-fe5b10062114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='checkbox'])[2]</value>
      <webElementGuid>a160de2e-95aa-459f-96bb-94d544f1e3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existInfo']/div[2]/div/label/input</value>
      <webElementGuid>eb0788bf-649d-4d33-9e04-8035132ad409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>2921f800-7ac4-42c1-a062-02253e8d8792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkbox']</value>
      <webElementGuid>3f15e89a-1d0c-48f9-a632-b1583ef840fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
