<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rfrence EVCAT (provisoire dfinitive)_MotCle</name>
   <tag></tag>
   <elementGuidId>513661be-0e15-4ea6-8da0-dabf8bcb595a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MotCle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MotCle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acc84a33-708f-461d-9746-19be81822eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80a856b2-c600-45df-a286-baf78ba849fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MotCle</value>
      <webElementGuid>742ca8a8-4fed-4a81-8b78-50ed3e87d858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MotCle</value>
      <webElementGuid>807b14fe-d9d8-42ab-b259-70ff04f86e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MotCle&quot;)</value>
      <webElementGuid>7ea106c6-f7bc-4593-9491-403c321c5ae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MotCle']</value>
      <webElementGuid>c9730291-8c69-427e-807f-062c474afa43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>a7387980-c7ac-46eb-a3b1-c5a2c831f1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>42742eac-d026-40d3-bd3f-728a48bf9c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'MotCle' and @name = 'MotCle']</value>
      <webElementGuid>540f0f8c-5130-440f-92cf-24f64b758286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
