<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rfrence EVCAT_a_capturer</name>
   <tag></tag>
   <elementGuidId>23662c0c-7e63-48ae-96cd-37093608f6ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReferenceEVCATDiv > #ReferenceEVCAT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ReferenceEVCAT'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c28716d8-1812-4ef2-a986-0d3b16a8f89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23f718bf-0c74-48c2-863b-4ae22b4342f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReferenceEVCAT</value>
      <webElementGuid>1f856ef9-a994-4428-8d34-df731bf0004b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReferenceEVCAT</value>
      <webElementGuid>e0abfdfe-7c2d-4cba-bd3d-8d15afac1e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReferenceEVCAT</value>
      <webElementGuid>a5aa37d0-2133-4244-acb9-a35da4c0ae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReferenceEVCATDiv&quot;)/input[@id=&quot;ReferenceEVCAT&quot;]</value>
      <webElementGuid>15b60d52-2d15-4ea1-84a8-7c2dfc61c915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ReferenceEVCAT'])[2]</value>
      <webElementGuid>70b908c6-e019-42a5-96a7-995edfe90c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReferenceEVCATDiv']/input</value>
      <webElementGuid>b12948f1-1f8b-4ee0-98c2-edaa173b9de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>2beb8bd7-8238-4b52-a23e-58fa88ae1352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ReferenceEVCAT' and @name = 'ReferenceEVCAT']</value>
      <webElementGuid>d7064223-1468-422b-8eda-a01880d1fea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
