<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>REG_li_Bni Mellal-Khnifra</name>
   <tag></tag>
   <elementGuidId>0147acec-8b75-44c2-8d9d-7d375c18aaac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.dropdown-option.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Béni Mellal-Khénifra'])[4]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>461c93ed-8fcf-4448-9571-0bf2572a3ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option selected</value>
      <webElementGuid>c5945492-8239-4efd-9e76-96bf36e12287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7596ab86-ee85-41c9-8740-506ed45f7f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4c91c40d-d8e8-4ec5-8551-38f7ca8306d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Béni Mellal-Khénifra</value>
      <webElementGuid>f9453f7e-f808-4c10-a18c-0cb0788b2ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_Definitives50c5b1a1-4865-4027-a6f0-6c86ae466c0d&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option selected&quot;]</value>
      <webElementGuid>af6be150-7e26-4058-bc6b-68dd03a1ea99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_Definitives50c5b1a1-4865-4027-a6f0-6c86ae466c0d']/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>8db69f05-863f-4a2e-95c2-bb7af6f766e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Béni Mellal-Khénifra'])[4]/following::li[1]</value>
      <webElementGuid>205141bc-4cd8-4f99-a176-571a6e2760af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Région'])[2]/following::li[1]</value>
      <webElementGuid>f7545bdf-b303-4e3f-b9bf-f38ad12f0128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drâa-Tafilalet'])[4]/preceding::li[1]</value>
      <webElementGuid>db8739dd-34d7-4ce8-ad0d-90e69dae4cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eddakhla-Oued Eddahab'])[4]/preceding::li[2]</value>
      <webElementGuid>a0cb0d46-f3ae-4839-bee1-94a641cbc8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>4244a9db-fb87-4924-8ea1-74e1abd53880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Béni Mellal-Khénifra' or . = 'Béni Mellal-Khénifra')]</value>
      <webElementGuid>d4a1b126-abcf-46da-9d8e-550bbe6af149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
