<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Declarant.N_Type_Doc</name>
   <tag></tag>
   <elementGuidId>1d87fbc6-cdbd-49de-aa4e-05607e5184f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_N_Type_Doc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Declarant_N_Type_Doc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6e48aa4-919b-4b01-aeec-9bdffd3e3070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6606c9d3-ee64-443a-95a9-516e3ac65092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a631d883-fdf6-4883-adc8-fe8fd2960eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N_Type_Doc' is invalid.</value>
      <webElementGuid>1eae8d23-ec87-4c73-9680-b5c60a2d98e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Type_Doc,*.Type_Doc_Id,*.Ref_Event_Id,*.Type_DocSinistre_Id,*.CompanyId,*.NatureDommageId,*.Type_Dommage_Id</value>
      <webElementGuid>9ad4af0d-e053-45cb-b5ba-9bb075eca780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>20221986-de03-46fb-8d9b-de34a861a0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/exist-dossier/get-exist-dossier</value>
      <webElementGuid>c6d64b3b-db5c-45a0-8c19-d0a7bdd3fc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'identifiant du document</value>
      <webElementGuid>04b7b907-55c5-440f-81dc-945980cd3a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_N_Type_Doc</value>
      <webElementGuid>265a7ae8-85a5-424a-8ec1-02b9ba6fdaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.N_Type_Doc</value>
      <webElementGuid>62f430bf-dc73-4f7d-bc52-0d75e553d122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_N_Type_Doc&quot;)</value>
      <webElementGuid>eb0b1fa1-dca6-4199-9e5e-9d596a34ce56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_N_Type_Doc']</value>
      <webElementGuid>0e53e21b-cd9e-4e7f-bafd-269ffba3256c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>77eb2514-113c-494e-8156-416d6086aa7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>e7ba7ad5-4912-466b-b693-0a263f40d8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_N_Type_Doc' and @name = 'Declarant.N_Type_Doc']</value>
      <webElementGuid>5d8bdfcc-85c4-4892-93c5-74853e4b22bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
