<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scrollTo</name>
   <tag></tag>
   <elementGuidId>d65ab991-6428-47e7-b4c1-de2e443a1dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_Gsm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Declarant_Gsm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a8d8947-0d13-4e77-b7b9-fbea66bcd0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20e60daa-8ea1-44e4-95af-089e43c7c91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>33c1cf10-b73a-4b7e-82b9-a8df93b58c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc4a247d-c473-4342-8b74-8ec388de3d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Numéro de téléphone non valide</value>
      <webElementGuid>a63e3306-67e5-4c69-8ee6-bff2bae81c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(?:(?:\+|0)?|0)[1-9](?:(?:[\s]?\d{2}){4}|\d{2}(?:\d{3}){2})$</value>
      <webElementGuid>c4c730c3-dd76-4365-ac35-2c766ee45cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_Gsm</value>
      <webElementGuid>ab029232-e0a7-48e6-8210-f6dafa837963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.Gsm</value>
      <webElementGuid>cb7fb49e-0319-4902-aecf-343c8e341973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ba6ffa8-afea-41bf-9e2b-54b2031027ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__ __ __ __ __</value>
      <webElementGuid>092daaca-4eb5-4572-a949-9de5db69f56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_Gsm&quot;)</value>
      <webElementGuid>c04e7b87-8941-4a7f-b25f-66bac1d8491c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_Gsm']</value>
      <webElementGuid>0bea0463-23f4-4907-a944-11c01b2eddd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[2]/div/input</value>
      <webElementGuid>12d739b7-2287-47e4-b645-cd43dda22839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[2]/div/input</value>
      <webElementGuid>91fb68cc-4239-4dc4-8c7b-a66616d81f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_Gsm' and @name = 'Declarant.Gsm' and @placeholder = '__ __ __ __ __']</value>
      <webElementGuid>b1150429-5ba5-407d-a299-af3fd3cd83d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
