<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dure_Evenement.ActeAdministratif.Duree</name>
   <tag></tag>
   <elementGuidId>26fd4f6f-2f38-41e1-b4ab-dd6090c97081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Evenement_ActeAdministratif_Duree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Evenement_ActeAdministratif_Duree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b58d718-6f6d-4576-8ca4-81b4a59b58ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>76740b51-4454-4125-a2a1-83d2c4c60d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ebbeab0-a3f7-47ed-9b2b-3b759533de1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Duree must be a number.</value>
      <webElementGuid>867cdeae-4357-4ad4-b28a-0f42863a3bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Valeur non valide</value>
      <webElementGuid>a926286a-e0d9-4bcd-b85d-f81421ee94a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>8f9a67cc-70b3-44b9-9095-42105c2f02f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb3489e8-e597-449d-a6d2-7e9705e4ae13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer la durée de l'évènement </value>
      <webElementGuid>c84ee2b5-fe36-4b99-9e06-6b1c0143f2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Evenement_ActeAdministratif_Duree</value>
      <webElementGuid>21e9f3bb-369d-44db-808e-63148cfc5d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Evenement.ActeAdministratif.Duree</value>
      <webElementGuid>05db9969-51b3-4641-b394-dd95275d768f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Evenement_ActeAdministratif_Duree&quot;)</value>
      <webElementGuid>23dd6f35-a506-42cd-9e0a-963039ddabf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Evenement_ActeAdministratif_Duree']</value>
      <webElementGuid>14ea05a8-7dcc-40f8-b15a-82531be10011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div[2]/div/input</value>
      <webElementGuid>c9049bb0-47d9-4ba0-9b62-c143c02692f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/input</value>
      <webElementGuid>e63673ef-223c-4190-b690-6c3306fe9c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Evenement_ActeAdministratif_Duree' and @name = 'Evenement.ActeAdministratif.Duree']</value>
      <webElementGuid>392dbe38-b87b-40b1-bd4e-6e8641959e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
