<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_r1 (en )_Evenement.ActeAdministratif.r1</name>
   <tag></tag>
   <elementGuidId>adf01adc-c0dc-4d1b-b0f5-a2aedafe54ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Evenement_ActeAdministratif_r1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Evenement_ActeAdministratif_r1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f15df493-c811-45ee-9961-1f01865b56bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e20bea20-633a-491f-8f71-12187327a2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7da7a828-87fd-4f00-82b0-bfab8362ab65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field r1 must be a number.</value>
      <webElementGuid>da12a866-7de9-4524-b14a-f7ea64b9296a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Evenement_ActeAdministratif_r1</value>
      <webElementGuid>30596f89-0446-405a-88c9-298c499870d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Evenement.ActeAdministratif.r1</value>
      <webElementGuid>ad6b06ed-350b-4952-85f6-97ece21e4c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Evenement_ActeAdministratif_r1&quot;)</value>
      <webElementGuid>614f333b-13f9-4d0b-b03c-d5c983ede23e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Evenement_ActeAdministratif_r1']</value>
      <webElementGuid>a440c0b5-18f7-47ca-8da0-582e2341bdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div[5]/div/input</value>
      <webElementGuid>8f196ae2-da92-420b-9bcc-71e4968e3e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>b29228bd-355b-42e7-aa02-11b26c73b0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Evenement_ActeAdministratif_r1' and @name = 'Evenement.ActeAdministratif.r1']</value>
      <webElementGuid>1fa51ad5-2adb-4609-9061-db4939c439fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
