<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rfrence EVCAT Provisoire_Evenement.Re_f49fea</name>
   <tag></tag>
   <elementGuidId>8e9b6206-cabd-4ce9-abe3-c164a4cb9859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Evenement_ReferenceEVCATProvisoire</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Evenement_ReferenceEVCATProvisoire']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a5d0f89-8490-4888-ab6d-2b73ef982b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35013fda-532d-469c-b7b5-d44ea0abe8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReferenceEVCATProvisoire</value>
      <webElementGuid>8bc6d7b9-7e3d-465b-8c45-9a67dab428f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Evenement_ReferenceEVCATProvisoire</value>
      <webElementGuid>a51238b4-37db-4877-ae8b-d39e8103a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Evenement.ReferenceEVCATProvisoire</value>
      <webElementGuid>634c41a9-38b9-4c66-97cc-a2010316ba81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P.2023.05.12.IND</value>
      <webElementGuid>3752048c-9527-4b0a-a37f-2488974359ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Evenement_ReferenceEVCATProvisoire&quot;)</value>
      <webElementGuid>1447af7c-8231-4ead-b82e-9cb97204b7ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Evenement_ReferenceEVCATProvisoire']</value>
      <webElementGuid>cf5e866e-137b-4963-907b-0b43ed3a35d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReferenceEVCATProvisoireDiv']/input</value>
      <webElementGuid>3601d662-a288-4a8f-b2d9-cfe6be11472f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>49233954-e110-49e3-9f28-6115b5078a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Evenement_ReferenceEVCATProvisoire' and @name = 'Evenement.ReferenceEVCATProvisoire']</value>
      <webElementGuid>4fa266db-e86c-44bc-abda-9a015c92c3d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
