<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_BENI MELLAL (1)</name>
   <tag></tag>
   <elementGuidId>cfa8010b-0619-4776-9f17-748d132c4c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Evenement.ZoneTouchees_Definitives[461e5801-ad86-44dd-8123-35b1cf5d2683]villeList']/div/div/div[2]/div[2]/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c9256d90-fbf7-4ebc-8071-04b3231c5e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>023e3950-61d8-4025-a050-b8420c2e648e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>beb17b15-1db2-47ec-b1c7-bd6d133a01fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>19141e81-603f-4080-bcef-c29e40a470cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BENI MELLAL</value>
      <webElementGuid>013c514c-b72e-4e2c-9136-eaa8688934d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Evenement.ZoneTouchees_Definitives[461e5801-ad86-44dd-8123-35b1cf5d2683]villeList&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>714de215-31bd-4281-bc12-501f6a83304e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Evenement.ZoneTouchees_Definitives[461e5801-ad86-44dd-8123-35b1cf5d2683]villeList']/div/div/div[2]/div[2]/ul/li[2]</value>
      <webElementGuid>6d27156e-e49e-4aad-b810-ab9c05bb3e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENI'])[1]/following::li[1]</value>
      <webElementGuid>798ff22f-b656-4fce-b710-96889401746f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autre Adresse'])[2]/preceding::li[1]</value>
      <webElementGuid>73429a2a-6fde-47f4-a34d-c17250a0db0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MELLAL']/parent::*</value>
      <webElementGuid>b1dbf582-63c1-47d3-a7bc-ff4b5e7bc084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div[3]/div/div/div[2]/div[2]/ul/li[2]</value>
      <webElementGuid>6572d285-9f9c-42e2-a80c-6e22a1396677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'BENI MELLAL' or . = 'BENI MELLAL')]</value>
      <webElementGuid>85bb1538-9c5b-4039-bef6-032f302653b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
