<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remorque_Type_Dommage_Id</name>
   <tag></tag>
   <elementGuidId>82bd7c6d-b875-4b49-b579-8419ceb3aeeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Type_Dommage_Id'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44c35d6b-ea26-4781-a3c9-abf99a46a1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>c572ddcf-9d58-42b5-b7eb-cc9298ada816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fac4e93-c8cb-4ce8-a6c4-99189d32275b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>7c7eac9c-7942-4e0d-ab89-8e1180523828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>d7365c83-4c20-45b9-a682-6f3bdfcd5f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>edd8c804-5843-4673-b5ab-ef39a4a6610b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecb8217f-db8b-4fd8-bdc9-70c5078d4eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/get-info-type-dommage?q=9oc1ZR4JEzXNdh3GJ7JsnhxCbxizGzkMYz4XoRIf5P0=</value>
      <webElementGuid>84baff7c-53b0-4921-9be0-3db7c09d91ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>c1956c0d-f6be-4a51-8f15-7fb5715afad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsSinistre</value>
      <webElementGuid>8b61e1ad-c38d-496b-a50e-2b43f9e4b840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidationSinistre</value>
      <webElementGuid>379864c1-1621-4446-9928-a4c9ff1b3e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#dommageInfos</value>
      <webElementGuid>843bf6f3-ab38-4844-ac0e-c15c07300f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>53d90833-4d76-41df-856a-02c1ae99dad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nested-partial</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aeff496f-5402-4af3-9e79-a9c4341bf973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>bb896309-74f6-49c5-beae-0a13a65a7a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9e594a18-982c-4561-8273-b4fec9fe8135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82099923-b674-41fe-9b76-5b80c7ea828a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez selectionner un type de dommage</value>
      <webElementGuid>85f72591-6b3a-44d7-a616-a4545b8a6b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error ajaxValue</value>
      <webElementGuid>fa1ae44d-d228-427e-9b5b-ec791a9c4d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Type_Dommage_Id-error</value>
      <webElementGuid>58b7bfe4-6942-49c6-90ba-222c0fd23eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;garantie&quot;)/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-lg-12&quot;]/div[1]/label[@class=&quot;my-radio&quot;]/input[@id=&quot;Type_Dommage_Id&quot;]</value>
      <webElementGuid>a3866ebe-91bc-4794-86c2-ccb3f734e43c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Type_Dommage_Id'])[2]</value>
      <webElementGuid>a4afc26c-f187-4f5a-88d3-aa9f60a1d6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='garantie']/div/div/div/label[2]/input</value>
      <webElementGuid>f6f24f5d-ef2f-4819-b0f7-22d54c8da3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>a4a587ec-397f-4947-ac2b-eba0e6973b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Type_Dommage_Id' and @name = 'Type_Dommage_Id' and @type = 'radio']</value>
      <webElementGuid>dd63d28f-8968-4bc8-a8d7-3da5791e5489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
