<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rfrence EVCAT Provisoire_ReferenceEVCATProvisoire</name>
   <tag></tag>
   <elementGuidId>14357ed1-f170-44e7-9739-f0f628b8afe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReferenceEVCATProvisoireDiv > #ReferenceEVCATProvisoire</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ReferenceEVCATProvisoire'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb4d10e2-8f94-40bb-9fa6-0e169617e0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa15d0d7-070c-4226-8ba1-e152bcfaa126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReferenceEVCATProvisoire</value>
      <webElementGuid>f82328b5-1d6e-41aa-9a1c-ac5ee524d7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReferenceEVCATProvisoire</value>
      <webElementGuid>07577e9c-14bd-4f30-b437-4cc93eb67861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReferenceEVCATProvisoire</value>
      <webElementGuid>0202e939-7c77-4a14-b309-8978bc79df99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReferenceEVCATProvisoireDiv&quot;)/input[@id=&quot;ReferenceEVCATProvisoire&quot;]</value>
      <webElementGuid>ded3b0a7-c10b-4fe8-b5a6-be7c93c869c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ReferenceEVCATProvisoire'])[2]</value>
      <webElementGuid>3c497644-89ef-41a9-857a-a49964a3c776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReferenceEVCATProvisoireDiv']/input</value>
      <webElementGuid>f9527d88-1631-460f-9727-c73be19a0d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>27ed50c3-e7d2-4205-92d2-3c27e9f6acc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ReferenceEVCATProvisoire' and @name = 'ReferenceEVCATProvisoire']</value>
      <webElementGuid>9c2ecb2c-f4b4-4979-918c-da45ab0e36f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
