<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_date_suv_ev</name>
   <tag></tag>
   <elementGuidId>14b5415b-8584-4dd4-8cdd-aa01adfe8c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DateEvenement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DateEvenement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c765be31-e241-4d5e-a4f7-7233262c831c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>fd42d03f-cac1-4e95-892e-65400870b339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Evenement_DateEvenement</value>
      <webElementGuid>bafae5aa-f7a6-4d21-89e3-620f75b0f5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51e681de-df9d-4348-8ba7-ef0ad74514e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer la date de l'évènement </value>
      <webElementGuid>e85914c2-d114-47c9-a2ff-daaddce39b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DateEvenement</value>
      <webElementGuid>55537586-ba58-45d4-8191-be2878b42835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DateEvenement</value>
      <webElementGuid>ea203905-4882-4fa1-adf0-a0d8a9f37311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DateEvenement&quot;)</value>
      <webElementGuid>e8261fd3-6535-4ac4-bc94-0bdd4e94ef05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DateEvenement']</value>
      <webElementGuid>3d65e017-3a2a-4e2f-af0c-68d6f0860bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DateEvenementDiv']/input</value>
      <webElementGuid>7cf81bc2-6f4e-4d17-b401-68a3d5650995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1a869a75-6cc0-42a4-86e5-e22724e9b3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'DateEvenement' and @name = 'DateEvenement']</value>
      <webElementGuid>8a02a306-c037-45f1-afcf-5f013b2539b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
