<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>c271bc86-2bf0-4672-a1b8-8a0def75ff47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagedContent']/div/div[2]/nav/div/div[2]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6db0cb7c-76de-4a86-bbeb-3c7ccb6a524e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/Indemnisations/Missions?page=2&amp;pageSize=100&amp;searchString=&amp;isClosed=False</value>
      <webElementGuid>bf5575e6-7a26-4a0d-8e3d-9096f165a107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link table-filter</value>
      <webElementGuid>5056ba39-29b5-47f5-bb0d-8ac752164052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1cd6206a-c83d-4279-bd38-62554fdc9ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>page 2</value>
      <webElementGuid>9c8dfd4a-d575-4df0-af8d-d1d779c83962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2
                                                </value>
      <webElementGuid>06377389-7805-43c5-82f0-f01fd31e8007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-content&quot;]/section[@class=&quot;contenu&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@id=&quot;pagedContent&quot;]/div[@id=&quot;pagedContent&quot;]/div[@class=&quot;work-space&quot;]/div[@class=&quot;withe-space&quot;]/nav[@class=&quot;pagination-tag-helper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/ul[@class=&quot;pagination pull-right&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link table-filter&quot;]</value>
      <webElementGuid>cb32996a-55d0-482d-9861-13072fa86138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/nav/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>b6e23bf7-93fb-4a7b-b9e9-ec8409328036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>11186d38-475b-4f3d-8d28-131babe2a01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/following::a[2]</value>
      <webElementGuid>d5926183-1c8e-425c-ba7d-663e324c4148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/preceding::a[1]</value>
      <webElementGuid>d5d4233d-d45f-479b-a94b-b01fade4ed7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/preceding::a[2]</value>
      <webElementGuid>6051b868-a0fb-4a5b-82d8-697e83a22506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>3018e8f1-0fab-4b73-8a97-8b5eeb5333c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>ddb2596d-cad8-4571-866c-37f8f3c5b1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '2
                                                ' or . = '2
                                                ')]</value>
      <webElementGuid>38e48f14-9a5e-44c3-95b0-be284384f5c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
