<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_10                                  _63d86f</name>
   <tag></tag>
   <elementGuidId>0c47650e-186c-43f9-b247-c155c02da86e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pageSize']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pageSize</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>43c931b9-4e81-47f0-ad05-25dc48296ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pageSize</value>
      <webElementGuid>dfa69070-9c03-4bb0-b280-48d415865455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageSize</value>
      <webElementGuid>5fa26ae7-400f-4720-9bb0-200655a52eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>submitPage('personForm','fromPageList')</value>
      <webElementGuid>968b541d-51ab-4299-b055-9c3894623633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                10
                                                20
                                                30
                                                50
                                                100
                                            </value>
      <webElementGuid>8b74b782-332d-4bda-b015-8e8295e9c471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageSize&quot;)</value>
      <webElementGuid>c674bbcc-df67-4d86-8818-bde4f321b196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pageSize']</value>
      <webElementGuid>f584ecc4-74f4-48bb-b275-8aeba193251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='personForm']/div[2]/div[2]/div/select</value>
      <webElementGuid>e6cf1101-3934-431a-bbd9-c3a96048fd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lignes par page :'])[1]/following::select[1]</value>
      <webElementGuid>1265a5ff-8a18-46fe-9ed0-a9b02f5abfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tableau de consultation :'])[1]/following::select[1]</value>
      <webElementGuid>b19ebce7-e51b-4324-9f91-4f6cb72b324b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reférence EVCAT'])[1]/preceding::select[1]</value>
      <webElementGuid>cb2d26e5-be7f-43fd-b8d1-54e0c71e9a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reférence du dossier sinistre'])[1]/preceding::select[1]</value>
      <webElementGuid>9904c7e7-7412-4e86-859d-8de5a3d64d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/select</value>
      <webElementGuid>8aec105c-cc94-44bc-8bd2-4d886b398242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pageSize' and @id = 'pageSize' and (text() = '
                                                10
                                                20
                                                30
                                                50
                                                100
                                            ' or . = '
                                                10
                                                20
                                                30
                                                50
                                                100
                                            ')]</value>
      <webElementGuid>8075ad51-c5ac-4bd0-9237-3b8e2d4a63df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
