<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Slectionner</name>
   <tag></tag>
   <elementGuidId>4dbac13d-8d16-4932-83e9-6a2e306b400b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagedContent']/div/div[2]/div/div/form/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e726954b-4d9b-4ddc-af2c-60b2c4d4d95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-label</value>
      <webElementGuid>f2634c41-4868-478a-8293-b5347ddd9c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sélectionner</value>
      <webElementGuid>6b8bd1ee-42b3-4f9c-8386-b82813bb5740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagedContent&quot;)/div[@class=&quot;work-space&quot;]/div[@class=&quot;withe-space&quot;]/div[@class=&quot;MoteurRech&quot;]/div[@class=&quot;formulaire&quot;]/form[1]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[1]/div[@class=&quot;tail-select no-classes&quot;]/div[@class=&quot;select-label&quot;]</value>
      <webElementGuid>38cf27dd-37fe-4ff6-8ff8-f62e63fe5a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/div/form/div/div/div/div/div</value>
      <webElementGuid>d72f4a88-7071-4dfa-aeff-9aaaae9823f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type de péril'])[1]/following::div[3]</value>
      <webElementGuid>ce525fc6-1a2e-4f31-bb0c-295bb7c90e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retour'])[1]/following::div[7]</value>
      <webElementGuid>0db7f328-4a47-43c5-88b8-6cbf808a665a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner'])[3]/preceding::div[2]</value>
      <webElementGuid>c734e0ef-b36a-4fe3-a009-c204ae07bd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div</value>
      <webElementGuid>6b0c6d85-8436-410d-8b91-16dca1b9964e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sélectionner' or . = 'Sélectionner')]</value>
      <webElementGuid>6b5e9cbb-b70e-4137-babd-67a4e4af566e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
