<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Inondation_fas fa-edit</name>
   <tag></tag>
   <elementGuidId>a7c72c6a-5713-4e0f-819d-62b3c8e8ff79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(9) > td:nth-of-type(5) > a[title=&quot;Modifier événement&quot;] > i.fas.fa-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tableEvenements']/table/tbody/tr[9]/td[5]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>419685d7-4342-4a20-a192-0c4ae9c9d82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-edit</value>
      <webElementGuid>15fb1028-09a7-48f7-ba83-fced49ca97ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableEvenements&quot;)/table[@class=&quot;omn-table table table-condensed table-body-center actions&quot;]/tbody[1]/tr[9]/td[5]/a[1]/i[@class=&quot;fas fa-edit&quot;]</value>
      <webElementGuid>fb1ffb1b-42b5-46b7-917a-d4d34fe640a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tableEvenements']/table/tbody/tr[9]/td[5]/a/i</value>
      <webElementGuid>312d3e9c-91da-4643-82b2-d3a36166c176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[5]/a/i</value>
      <webElementGuid>8cd77a29-70d2-4c29-b907-929662650ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
