<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Connexion</name>
   <tag></tag>
   <elementGuidId>abdf132c-3190-465a-91b8-6499abca8817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.lf-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26700e2e-6f18-4dfb-aa76-52ec48f6d3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-button</value>
      <webElementGuid>12e74c60-2ce2-4b07-b31c-a3dbbbe7f1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>b03664d1-f7f2-4ea8-9f84-b0a1d43c56eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account&quot;)/div[@class=&quot;back&quot;]/div[@class=&quot;authentification&quot;]/div[@class=&quot;container ogul&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;log-in&quot;]/button[@class=&quot;lf-button&quot;]</value>
      <webElementGuid>d29667a6-83e5-4748-9961-c032b3e5a59b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>70596254-4b8e-438c-9103-97d71c3ff9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connexion'])[1]/following::button[1]</value>
      <webElementGuid>a3e2c3da-00ef-43e1-a715-7447b11b7649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe oublié?'])[1]/preceding::button[1]</value>
      <webElementGuid>35c5267c-5845-4662-8b6d-87e01e0719aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0f48d5d8-6592-4973-b510-ff8b04fcc3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Connexion' or . = 'Connexion')]</value>
      <webElementGuid>58404f73-b9cf-4281-9509-b716f2022baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
