<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Retour</name>
   <tag></tag>
   <elementGuidId>972ad632-13c4-4bfb-857f-577fcd79899b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.back-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagedContent']/div/div[2]/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cc7a4ef-07e7-48c7-8b3f-9167d68ab963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-page</value>
      <webElementGuid>867cf169-5447-4e6d-a68b-20be03d82dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formaction</name>
      <type>Main</type>
      <value>/Sinistre/Suivi</value>
      <webElementGuid>e33e27b4-3530-4c1d-8480-ce2dc7fa7fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Retour</value>
      <webElementGuid>14e4de44-1b33-454f-a678-63e96977ccc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagedContent&quot;)/div[@class=&quot;work-space&quot;]/div[@class=&quot;withe-space&quot;]/form[1]/button[@class=&quot;back-page&quot;]</value>
      <webElementGuid>79bc4fcf-13be-4a1e-a115-fb55f6937c80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/form/button</value>
      <webElementGuid>6da2232f-ab66-4a6f-a31e-0dd637679aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultation / Modification / Validation des dossiers sinistres'])[1]/following::button[2]</value>
      <webElementGuid>5151737f-ac6d-499d-bad5-79392f86f512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des dossiers sinistres'])[2]/following::button[2]</value>
      <webElementGuid>baea0ac4-e779-47a5-8fd3-a97999a92900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Les données de la garantie sont récupérées depuis la BD EVCAT'])[1]/preceding::button[1]</value>
      <webElementGuid>f3d62615-6026-45e2-9541-662196bb27ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infos dossier :'])[1]/preceding::button[1]</value>
      <webElementGuid>269c4c20-ae73-4d7f-87ae-9dcbd3f0eb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>af624731-269f-4d69-8666-6cbbe58f8ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '     Retour' or . = '     Retour')]</value>
      <webElementGuid>392eb2a3-6af7-4cb4-b42c-53b9f4e38397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
