<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_-_fas fa-eye</name>
   <tag></tag>
   <elementGuidId>3cd5e9f0-fcfa-496f-ab9f-ba89b540aedc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='personForm']/div[2]/div[4]/table/tbody/tr/td[12]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>327cc1ac-c2e7-4615-b113-7fa5e6223cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye</value>
      <webElementGuid>a1506951-dde9-4cb9-b743-f8ae7af6785c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8251261e-c58e-4fba-ace3-f72588cf8419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personForm&quot;)/div[@class=&quot;row personTable&quot;]/div[@class=&quot;col-lg-12 responsive-table-line custom-table-css&quot;]/table[@class=&quot;omn-table table table-condensed table-body-center&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-left&quot;]/a[1]/i[@class=&quot;fas fa-eye&quot;]</value>
      <webElementGuid>5e66d8cc-c59b-4eec-a6eb-6295235e0073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='personForm']/div[2]/div[4]/table/tbody/tr/td[12]/a/i</value>
      <webElementGuid>cb30bbf0-b601-4eac-9902-5baa8ba612aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/a/i</value>
      <webElementGuid>fe478b92-c4e6-4c68-8726-eef8bfd3b749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
