<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rglement_checkmark</name>
   <tag></tag>
   <elementGuidId>ab97c37c-8a51-44d0-8b50-4b9120f2cab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='etat']/div/div[3]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6ddaf88-3e19-4e31-a782-8581b461189f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>10377c7f-0f44-4e19-aab4-daaa160e1089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;etat&quot;)/div[@class=&quot;row sous-blc-rad&quot;]/div[@class=&quot;col-lg-6&quot;]/label[@class=&quot;my-radio&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>75eaa46a-3f82-425f-a5b4-9c06aed47e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='etat']/div/div[3]/label/span</value>
      <webElementGuid>acc4fa74-92ce-4785-9606-70ac21edd98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span</value>
      <webElementGuid>007042c8-9258-4f0d-81d3-6b6a31370eac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
