<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rsidentiel_Type_Dommage_Id</name>
   <tag></tag>
   <elementGuidId>276e8b62-cb5a-4735-9f0c-27b5e665755a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Type_Dommage_Id'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59fcd0dc-1c8a-4f02-b32d-845e874ac0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>6e6b7401-ed6c-4e0c-933a-2e9676d9044b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8aff9ac-392a-480c-909f-b368ee0b6693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>81c10557-94a2-4096-80bc-af61d5752ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>d3e463e7-a09d-4867-9fdd-00e3ed56b23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>215f47df-f555-44ba-838e-7e7742f0ab06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f4a24d88-1f64-4bab-a7a0-b580f1f500ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/get-info-type-dommage?q=9oc1ZR4JEzXNdh3GJ7JsnhxCbxizGzkMYz4XoRIf5P0=</value>
      <webElementGuid>adc354f8-bf21-4178-b460-a90a15696e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>85f8d108-6206-48ad-b5b3-7e3703bdbed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsSinistre</value>
      <webElementGuid>903059f2-de1f-445a-9af2-e3149c2ba79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidationSinistre</value>
      <webElementGuid>2919ded8-b7d4-4cc9-900d-4595b7af9747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#dommageInfos</value>
      <webElementGuid>380f1587-be2c-4549-aa88-2325bbeb7f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>8af6e210-79fe-4fc6-b481-6d03dfe1c26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nested-partial</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ca8a6b4-e1ae-4fea-8dd1-4c18bbad6e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>5dde2567-9cc7-4b0f-b879-05955f8dcad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b531eb38-0b9d-44e0-9934-914f2fcadc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b122f78-e56d-415c-a65f-5e5c766c8e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez selectionner un type de dommage</value>
      <webElementGuid>d6732c11-e850-4903-9f3d-4aa58364d460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error ajaxValue</value>
      <webElementGuid>c2dba986-6e91-447e-9d9c-e74b2e383132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Type_Dommage_Id-error</value>
      <webElementGuid>8c437ff0-de8b-4e0b-abbb-925a988e4f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;garantie&quot;)/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-lg-12&quot;]/div[1]/label[@class=&quot;my-radio&quot;]/input[@id=&quot;Type_Dommage_Id&quot;]</value>
      <webElementGuid>7ee70896-c9fa-41c1-a188-701572801934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Type_Dommage_Id'])[3]</value>
      <webElementGuid>02d02a4b-1729-4cfb-b249-06c151e12d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='garantie']/div/div/div/label[3]/input</value>
      <webElementGuid>7dd4f250-0cf7-46ac-bd2b-2d8c28a6f3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>59d37608-06ad-4828-b0b3-9360df1605c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Type_Dommage_Id' and @name = 'Type_Dommage_Id' and @type = 'radio']</value>
      <webElementGuid>8711f084-4efb-4f38-a6a0-f6703d4140b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
