<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__N_TF</name>
   <tag></tag>
   <elementGuidId>3cef48b3-443e-49d4-a1f2-06f92bee4118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#N_TF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3daedd8-0617-426a-b9db-ba4114d31301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03f96b83-0742-40b1-986e-c0bbfb9f40dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>858b8beb-4ecf-4a73-b63c-220d5040abf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>afe17ef8-0580-4070-8510-dc343dc5512b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93fc5987-f17a-4983-804c-58880b9dbd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro titre foncier</value>
      <webElementGuid>53b74d8d-adab-4669-a963-8317a22252e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N_TF</value>
      <webElementGuid>b94d19f4-66cc-4726-ac9e-91f774c1ec1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>N_TF</value>
      <webElementGuid>638e2766-663c-4993-a0a0-f6a29b4f2957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;N_TF&quot;)</value>
      <webElementGuid>e466c0ad-27d7-4440-8e63-c665673bfd99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='N_TF']</value>
      <webElementGuid>7f05a082-e2a8-4071-8335-75b11657e0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NumFonci']/input</value>
      <webElementGuid>301a69df-89b3-40ba-b0f7-51f0d499d544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f0989f36-4004-4370-8915-36f5ee437eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'N_TF' and @name = 'N_TF']</value>
      <webElementGuid>c1ce0f5c-29b9-4f52-9eed-21b2cda19aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
