<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__N_Police</name>
   <tag></tag>
   <elementGuidId>720f50d2-096d-4a94-a075-53f2a627bd92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#N_Police</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='N_Police']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8748ad89-127a-4148-b358-f533598c7357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37770b6b-219f-4061-848c-5ced5e917497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>22a79473-5b48-4ae8-92aa-970eadf5937c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>376b8450-8001-4a0f-9875-ed41fa4f8fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d300df7b-4b98-4ef9-ae46-cc8c30c91a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro de police</value>
      <webElementGuid>80398f69-9bf3-4012-a753-6b0ab8d9f3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N_Police</value>
      <webElementGuid>eae29ca0-ff76-4803-ae3b-e36b75603e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>N_Police</value>
      <webElementGuid>a066765c-0444-4bef-9095-60c0b41602ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;N_Police&quot;)</value>
      <webElementGuid>880aea2a-a913-4cd5-b511-0e7206ab528b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='N_Police']</value>
      <webElementGuid>51f161ab-967b-4278-8e46-b3942cf0241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NumPolice']/input</value>
      <webElementGuid>a3ded1fd-20a4-4ec8-86a7-ae97ecb74fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>a0171ca2-6bff-4679-af11-52fa8ce3432c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'N_Police' and @name = 'N_Police']</value>
      <webElementGuid>79cd013e-1fb2-4f63-9cb5-6c82eaea21e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
