<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Adresse</name>
   <tag></tag>
   <elementGuidId>7ce10d02-dd69-4028-bf9d-3663742d2f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Adresse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Adresse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ec138fc2-3eb5-49b8-8ebe-d3cf41b38dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>87bdc7c1-5279-4155-9415-b4f537e2eae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1d7408f9-3357-4c40-80aa-495f8f6eb2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4bccbd59-8bf5-46ef-a9f3-083d86787131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35fc7737-8395-4877-94ea-e81945e3a119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'adresse du lieu de sinistre</value>
      <webElementGuid>aebdffef-ed22-4e1a-b963-ce8073e9888c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Adresse</value>
      <webElementGuid>8246d841-87a5-4989-bdf5-47d8b700e996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Adresse</value>
      <webElementGuid>f0d71a90-fe1a-4aa6-a63f-b94c99d8ff52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Adresse&quot;)</value>
      <webElementGuid>eef363b9-6eaa-4754-8410-5d6dec193f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Adresse']</value>
      <webElementGuid>796c5bc1-dffa-447c-bcd2-5fdd3f4a5204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existInfo']/div[3]/div/textarea</value>
      <webElementGuid>6180c7ff-6164-49bc-b409-7e4340dbd436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c888c23b-e198-488d-9454-fbe4b2b3c5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Adresse' and @name = 'Adresse']</value>
      <webElementGuid>9f1dcdff-1970-4dff-a434-6aadceb53320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
