<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_r2 (en )_ActeAdministratif.r2</name>
   <tag></tag>
   <elementGuidId>7facc6bf-7fa0-4d46-a05a-90fcdf6269c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ActeAdministratif_r2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActeAdministratif_r2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c166ceb-7757-462c-b87b-1a542ddd58fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8fea82f8-4136-4352-9ad5-4ee8af762e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b653e9cb-71ca-415e-9ae4-a79da27989b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field r2 must be a number.</value>
      <webElementGuid>c73c60f3-3eb7-45b0-a2e2-0fbdaf178ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ActeAdministratif_r2</value>
      <webElementGuid>7af5edfb-cda2-45fe-b2b0-01fde4af456a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ActeAdministratif.r2</value>
      <webElementGuid>5d70e930-d368-4a42-b360-249d72a1f2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActeAdministratif_r2&quot;)</value>
      <webElementGuid>7085756f-a7cc-484c-b139-d78fb72699ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ActeAdministratif_r2']</value>
      <webElementGuid>9c8051a9-1264-412b-b535-ce885765faea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div[5]/div[2]/input</value>
      <webElementGuid>c072e94f-bc98-4b68-99ec-fb81ef9f944a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>da6ceb72-9ff9-421d-a580-f11c2de58143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ActeAdministratif_r2' and @name = 'ActeAdministratif.r2']</value>
      <webElementGuid>94a7fc30-7375-4859-a1e3-7037a9ddd290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
