<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Rfrence de l, , acte administr_59de6f</name>
   <tag></tag>
   <elementGuidId>d860cbb0-277e-4dc2-a8c2-0da246fd94e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ActeAdministratif_ReferenceActeAdministratif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActeAdministratif_ReferenceActeAdministratif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eda65d7-b469-4ee6-acf1-961977199a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>960eb5e8-9797-413e-8821-a90a8b9d123d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36afefa8-be78-4e39-87f6-7e987489479b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir la référence de l'acte administratif</value>
      <webElementGuid>d11ec2c6-7789-46ca-8cc8-23ab3f6086c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ActeAdministratif_ReferenceActeAdministratif</value>
      <webElementGuid>341bb8c4-f9df-4142-8b87-8043d5fc5713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ActeAdministratif.ReferenceActeAdministratif</value>
      <webElementGuid>163e30dc-59a9-47a1-a265-5f98a74bfba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActeAdministratif_ReferenceActeAdministratif&quot;)</value>
      <webElementGuid>402c6b19-43c5-409b-8fb7-5bf6a9cddc4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ActeAdministratif_ReferenceActeAdministratif']</value>
      <webElementGuid>8a91e120-6b61-4578-912e-3e5de5072773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div/div/input</value>
      <webElementGuid>83764248-2c17-4514-98d8-abd8f31f1871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>158ba090-41fc-4cd6-9f65-d1ee9e2c421a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ActeAdministratif_ReferenceActeAdministratif' and @name = 'ActeAdministratif.ReferenceActeAdministratif']</value>
      <webElementGuid>b5049fa2-1431-4991-a5c7-07b79933ab39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
