<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date dchance_GarantieResidentiel.DateEcheance</name>
   <tag></tag>
   <elementGuidId>80996570-dba2-4673-87d1-ffa2a7c007f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieResidentiel_DateEcheance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GarantieResidentiel_DateEcheance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>480580d2-cb4a-4f50-a365-ab9ca99b941d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>4e8ece39-a3f6-4548-a1e6-e55668110abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ec3b8863-85df-45fa-af13-97b878e8704b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac704126-8167-4d77-8953-f0c51b44ba6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>La date d'échéance doit être supérieur ou égale à la date d'effet</value>
      <webElementGuid>4cd83ac8-f869-4f57-a61a-703b7d360f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.DateEcheance,*.DateEffet,*.DateSinistre</value>
      <webElementGuid>6db9f727-1748-40e0-a586-6de322d4ca37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>3012165a-da01-4669-8061-fdcddb9e401b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/Date-compare/compare-dates-effet-echeance</value>
      <webElementGuid>c39b25bf-8072-4afa-b235-5920b02059a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Date d'échéance est obligatoire</value>
      <webElementGuid>2b383119-1f08-49ba-bba3-28045dace257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieResidentiel_DateEcheance</value>
      <webElementGuid>5f2c9bc4-ed1b-456f-95e7-7231820a1d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieResidentiel.DateEcheance</value>
      <webElementGuid>c19835b5-c3b3-43a6-823f-44f05fe0e5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieResidentiel_DateEcheance&quot;)</value>
      <webElementGuid>6e06f584-1984-4734-b995-2a3cd5ae56b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieResidentiel_DateEcheance']</value>
      <webElementGuid>cab737b0-89b0-4591-a840-7326d59a0f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>c4b5d50e-20ab-4b11-9fd5-21cc3ff91b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>6d0741c6-8522-434d-a871-9b29053af8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'GarantieResidentiel_DateEcheance' and @name = 'GarantieResidentiel.DateEcheance']</value>
      <webElementGuid>fb8ce7d0-eabe-49e2-93b6-275e9dc9567d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
