<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Slectionner</name>
   <tag></tag>
   <elementGuidId>5c7a3c1d-a4df-4a5a-b2aa-2e0e968e3405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ActeAdministratif-form > div.row.mb-3 > div.col-sm-6 > div.box > div.tail-select.no-classes.deselect > div.select-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ActeAdministratifDiv']/div/div[4]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d64cb0c2-1e84-41e6-95bd-f742b972e044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-label</value>
      <webElementGuid>2ddeeeea-52c5-47d5-9c84-c705031eff8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sélectionner ...</value>
      <webElementGuid>b4696260-ed16-4d96-86db-62a9838a5f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActeAdministratifDiv&quot;)/div[@class=&quot;ActeAdministratif-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect&quot;]/div[@class=&quot;select-label&quot;]</value>
      <webElementGuid>31cf7acd-a86c-4745-a0be-c3b45136dd2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div[4]/div/div/div/div</value>
      <webElementGuid>cb6abc37-31ab-468e-98ca-7f05c28bf746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type du péril'])[2]/following::div[3]</value>
      <webElementGuid>d0edd346-ddc1-4d57-868a-688ae561c639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Date de publication de l', &quot;'&quot;, 'acte administratif')])[1]/following::div[5]</value>
      <webElementGuid>64eb0a01-9b6c-4606-946e-d0f704aa0926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner...'])[2]/preceding::div[1]</value>
      <webElementGuid>bc2ace6c-b4d8-4df4-ad12-fc3d72fd13f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]/div/div/div/div</value>
      <webElementGuid>63933847-2792-4919-9dfa-42c7371e6cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sélectionner ...' or . = 'Sélectionner ...')]</value>
      <webElementGuid>9464711e-a8ff-431d-9de8-c2559e83c0c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
