<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dure_ActeAdministratif.Duree</name>
   <tag></tag>
   <elementGuidId>0b10b217-c89a-4257-a419-7114672087bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ActeAdministratif_Duree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActeAdministratif_Duree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc3ea683-3035-4ee4-b4a5-da6378cccfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9c17c6d1-8408-429a-b10d-b4e51d571c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f3a2c681-5d66-40f1-a75c-4d738ee7d377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Duree must be a number.</value>
      <webElementGuid>abb843cd-0109-424e-b887-5fbb9f2adb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Valeur non valide</value>
      <webElementGuid>1f7f343e-e07e-4d65-bba3-1065d4b9a870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>66011ff5-375f-40b2-915c-008d1de0fe5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de727931-aab0-4266-b19b-7520fc194389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer la durée de l'évènement </value>
      <webElementGuid>36154a6b-919a-4c56-a9f3-6b9a5241f893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ActeAdministratif_Duree</value>
      <webElementGuid>95e23cd0-b0f2-4a03-aad8-bee892a6a7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ActeAdministratif.Duree</value>
      <webElementGuid>040c1618-fbb9-40a0-8935-8f59c1097306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActeAdministratif_Duree&quot;)</value>
      <webElementGuid>ba2d335e-f964-434d-9b02-9e0f54ad2ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ActeAdministratif_Duree']</value>
      <webElementGuid>d6b70ae0-f056-448a-b326-813f7de286f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActeAdministratifDiv']/div/div[2]/div/input</value>
      <webElementGuid>df7c8341-b9ea-4577-bc96-6eb6f8b1ec22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/input</value>
      <webElementGuid>194a2948-0976-4ab9-8d4f-51c943024b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ActeAdministratif_Duree' and @name = 'ActeAdministratif.Duree']</value>
      <webElementGuid>37b28c85-ef9a-41c7-ba7f-8014b0979423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
