<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Bni Mellal-Khnifra</name>
   <tag></tag>
   <elementGuidId>3d3c68ee-c2e9-40af-be25-c0273f428e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tail-select.no-classes.deselect.active > div.select-dropdown > div.dropdown-inner > ul.dropdown-optgroup > li.dropdown-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_Definitives2abfebe7-1f0f-4a87-9665-de141c260abd']/div/div/div/div[2]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87b847ec-11f7-4a22-9bd5-f2b868ad9845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>8e14d618-c7f7-4f16-9971-1a77810d15c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ebcd625e-136b-40b4-853d-79098ce7add2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2be2bfb7-c6dd-491f-8b20-292c2a1b9c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Béni Mellal-Khénifra</value>
      <webElementGuid>b0f9b31e-a60d-497e-aee9-4b4a647db0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_Definitives2abfebe7-1f0f-4a87-9665-de141c260abd&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>e64c0e75-4908-45d2-b16e-c05f22ff9a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_Definitives2abfebe7-1f0f-4a87-9665-de141c260abd']/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>17f2c8eb-6ff1-4a78-bd43-ddc8acd621a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner ...'])[4]/following::li[1]</value>
      <webElementGuid>bc38a893-c2b9-466b-8956-6b72f3e83967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Région'])[2]/following::li[1]</value>
      <webElementGuid>87f1d250-259b-4a2a-a15a-b4166d5a5271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drâa-Tafilalet'])[4]/preceding::li[1]</value>
      <webElementGuid>2159826d-37ef-4a7f-ae93-9f1b43a1c439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eddakhla-Oued Eddahab'])[4]/preceding::li[2]</value>
      <webElementGuid>801c1479-13c4-420b-beff-33d32086df9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>36ec5445-6706-4fd1-b801-d6e3707bf445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Béni Mellal-Khénifra' or . = 'Béni Mellal-Khénifra')]</value>
      <webElementGuid>d14cbd07-22d9-4f68-9fe5-b92a5c1d7cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
