<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_MAR_BEM</name>
   <tag></tag>
   <elementGuidId>0c956a1a-5f93-45c2-8940-3c24d265f1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tail-select.no-classes.deselect.active > div.select-dropdown > div.dropdown-inner > ul.dropdown-optgroup > li.dropdown-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ZoneTouchees_Definitives[2abfebe7-1f0f-4a87-9665-de141c260abd]codecrestaList']/div/div/div/div[2]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>eaf2a0ba-48ab-4b46-b9b9-882b11415288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>492d0e22-536d-4eac-bf6a-dafe1c967b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>0acad6bd-5a30-43f2-9fa0-e4945efea36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d8d3a42b-8525-4f15-8e01-ebcd4a2bb35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MAR_BEM</value>
      <webElementGuid>53c51daa-f4f1-4a27-adbe-6218b65a8f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZoneTouchees_Definitives[2abfebe7-1f0f-4a87-9665-de141c260abd]codecrestaList&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>a021005b-7da3-4d93-bb73-d3439343e17d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ZoneTouchees_Definitives[2abfebe7-1f0f-4a87-9665-de141c260abd]codecrestaList']/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>fb3f4a8e-ea0d-48f0-833e-2aaf09954345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner ...'])[4]/following::li[1]</value>
      <webElementGuid>48552a83-63ac-464e-80a3-51eb3014137d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code Cresta'])[2]/following::li[1]</value>
      <webElementGuid>b818525e-e722-4328-8ca8-2dde94183658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ville'])[2]/preceding::li[1]</value>
      <webElementGuid>db6b9997-c8d4-4eb5-b246-c09db846e673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner ...'])[5]/preceding::li[1]</value>
      <webElementGuid>690236a4-524c-44a1-8ada-82df3eaa72c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>008745ad-8419-47e9-ab91-4b88cd923365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'MAR_BEM' or . = 'MAR_BEM')]</value>
      <webElementGuid>f73d86c4-cf3d-410a-abfb-9d83b2d37de5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
