<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dfinitive_checkmark</name>
   <tag></tag>
   <elementGuidId>f02b5c4a-30bc-4553-87d9-f1e085ffb87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='createEvenement']/div/div/div/div/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36b003f9-25e6-4196-b2b8-0cc8f4fec2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>265f4c82-f7d7-429c-a8e4-033f4aa1c60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createEvenement&quot;)/div[@class=&quot;new-avocat&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[1]/label[@class=&quot;my-radio&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>11314d45-8d80-4de8-8adb-7df47e7b2f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createEvenement']/div/div/div/div/label[2]/span</value>
      <webElementGuid>783c2662-502f-4eb2-b52f-2ccfc71998cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>606efdfe-4758-45b4-a643-912c7bc72e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
