<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lignes par page_searchString</name>
   <tag></tag>
   <elementGuidId>0c4f3e42-0509-4ae3-942a-b42d52af2ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchString&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2523eb19-f7a1-43bc-8209-99e957f7e737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53badb5d-3de5-4f80-9f4c-68b22fbbdec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>5f3ccf20-565d-4d16-94dd-06b945ec915d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchString</value>
      <webElementGuid>72ebc4e4-9020-4883-8bbd-1a163b89493c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExperCatForm&quot;)/div[@class=&quot;row ExpertTable&quot;]/div[@class=&quot;col-sm-6 6 mt-1 barre-tab&quot;]/input[1]</value>
      <webElementGuid>df1fa5f3-f72f-4f28-bb6c-2a2ff87bed49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchString']</value>
      <webElementGuid>d5080c5f-bc04-4f9f-a127-5d2d09b30ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ExperCatForm']/div/div[3]/input</value>
      <webElementGuid>1a877e1b-1fab-46d2-b8c2-cf8d4959f946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a18d36fd-8386-4b62-a8f2-cd7865db6f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Rechercher' and @name = 'searchString']</value>
      <webElementGuid>31d22192-c78d-468e-bc80-6a50349cb347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
