<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Capacite</name>
   <tag></tag>
   <elementGuidId>b09dd3e9-aed2-4bb1-8c8b-4399b95b3459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Capacite']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Capacite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35bd9c88-9caa-4bb9-b656-d58534c54792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>11e74495-8122-4c37-b8ed-e5d7ae82ec84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c50f2789-5667-4593-92ca-3fbdb254e419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Valeur non valide</value>
      <webElementGuid>5fb4d630-4afb-4263-8622-481f923fbc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>a95245d8-791c-4f88-b285-20492d68f2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8eaa7a0d-65a7-4249-adce-c854329c7d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir la capacité</value>
      <webElementGuid>c14ec477-8b88-49e1-aa41-5185ef5c78d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Capacite</value>
      <webElementGuid>7d63527e-1f32-4ca8-b118-04739488884f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Capacite</value>
      <webElementGuid>821e0b76-19d5-40b7-aeff-479e4482200e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Capacite&quot;)</value>
      <webElementGuid>3003d5f3-b2a8-4b9e-9c8b-527dade40071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Capacite']</value>
      <webElementGuid>53cd01b0-c7d5-4912-bf20-e09c469f17e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/form/div/div[9]/div/input</value>
      <webElementGuid>469da78a-5bc7-4bae-b6fc-bea012929a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>d60ec3a6-49cf-4948-a35d-97ceb63eb47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Capacite' and @name = 'Capacite']</value>
      <webElementGuid>e1f3be9c-31b9-40f5-b16e-02548a235831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
