<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Identification de la dclaration</name>
   <tag></tag>
   <elementGuidId>e7e9b9f1-c595-48cb-81e9-069023955103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableDeclarationForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tableDeclarationForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>970e03db-6402-4438-b3c7-f221f3ba43f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3edd96b2-37e3-4020-afce-1c5d22db713a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>3201a1d4-e2cc-4b66-9be2-0b27067f712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/get-table-demande</value>
      <webElementGuid>12243f47-2e31-43b9-965b-49f54e8b1e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>7a51f673-cf18-4712-a573-3430cfe36ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-begin</name>
      <type>Main</type>
      <value>ajaxBeforeSubmit</value>
      <webElementGuid>82ae3b51-2aad-471e-ab4d-64b40127ca2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsSinistre</value>
      <webElementGuid>64566733-6486-4ba7-87d7-eab8de3e7f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidationSinistre</value>
      <webElementGuid>acd9e543-b2cd-4a27-be4a-672a33369005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#declartionIdentity</value>
      <webElementGuid>8ecc8b36-7511-4b7b-a97a-47d280e84242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>ce721649-8c44-487f-828e-543ecd9e3fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn link out</value>
      <webElementGuid>992a75d3-693f-4038-b24c-c7c037a91055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identification de la déclaration
                                                </value>
      <webElementGuid>fdf0824d-f494-4107-b38e-99eee9a6da0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableDeclarationForm&quot;)</value>
      <webElementGuid>ff01627e-066d-400d-be78-ae2229041473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tableDeclarationForm']</value>
      <webElementGuid>2ab2c5e1-b120-4567-90c5-ca4cc60e3327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dommageInfos']/div[6]/div/div/a</value>
      <webElementGuid>cfaf01d6-7797-4207-a141-7a8fddce456b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Identification de la déclaration')]</value>
      <webElementGuid>b4501f65-e0c0-442c-83b2-de3ca68ef109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::a[1]</value>
      <webElementGuid>cfd5d1eb-7bbc-45e7-bf0f-4216677ab441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuer'])[1]/preceding::a[1]</value>
      <webElementGuid>87548b71-eb8d-4415-a1a3-75f04a41c7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/preceding::a[1]</value>
      <webElementGuid>4ee7f3f2-40e9-4542-9242-835c3843a6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Identification de la déclaration']/parent::*</value>
      <webElementGuid>59c9f301-0989-476b-a177-2096917e80d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a</value>
      <webElementGuid>2a22fc52-cd88-4c9c-8b1f-3bafc7096ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tableDeclarationForm' and (text() = 'Identification de la déclaration
                                                ' or . = 'Identification de la déclaration
                                                ')]</value>
      <webElementGuid>88a4b139-d5a0-4483-889d-9ceb65417ee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
