<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sauvegarder et Publier</name>
   <tag></tag>
   <elementGuidId>ce384c8f-c20a-4eeb-9c45-c51c59dd3edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2023c2ce-fcbf-453b-9c27-1e324b9863cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnSave</value>
      <webElementGuid>78ee4e92-1158-47a9-8e14-f0a475f9f65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4dc683cd-29bd-4e29-881f-7afe5211b45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BtnSave</value>
      <webElementGuid>d1496269-bed4-4f9d-9619-725230f0e6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sauvegarder</value>
      <webElementGuid>9f11fecb-0be0-445a-86a7-755a47de288a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>f27d9847-30cf-49a1-aa92-e1e553fbf56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sauvegarder et Publier</value>
      <webElementGuid>0cd45d70-f4df-4935-aa04-f37956867bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnSave&quot;)</value>
      <webElementGuid>24be782a-1952-41fc-b2b8-d96fa82d72e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnSave']</value>
      <webElementGuid>66541b92-25ed-407a-982b-90610af9a294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[6]/div/div/button[2]</value>
      <webElementGuid>596b591d-ef81-41be-9219-8557fdf7b03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enregistrer le brouillon'])[1]/following::button[1]</value>
      <webElementGuid>f0dd5c1f-aa1b-47c7-92c2-9f878d2e313c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Les fichiers selectionnés'])[1]/following::button[2]</value>
      <webElementGuid>dd89b8a0-fdc4-4c3d-b655-a6d1f8cdfe3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/preceding::button[1]</value>
      <webElementGuid>109ed2bb-92bc-4723-9761-5addc02c3b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 All Rights Reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>31b39220-0f0b-4a90-8f98-c65c26bce935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sauvegarder et Publier']/parent::*</value>
      <webElementGuid>2a2589b1-155f-43c8-b5b7-6c8ce124ee02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>03501432-3eb6-4319-b3ab-b5ae6729127f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnSave' and @type = 'submit' and @name = 'BtnSave' and (text() = 'Sauvegarder et Publier' or . = 'Sauvegarder et Publier')]</value>
      <webElementGuid>3bae2257-a0d4-46c7-a5c2-84e17a9f8e48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
