<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuer</name>
   <tag></tag>
   <elementGuidId>7e719bb8-687f-4f50-ab0b-b926fdd4c7b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitDemande</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitDemande']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b2bf0d0-6503-453d-aa2f-b451f14f1c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>75973860-9165-4003-982b-22ddfef279c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d1377f1-12e4-4a88-bf86-1b65cb919764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitDemande</value>
      <webElementGuid>1bebb2fd-db34-40ce-8deb-db49078fff0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuer</value>
      <webElementGuid>7523aab2-a1a3-4384-9b5e-407815e650ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitDemande&quot;)</value>
      <webElementGuid>d714da6f-8108-4d45-b1f0-9d7ab41ddd55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitDemande']</value>
      <webElementGuid>c22946aa-bcac-44e3-9587-ec9c2c35e470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/form/div[3]/div/button</value>
      <webElementGuid>c12521ea-ce04-4c5e-b9db-f4314feee165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tesldksfsdhfl'])[1]/following::button[1]</value>
      <webElementGuid>ca35c32e-bf69-4c3f-a2a0-5cef4783e0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::button[1]</value>
      <webElementGuid>cc978699-12fb-4829-98e0-4a94533888a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/preceding::button[1]</value>
      <webElementGuid>ab392a35-16d3-4e3a-9c51-6abbfe3f8796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 All Rights Reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>822a9488-e5c7-4c7d-aecf-5eba0e71cffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuer']/parent::*</value>
      <webElementGuid>1b5e0e3e-52b8-46b8-9b8a-2346c76de6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a6c909bd-30cc-44ee-bdc9-958786b28f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submitDemande' and (text() = 'Continuer' or . = 'Continuer')]</value>
      <webElementGuid>2e567f1f-acfe-4632-9b28-b8604457d667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
