<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Demandeur.N_Type_Doc</name>
   <tag></tag>
   <elementGuidId>65cc76ea-d647-4b4b-95c8-8bfd521a0cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Demandeur_N_Type_Doc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Demandeur_N_Type_Doc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43dafd28-35da-4812-b84c-cb34352644c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e21e406-3801-4078-90cc-ffcf770f2976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>1ee7d5ac-0d77-4c05-84df-355b65191d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>demandeurInfos</value>
      <webElementGuid>140159af-04ab-445f-a069-03445b6496ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>101696ec-53c3-4895-8949-dbf3a1c5d87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N_Type_Doc' is invalid.</value>
      <webElementGuid>b9fd4c8d-d173-4c22-803c-6f3ca84dce27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Type_Doc,*.Type_Doc_Id</value>
      <webElementGuid>27694581-3eda-4f75-9501-86601ff6d138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>a6936656-7649-4888-85b2-0d95549892a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/FieldVerification/RegexCINE</value>
      <webElementGuid>85c5c67b-243a-4b71-8014-84cb0127f4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'identifiant du document</value>
      <webElementGuid>bd00e3b0-a908-4eb8-a223-2cd4ed6cb072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Demandeur_N_Type_Doc</value>
      <webElementGuid>6b6968d1-51c6-4289-a933-d39536c47a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Demandeur.N_Type_Doc</value>
      <webElementGuid>76b9d992-8bd1-4133-838e-dfca9fd2edcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Demandeur_N_Type_Doc&quot;)</value>
      <webElementGuid>7da84c9a-3379-43cb-9e1c-85d0c217418a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Demandeur_N_Type_Doc']</value>
      <webElementGuid>7754aeea-0a3a-4b43-8043-2be38fa2fb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>72db69a1-8948-4785-b7c7-11029c729baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>d9f32b5b-870e-4a05-9bf6-8d92f768f6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Demandeur_N_Type_Doc' and @name = 'Demandeur.N_Type_Doc']</value>
      <webElementGuid>40cd0d40-caa1-417a-9be1-c71997ec91ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
