<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Demandeur.Prenom</name>
   <tag></tag>
   <elementGuidId>93822e93-6c8c-4e51-8a6a-b05c5020b7dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Demandeur_Prenom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Demandeur_Prenom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5ab0cff-3c9d-410b-bc9f-ec537abe159a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cfbebca-1b05-4093-bf52-777207d2b29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>5cab806d-5571-42c5-b708-338f7c02fe03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>demandeurInfos</value>
      <webElementGuid>dc4acd8e-d136-4f9b-85ec-e028d7006a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6af9be88-fdc9-424e-ba2e-bf410f67fc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le prénom</value>
      <webElementGuid>bc9dfd85-11f1-44ba-a973-ff03d81344c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Demandeur_Prenom</value>
      <webElementGuid>f90ca2d2-701c-4343-ad85-89111029b76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Demandeur.Prenom</value>
      <webElementGuid>3202d298-5f30-4238-839c-08f27063a234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Demandeur_Prenom&quot;)</value>
      <webElementGuid>6c8f728c-3414-4171-a9b4-9dcc436007d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Demandeur_Prenom']</value>
      <webElementGuid>90c8f57e-2991-4e77-99d6-3278afafb66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div/div[2]/input</value>
      <webElementGuid>191c98dc-72d4-4312-84bb-860d3c4734a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>ffe4d9a9-a416-4aab-bf84-f9b07a74103a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Demandeur_Prenom' and @name = 'Demandeur.Prenom']</value>
      <webElementGuid>aee76360-a618-4219-9112-96b82ce61e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
