<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Attachement.FichierIdentiteAssure</name>
   <tag></tag>
   <elementGuidId>ed6334f1-282d-4444-906d-927c5d053280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Attachement_FichierIdentiteAssure']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierIdentiteAssure</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98110ea7-a0f7-4f9d-bc3a-05be4d04f6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cc10da7-289e-4f64-881c-9f687b6a6910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>e03bd0e6-4bf3-4160-a150-a5152b5cdb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>1b4beca1-e713-4515-a641-e93460d68cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierIdentiteAssure</value>
      <webElementGuid>824972db-48f6-4d70-9703-c5de6c648e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierIdentiteAssure</value>
      <webElementGuid>341e0b34-f2d8-429b-9dc0-a447a8001f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierIdentiteAssure&quot;]</value>
      <webElementGuid>284a4808-05d9-4c7a-a0f1-8ecb9497c3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierIdentiteAssure'])[2]</value>
      <webElementGuid>21947136-a6ee-4980-a6ac-4f119173a41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>b0ca1e07-85e5-4fdf-89cc-d8d130ade4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>dc1a089f-f5a9-498f-acea-11f44d146155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierIdentiteAssure' and @name = 'Attachement.FichierIdentiteAssure']</value>
      <webElementGuid>45feab3d-58e4-4bb2-9224-66186a58e12e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
