<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Demandeur.Nom</name>
   <tag></tag>
   <elementGuidId>bac32799-ab4f-4a0b-a4cb-9a0093d63e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Demandeur_Nom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Demandeur_Nom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1f97cbf-18c5-4270-aa6e-5ac3821f8b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3afd45d2-cea3-4bcc-ba12-3e416a15dc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>37976374-893e-4e1f-b5e8-4e2223abd7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>demandeurInfos</value>
      <webElementGuid>5d19f7c3-f32e-4b66-96d1-7d2a8687c3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dca0f1af-2dbe-450c-bf0a-a4b31ec66e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le nom</value>
      <webElementGuid>079b9480-7b67-40cc-8db2-871f16f4672f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Demandeur_Nom</value>
      <webElementGuid>4dbef83e-8306-4869-8d7c-50525b73bcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Demandeur.Nom</value>
      <webElementGuid>52b949a2-03b0-4e24-b867-16f47f9b341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Demandeur_Nom&quot;)</value>
      <webElementGuid>866f4f6e-1eb9-4bf2-b26a-e824037e5bc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Demandeur_Nom']</value>
      <webElementGuid>d149343b-6080-4b6e-bb80-5ee20abe337d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div/div/input</value>
      <webElementGuid>5a82a67d-1ae2-4352-8ef5-6a77e9ae85b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[2]/div/div/div/input</value>
      <webElementGuid>89f90001-e3a7-4557-b9a8-da7db1d80645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Demandeur_Nom' and @name = 'Demandeur.Nom']</value>
      <webElementGuid>a4947772-537e-497d-914e-524e2fa4f588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
