<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__N_Immatriculation</name>
   <tag></tag>
   <elementGuidId>5cd1d5d8-c142-41a1-a45c-1f8df7592f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#N_Immatriculation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='N_Immatriculation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8f6abc3-3f48-482d-8922-ca5b57fc084d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0797381-5b05-4e71-9b4b-258d543cb793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue  </value>
      <webElementGuid>16d789ed-207d-4c4a-9c4c-21acf4761495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>9716b187-6cd9-474f-9c8d-082febca6116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4365c7ce-0813-4451-b766-85041e7de32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N° Immatriculation' is invalid.</value>
      <webElementGuid>ff992f92-c214-48dc-89c2-a3223af87671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Immatriculation,*.ImmatriculationFormatId,*.Ref_Event_Id,*.Type_DocSinistre_Id,*.Type_Dommage_Id,*.NatureDommageId,*.Type_Garantie_Id</value>
      <webElementGuid>c02c9c93-7274-47ac-be95-efcb9f20423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>53a0f966-6e10-4e37-9054-2cbcd09f3d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/FieldVerification/RegexImmat_Verify_GA</value>
      <webElementGuid>954ba1a2-8882-437d-84ae-9fafc77bc53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro d'immatriculation</value>
      <webElementGuid>4bd27871-aa43-4a4c-8ed1-1233c7a88b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N_Immatriculation</value>
      <webElementGuid>d77ecc8a-3e09-4c27-9bb9-e542c94a8585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>N_Immatriculation</value>
      <webElementGuid>2f6b5205-d0a4-4e39-855f-baef1ef88c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;N_Immatriculation&quot;)</value>
      <webElementGuid>bf8a1967-d88b-4a41-9080-5769f8f87da5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='N_Immatriculation']</value>
      <webElementGuid>0c927da0-3539-4b3e-b264-fa62ad66aa47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imma']/input</value>
      <webElementGuid>6dc04cea-62f7-4317-ac51-9cfb6e303bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>4a9f2294-9c5c-4d88-b95e-dbeea74adde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'N_Immatriculation' and @name = 'N_Immatriculation']</value>
      <webElementGuid>fc6ae087-7350-4bbf-9d78-847e7cecd0b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
