<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__N_Police</name>
   <tag></tag>
   <elementGuidId>ab4fa814-ae6b-418f-912d-ac501b54a30f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#N_Police</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='N_Police']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4b3358f-280d-4428-a872-97ef5280f2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e03d5a92-6c28-4b7b-98a2-b05226c4faaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>bf989780-58b7-4be5-b9db-b28410f1ff91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>a086899b-2748-4b28-ba65-77ff9043b76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04181559-d73f-47a8-b6f5-0428ec8ed646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro de police</value>
      <webElementGuid>b3ab1ea9-951e-4851-8d5c-e9844634d053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N_Police</value>
      <webElementGuid>80b7c039-cf76-4b2c-b0e6-995ae20bd845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>N_Police</value>
      <webElementGuid>3d826eee-8a38-4251-ad73-c8f8517bd084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;N_Police&quot;)</value>
      <webElementGuid>8057fea3-15d7-4508-b626-6d906be7c355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='N_Police']</value>
      <webElementGuid>56152d4e-ecde-4055-88c5-00609456d28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NumPolice']/input</value>
      <webElementGuid>94db957b-2106-4b81-a699-de6b12072881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>e202778c-cf57-4fd6-8ed8-94f0ddaedb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'N_Police' and @name = 'N_Police']</value>
      <webElementGuid>35c46527-dda6-4450-80d8-07ae75b76d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
