<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vhicule_Type_Dommage_Id</name>
   <tag></tag>
   <elementGuidId>a80d909c-58f3-4fed-9008-762fe5034b5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Type_Dommage_Id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Type_Dommage_Id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1f4bf96-51c6-4bcd-a579-4b0abb6f0871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>7890357f-c4a5-4077-b2c2-63f9cb8c3d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>261b5fdb-0043-49d7-8461-632538c7835b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>1fcf88df-c92e-403f-9938-db0defaf0976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>85e5edac-b25f-481c-865c-3894b6dc70fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f05e88ed-19cf-40df-b0d6-e88e665f6877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0dbceaaa-be62-4765-8631-3e1ed9c87b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/get-info-type-dommage?q=9oc1ZR4JEzXNdh3GJ7Jsnvp3-DYBE22o3zTLTBGSyz8=</value>
      <webElementGuid>ef318408-15c0-4ca5-bb34-1a25251569f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>6ff9dd99-2721-477b-9c37-1401bb603b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsSinistre</value>
      <webElementGuid>9547d912-3815-4a14-bf75-d6e88abc2519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidationSinistre</value>
      <webElementGuid>b0248210-8e85-4071-b0f3-89819b678189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#dommageInfos</value>
      <webElementGuid>672bf7c9-01cb-4dd5-b4f2-c8a76b43b7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>a727d931-29f8-414e-b70c-f09ddc65839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nested-partial</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee3b86ba-2fbc-4531-8b95-d76e5cd07232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>14cc837f-6c80-48f0-8a3e-4edc359f70fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>595d8e84-d0e6-4529-bb50-772e9e9949c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48424d11-4fcc-4971-b3ed-f14f237972f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez selectionner un type de dommage</value>
      <webElementGuid>453aaa99-833a-4a45-aa9e-f4890b1639a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error ajaxValue</value>
      <webElementGuid>0b972432-580b-467e-a430-06791fe81e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Type_Dommage_Id-error</value>
      <webElementGuid>29a5080d-477e-4791-a42c-2a2db5739170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;garantie&quot;)/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-lg-12&quot;]/div[1]/label[@class=&quot;my-radio&quot;]/input[@id=&quot;Type_Dommage_Id&quot;]</value>
      <webElementGuid>090cfbbf-00e4-44e0-a750-dd800caa8964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Type_Dommage_Id']</value>
      <webElementGuid>2863b82c-1507-46ac-87b1-31098346c210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='garantie']/div/div/div/label/input</value>
      <webElementGuid>efe4d068-ee84-471b-887d-3f4f6fcd4e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>17a1663e-2292-4dae-ae39-3de75bf60e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Type_Dommage_Id' and @name = 'Type_Dommage_Id' and @type = 'radio']</value>
      <webElementGuid>d10bc6d7-a750-465e-94a9-10400e26e592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
