<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_N de lattestation</name>
   <tag></tag>
   <elementGuidId>ed0c9f22-864b-47b2-bbd5-2d61e7410775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NumAttes > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NumAttes']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b2d71291-e9c0-4c2d-83c2-6caa94bc4ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>N_Attestation</value>
      <webElementGuid>2c4443b0-4e03-4568-9cea-e49a31065fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>N° de l’attestation *</value>
      <webElementGuid>368e626f-b098-403e-9a6b-5684b4e0e079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumAttes&quot;)/label[1]</value>
      <webElementGuid>9801d755-57eb-4422-b839-1f89df775e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NumAttes']/label</value>
      <webElementGuid>bc8bd922-e36d-43f7-9916-43e8e9011dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::label[1]</value>
      <webElementGuid>bcf465c7-5357-4028-aa27-b88f9cd2c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='N° de l’attestation']/parent::*</value>
      <webElementGuid>1558a11c-768f-4d5e-8c63-1e6743e3af73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>9d2885fe-6c2b-421b-be96-dea8478a1364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'N° de l’attestation *' or . = 'N° de l’attestation *')]</value>
      <webElementGuid>31a76d9a-b48d-4680-93ee-11c696f0c1f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
