<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Assur</name>
   <tag></tag>
   <elementGuidId>c0e454d5-de88-4f32-920f-b2b78acb9db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tail-select.no-classes.deselect.active > div.select-dropdown > div.dropdown-inner > ul.dropdown-optgroup > li.dropdown-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formSinistre']/div[2]/div/div[4]/div/div/div/div[2]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ce692b25-2f8a-4212-896a-fb6decebaf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>7b07ff10-35ab-4672-8a18-5797736a27a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9a784058-40af-4152-979e-e8112323b5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>fa171dad-f706-4a16-b5cb-06a030c09426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assuré</value>
      <webElementGuid>d3251952-543e-4021-9306-d2ad230ae0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;Demendeur-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>8ce5a172-c715-412d-96c8-5c219c8c1e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[4]/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>0e3dde8f-c17a-4687-8d54-588a53a6fdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner ...'])[1]/following::li[1]</value>
      <webElementGuid>8d3be5eb-c64d-4164-bfd1-129ad7f3ed37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[20]/following::li[1]</value>
      <webElementGuid>5364df4e-59ca-47fe-a500-cf7750e78ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Souscripteur'])[2]/preceding::li[1]</value>
      <webElementGuid>462b3762-ceed-4f7f-a99c-2e918ed4c7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autres à préciser'])[2]/preceding::li[2]</value>
      <webElementGuid>83151f7b-321b-40bf-ae08-bfbd375f5c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>0cf59007-0904-45f8-a57e-4a866a0ace2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Assuré' or . = 'Assuré')]</value>
      <webElementGuid>bfeebe18-15c9-423e-a89a-60d7205e74a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
