<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_WQVPEE NeKECbTx_checkmark</name>
   <tag></tag>
   <elementGuidId>6b8725a1-bafc-4616-99cb-5433fb8e1ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4) > div > label.my-radio > span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tableDemande']/table/tbody/tr/td[4]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96ee5582-0bc6-43e8-8d44-585fc4888189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>b1c4509c-06a7-421e-9c1e-403923a02e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableDemande&quot;)/table[@class=&quot;omn-table table table-condensed table-body-center actions&quot;]/tbody[1]/tr[1]/td[4]/div[1]/label[@class=&quot;my-radio&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>bff9998d-a54b-448f-9916-b4140e752397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tableDemande']/table/tbody/tr/td[4]/div/label/span</value>
      <webElementGuid>c865d234-f926-4afb-929f-4f0ed9594291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/label/span</value>
      <webElementGuid>5753dfb5-2252-4d01-9683-4d7ba09138bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
