<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Assure.Adresse</name>
   <tag></tag>
   <elementGuidId>9fe7c594-2ce6-49e6-8534-c5fdf2dad703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Assure_Adresse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Assure_Adresse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3efbbbb3-1a9e-49bb-9b37-1c482dfd2b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f42dd166-dc06-4ad7-a1bb-0039f3d9b149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6e954c7-6af4-4f86-91e3-d66cb32d3745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'adresse</value>
      <webElementGuid>7f7322fb-34c7-45fe-95cf-babe3cb4df7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Assure_Adresse</value>
      <webElementGuid>2c01588d-3d6d-48ba-aaf3-c3fbf3f518dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Assure.Adresse</value>
      <webElementGuid>3206da4b-25fb-418a-98e3-27b5946e149d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Assure_Adresse&quot;)</value>
      <webElementGuid>0653b207-11df-4910-8271-6f9383232ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Assure_Adresse']</value>
      <webElementGuid>75f31ba8-645e-4643-ac98-97cd7fcbd009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autreQualiteDemandeur']/div/div/div[5]/div/textarea</value>
      <webElementGuid>02f04d5b-265c-463b-a252-cf37eebd9546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/textarea</value>
      <webElementGuid>8573ecaf-cf16-403f-bdbe-58edb768688e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Assure_Adresse' and @name = 'Assure.Adresse']</value>
      <webElementGuid>011b3aa2-ee5c-4eee-b060-12e2c66bf819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
