<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DateEvenement</name>
   <tag></tag>
   <elementGuidId>4d5b1e67-f425-4a88-89e2-d040fb1755d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DateEvenement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DateEvenement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dbca3e0-844d-4185-b6f5-d0d8fa902c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>f0a181c1-41a0-4d05-b747-5d3e73ff6574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Evenement_DateEvenement</value>
      <webElementGuid>b3042bf6-028a-4207-b036-7e9ecdc3c4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d64bb5c-67e0-43cf-a660-690de99c37d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez insérer la date de l'évènement </value>
      <webElementGuid>f42e0171-f6ef-410d-8b3d-d59cba9c1bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DateEvenement</value>
      <webElementGuid>e96df695-5a6d-4aef-862b-b7ebf60d5f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DateEvenement</value>
      <webElementGuid>515deb00-cd29-46ce-95a3-a2240a5823ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DateEvenement&quot;)</value>
      <webElementGuid>00c84dd9-41ae-4516-b545-0de24718b039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DateEvenement']</value>
      <webElementGuid>241c74ae-9985-428e-9267-3a9174ecdadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DateEvenementDiv']/input</value>
      <webElementGuid>a34235dc-6d3d-4c1b-8c01-019fe7f4402a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8af3d2e4-185b-46ae-ab77-b7505820b111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'DateEvenement' and @name = 'DateEvenement']</value>
      <webElementGuid>5f98b560-2ac0-4154-b0c6-4d775c034728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
