<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>region_Slectionner</name>
   <tag></tag>
   <elementGuidId>bf5b6af4-6006-40b0-829d-72ea20a819c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='select-label'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4711b5cb-34db-4876-8e7f-e62950bdb4d1 > div.col-sm-6 > div.box > div.tail-select.no-classes.deselect > div.select-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54b47a30-5e96-4275-b028-0a6d66c4f7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-label</value>
      <webElementGuid>9edae6c0-9a8b-4e7c-95fe-965695a8528f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sélectionner ...</value>
      <webElementGuid>a8aec057-82da-41b8-a56e-cba858f75117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4711b5cb-34db-4876-8e7f-e62950bdb4d1&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect&quot;]/div[@class=&quot;select-label&quot;]</value>
      <webElementGuid>97fb1ce8-b291-41e8-b6a8-4007c9c61a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4711b5cb-34db-4876-8e7f-e62950bdb4d1']/div/div/div/div</value>
      <webElementGuid>fd3bb110-b91d-478e-aa58-cfda3f688d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Région'])[1]/following::div[3]</value>
      <webElementGuid>b91ef422-17f8-4b4b-ad50-623fc5a7f407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zones touchées provisoires:'])[1]/following::div[8]</value>
      <webElementGuid>dcc66284-7bb9-433d-a752-a812e39ce1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Béni Mellal-Khénifra'])[2]/preceding::div[1]</value>
      <webElementGuid>a055c382-d0b0-410c-8b3f-3e3ef338ca49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>08af825e-ce24-4bf9-a188-4d798cf1568c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sélectionner ...' or . = 'Sélectionner ...')]</value>
      <webElementGuid>3f0c43d0-a90d-461f-a125-fab14d84eb50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
