<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filtrer</name>
   <tag></tag>
   <elementGuidId>4e052bfb-36d5-4410-8c64-6978c36134d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnfilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnfilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>065ee395-7bd0-4449-9ac4-a386e0e3eb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnfilter</value>
      <webElementGuid>f15d341e-3a7d-445a-915d-5c9979175604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>51171837-955a-48cb-9b74-f9675383c923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filtrer 
                                        </value>
      <webElementGuid>63f8a056-7389-4b4e-8d21-eea243056952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnfilter&quot;)</value>
      <webElementGuid>fd648d24-1398-4c8b-9509-dd5b0148e7f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnfilter']</value>
      <webElementGuid>91728843-2614-486b-af3c-f58839954447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='personForm']/div/div/div[2]/div/button</value>
      <webElementGuid>32bd51dd-be5f-452f-8b33-09bb791613d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N° de police'])[1]/following::button[1]</value>
      <webElementGuid>facf663d-9fdf-4b5d-91de-ed6801a76c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporel'])[2]/following::button[1]</value>
      <webElementGuid>86b14244-688f-4a10-9fc3-7c2c639dbf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tableau de consultation :'])[1]/preceding::button[1]</value>
      <webElementGuid>b8600715-aec9-4ec1-9197-b4b2639cfecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lignes par page :'])[1]/preceding::button[1]</value>
      <webElementGuid>ac561300-14cd-4a82-aaeb-6b99a29912e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filtrer']/parent::*</value>
      <webElementGuid>e372390a-21a3-4de6-87ce-cecbd17f643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>63abb13b-f6d4-4fd4-8291-bf44bd5ed6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnfilter' and (text() = 'Filtrer 
                                        ' or . = 'Filtrer 
                                        ')]</value>
      <webElementGuid>60f4be9e-cea3-403c-b4f0-20ea192b27e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
