<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rsidentiel_Type_Dommage_Id</name>
   <tag></tag>
   <elementGuidId>2ef8509d-7ec8-4c11-9576-e1d6c0f8a3a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Type_Dommage_Id'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13182b53-a986-4cff-bffd-cc3fb399e122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>bd35ef42-714f-4ffa-bc95-6ea1ef714d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type_Dommage_Id</value>
      <webElementGuid>fbcf84f9-61dc-46f8-9c2a-c055755d7cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d9b93d1f-0a31-4aa0-a7d0-e395e2cd2d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8faee56d-4308-48b1-b574-53eb0a595b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_Type_Dommage_Id&quot;)/label[@class=&quot;my-radio&quot;]/input[@id=&quot;Type_Dommage_Id&quot;]</value>
      <webElementGuid>6ff5f751-5708-4b77-927a-29822b3a8446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Type_Dommage_Id'])[3]</value>
      <webElementGuid>93bc3c72-a2b9-484c-a785-644e1c059472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_Type_Dommage_Id']/label[4]/input</value>
      <webElementGuid>fad15e2d-fe47-4511-acac-8862f9795944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>78d37010-f7d3-4982-8b70-425e3a655f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Type_Dommage_Id' and @name = 'Type_Dommage_Id' and @type = 'radio']</value>
      <webElementGuid>e5c2e9dd-d907-4b28-992a-a80a71477238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
