<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commune sinistre_checkbox</name>
   <tag></tag>
   <elementGuidId>337a2630-4702-40ec-a4b4-bc5bb65bf09c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section/div[1]/div/div/div/div/div[2]/form/div[2]/div/div[2]/div[5]/div[2]/div[1]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc1a1da0-7b74-4cf7-801f-0944c23bcb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>248ae08f-7172-473d-8b03-03f5a2ae87e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box read-commune</value>
      <webElementGuid>2d798e96-6570-4cc6-806b-1c5484a3a0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d7483e77-ef20-4024-aa91-806442363f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>928fcdd0-3f77-4c8d-9802-dc239542c1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existInfo&quot;)/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-sm-6&quot;]/label[@class=&quot;label-check-box&quot;]/input[@class=&quot;check-box read-commune&quot;]</value>
      <webElementGuid>3a1b40ec-d28a-40d9-986c-ee76315d163f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='checkbox'])[2]</value>
      <webElementGuid>efad3cd9-d06c-4d4c-be93-35175f89fe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existInfo']/div[2]/div/label/input</value>
      <webElementGuid>2dbeac06-4701-4693-8d47-be753a57ecbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>c21ef571-fd55-4a84-a010-6e9cb41ce2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkbox']</value>
      <webElementGuid>cede5d9a-cdc2-4527-ad61-f20ed6463f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
