<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date dchance_GarantieVehicule.DateEcheance</name>
   <tag></tag>
   <elementGuidId>619136c3-a1bf-40c2-b628-ecc1c1a4dc41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formSinistre']/div/div/table/tbody/tr[6]/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GarantieVehicule_DateEcheance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6d97bd7-5d87-4f75-bf7c-a42ffc003c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>ddfe706b-67a6-4c62-94d8-a8015caa7d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>3b6675ec-bd59-4ce2-8b62-ef1b57fb6f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e4101e8-f171-429f-b42b-29bfef8c73d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>La date d'échéance doit être supérieur ou égale à la date d'effet</value>
      <webElementGuid>8b734d13-a6e0-4be2-8791-5c7e05b5b7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.DateEcheance,*.DateEffet,*.DateSinistre</value>
      <webElementGuid>457e942c-ad23-4d5b-a840-e8b6e55b431c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>cbbb9f36-008b-4232-89fd-544fefd94361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/Date-compare/compare-dates-effet-echeance</value>
      <webElementGuid>7ea40cf6-16a6-47a9-a533-9bc4736fce4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Date d'échéance est obligatoire</value>
      <webElementGuid>dc294971-985e-4bd9-b0e8-27502c9f3fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieVehicule_DateEcheance</value>
      <webElementGuid>35747dd2-9246-4ffe-ab9d-c90337134d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieVehicule.DateEcheance</value>
      <webElementGuid>c7c4ba5b-38ba-46d1-aae6-3219616bbf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieVehicule_DateEcheance&quot;)</value>
      <webElementGuid>82161033-bfd7-4ebd-a61b-62793019c634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieVehicule_DateEcheance']</value>
      <webElementGuid>e04a5d09-4709-4911-9bf8-abb2f16bc497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>878ae50a-3399-42bd-bad8-b2c0f064de8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>9ff06670-8338-4dc4-9513-6fdca96174bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'GarantieVehicule_DateEcheance' and @name = 'GarantieVehicule.DateEcheance']</value>
      <webElementGuid>7bd24dc3-e970-4ce0-bf69-a47a8a6594ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
