<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upload_file__Attachement.FichierDeclaration</name>
   <tag></tag>
   <elementGuidId>e4a89d3b-c237-4189-abfe-4fe27305a5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierDeclaration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Attachement_FichierDeclaration'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db446362-3a7f-47d3-989f-bf6a80066acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4a6eb0e-029e-442f-8a5e-b07bc27aa520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>602c0261-554f-4687-a896-525f9f1617b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>dfa9a3e4-4ee6-444d-8942-aa72c8eb1d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierDeclaration</value>
      <webElementGuid>3cba3a4b-8c7c-48d4-9641-d17b53b2f285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierDeclaration</value>
      <webElementGuid>860d2e11-8d92-46cd-9aa7-c0e3144df56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierDeclaration&quot;]</value>
      <webElementGuid>dd808f22-d8d6-4129-b473-742c5b3a9e6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierDeclaration'])[2]</value>
      <webElementGuid>937f35d7-5de0-42d7-ab9a-239f2597786e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div/div/div/input</value>
      <webElementGuid>6a6a1cbe-2d58-415e-8171-bb6b536e72c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>9a3fef99-64c6-41ca-94a2-486f539246ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierDeclaration' and @name = 'Attachement.FichierDeclaration']</value>
      <webElementGuid>9a014d75-13de-4393-a555-473f4cf2674d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
