<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Identification de la dclaration</name>
   <tag></tag>
   <elementGuidId>071e7991-a19d-4652-9152-3735ba489c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableDeclarationForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tableDeclarationForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab391357-f04e-4500-bce2-83623da15253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>beab25ca-06c3-4974-bcc5-29f94667274a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>b19fa3d1-9d78-4c4d-9347-0899f9f2fa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/get-table-demande</value>
      <webElementGuid>72154548-7437-4b00-9639-50ca89f7afd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>921b6a9e-da99-419a-8109-694d77b31334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-begin</name>
      <type>Main</type>
      <value>ajaxBeforeSubmit</value>
      <webElementGuid>a415e460-6303-4687-928f-9ef56cefe7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsSinistre</value>
      <webElementGuid>8352dbdc-8cef-4c5a-bccf-6e3d1fbc839e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>setValidationSinistre</value>
      <webElementGuid>c9a41792-db00-4296-8d29-4ed2e6354dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#declartionIdentity</value>
      <webElementGuid>8bed14ab-5bfa-4e18-8b61-d331d731b78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>2fadafe3-cc75-4912-9a6c-2ae00cf16a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn link out</value>
      <webElementGuid>4d846974-9e38-43c5-9ba1-76c27abac0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identification de la déclaration
                                                </value>
      <webElementGuid>b75137e7-ac3a-4339-9141-985473348496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableDeclarationForm&quot;)</value>
      <webElementGuid>b07349b4-d66c-40e9-a2e0-378004514cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tableDeclarationForm']</value>
      <webElementGuid>28f1ae87-e964-45a4-8dcf-40d60553a62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dommageInfos']/div[6]/div/div/a</value>
      <webElementGuid>34029d0b-f535-4559-80e9-da9f32994210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Identification de la déclaration')]</value>
      <webElementGuid>69b0239e-3e26-4a36-a1cd-f83844968f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::a[1]</value>
      <webElementGuid>62ccdd8c-cf26-415e-a60c-c64a17d9f809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuer'])[1]/preceding::a[1]</value>
      <webElementGuid>aadd2913-51c6-4c6d-bf5d-908f7af1bb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.cat.co.ma'])[1]/preceding::a[1]</value>
      <webElementGuid>26ddb87e-4d09-4c4b-b2cf-8c0fe3cef4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Identification de la déclaration']/parent::*</value>
      <webElementGuid>9ee58dbb-d9bd-4c55-9263-e86662567df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a</value>
      <webElementGuid>b69cafbb-6080-4251-bfbd-3c6466dbfaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tableDeclarationForm' and (text() = 'Identification de la déclaration
                                                ' or . = 'Identification de la déclaration
                                                ')]</value>
      <webElementGuid>9eb443a8-725d-4c45-a868-b893f433fd9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
