<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Declarant.N_Type_Doc</name>
   <tag></tag>
   <elementGuidId>e3b418e6-695a-420f-8b62-47d8877e1e27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Declarant_N_Type_Doc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_N_Type_Doc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca52f92d-1921-4bcd-b1d1-cdbb66a2775e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b46bd318-3e68-45b0-bf1f-619da0b05f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e2c6f43-18e7-461a-b753-c305e08df9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N_Type_Doc' is invalid.</value>
      <webElementGuid>ebaf642b-0e66-4314-ad2a-f79bbe95c8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Type_Doc,*.Type_Doc_Id,*.Ref_Event_Id,*.Type_DocSinistre_Id,*.CompanyId,*.NatureDommageId,*.Type_Dommage_Id</value>
      <webElementGuid>9e258fd5-d956-4610-9655-cb5528090d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>d9fe154e-67b5-4620-b7c3-0b876479ce23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/exist-dossier/get-exist-dossier</value>
      <webElementGuid>1dfdd707-013b-4eba-959b-1415aae74075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'identifiant du document</value>
      <webElementGuid>6a79b2ed-0663-472d-8a82-5c0aceea7ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_N_Type_Doc</value>
      <webElementGuid>54f1b70f-0be7-4a09-a533-c19ae2314f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.N_Type_Doc</value>
      <webElementGuid>d55225c8-0fcd-4430-8e48-ae0318abacd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_N_Type_Doc&quot;)</value>
      <webElementGuid>f1653421-c27c-4f50-ae2e-630db1b8a779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_N_Type_Doc']</value>
      <webElementGuid>a1d167a6-9475-4c3a-ab5d-d1d483080a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>9d7366c5-e7ab-4276-83fc-082eed11c16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>954ed375-c83b-4bed-b176-51c0847e8053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_N_Type_Doc' and @name = 'Declarant.N_Type_Doc']</value>
      <webElementGuid>6132d944-308c-43ae-bf9b-8b336aed883a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
