<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Declarant.Prenom</name>
   <tag></tag>
   <elementGuidId>af34b948-4e53-4a79-948d-c0a61550d692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Declarant_Prenom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_Prenom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34b45596-c210-47d6-9a25-9db284c9eca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ad78770-5bff-47fc-be4d-5538d3e65e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47c1b335-fe10-434f-a4cc-e67e96a299cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le prénom</value>
      <webElementGuid>684a31d8-5cb4-47b1-b41a-598aaf726a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_Prenom</value>
      <webElementGuid>299e5e07-ee66-4b56-9f26-75169a76118e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.Prenom</value>
      <webElementGuid>c840394f-4f9a-4035-8c86-66ee457675f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_Prenom&quot;)</value>
      <webElementGuid>04fa9d9b-b3ca-4e29-97f7-018e288073ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_Prenom']</value>
      <webElementGuid>fe2f90db-62ee-4be3-b1b8-f1aa80fa85c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div/div[2]/input</value>
      <webElementGuid>06d22606-6511-4e99-a457-3b7029bb2cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>21f7ae62-0b7c-4d01-9dbc-bab18986fc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_Prenom' and @name = 'Declarant.Prenom']</value>
      <webElementGuid>bae47fee-e26d-44a7-9c05-3fe8f41d7e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
