<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__N_Police</name>
   <tag></tag>
   <elementGuidId>d49f9b6a-b49c-4baf-82f1-83f7e9e509f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#N_Police</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='N_Police']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6245591c-ac90-4de5-a8eb-696124168f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59fa22c5-60f1-40bd-8a17-287800d27e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue</value>
      <webElementGuid>6e387729-95f9-4f11-b649-de9ea1947314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>1d3a1aa2-35f1-4334-b237-e7b8bcf4bdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8704b699-5d37-455e-a951-e693157b7bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro de police</value>
      <webElementGuid>c4c06c9d-e258-4d24-917f-e1865b6c45e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N_Police</value>
      <webElementGuid>37c6cfbf-05ce-43ed-9646-74d1903b78d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>N_Police</value>
      <webElementGuid>91942d1f-55f8-451a-b3b4-a32371393fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;N_Police&quot;)</value>
      <webElementGuid>eb23f020-06a2-4fa0-a37f-6b3d04bc676d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='N_Police']</value>
      <webElementGuid>4bb7785f-8c89-4745-bcca-0cea70dd43b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NumPolice']/input</value>
      <webElementGuid>c23004d1-7db4-42e2-83ce-dea5083a95ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>13cf459b-b009-405e-b98e-232137f6adc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'N_Police' and @name = 'N_Police']</value>
      <webElementGuid>d5f75afd-f718-4f16-bb3e-517fd4eb8fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
