<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__N_Immatriculation</name>
   <tag></tag>
   <elementGuidId>04035b96-43f2-4f57-8b85-bea4a8a6ddc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#N_Immatriculation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='N_Immatriculation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eccb5e73-dfc0-4d55-aa4b-995a79035800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91b96d89-5150-4989-a21c-7e889ba0fb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue masked </value>
      <webElementGuid>367e52a5-a5ae-4426-83c8-40b7f4038f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>99bf3064-e9cf-43b1-8cda-6d6aae93c6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^([0-9]{1,5}-[A-Za-z]-[0-9]{1,2})$</value>
      <webElementGuid>03e47629-0512-4343-b228-06b57be2a279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-charset</name>
      <type>Main</type>
      <value>XXXXX-_-XX</value>
      <webElementGuid>8b37ee12-737f-4bfa-a859-dd68faea51e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75f2d710-5056-4d28-888f-de33e68d9083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N° Immatriculation' is invalid.</value>
      <webElementGuid>6dc7bdfa-77e6-48fb-ad8d-1e85ac1d0b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Immatriculation,*.ImmatriculationFormatId,*.Ref_Event_Id,*.Type_DocSinistre_Id,*.Type_Dommage_Id,*.NatureDommageId,*.Type_Garantie_Id</value>
      <webElementGuid>d24909b4-8454-4718-ac2f-91e32e9d8f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>6e2617fd-bde6-426f-9bd0-cca2178a26bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/FieldVerification/RegexImmat_Verify_GA</value>
      <webElementGuid>ac4be8c9-6dfb-48a1-a4c3-a950fca2e74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro d'immatriculation</value>
      <webElementGuid>7192c71c-736a-47d3-94ed-2069a2639d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N_Immatriculation</value>
      <webElementGuid>93a92bcb-5c38-4338-b0c0-66e86ffa7cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>N_Immatriculation</value>
      <webElementGuid>2cb362d0-81df-467e-ad9b-34b611da3852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>24b6a011-a79f-4280-a3a8-6c28c758b094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>XXXXX-X-XX</value>
      <webElementGuid>a4e7ffba-bcd3-4550-aa6c-18593b65ef6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;N_Immatriculation&quot;)</value>
      <webElementGuid>8acf525e-2309-48c6-b9e5-1431660f5680</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='N_Immatriculation']</value>
      <webElementGuid>963b98c8-77e3-4571-b683-db174ce69f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imma']/span/input</value>
      <webElementGuid>60d5e163-c24d-4cf8-b141-2beda3fd76f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>8d29a0e4-888c-4a44-b25f-4683d2ce8bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'N_Immatriculation' and @name = 'N_Immatriculation']</value>
      <webElementGuid>339d851f-d56b-4d7e-8e51-2d7edaba89bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
