<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N CNIERC_GarantieVehicule.NCNIRC</name>
   <tag></tag>
   <elementGuidId>9f166714-b08c-493d-a698-fc6b37d93e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formSinistre']/div/div/table/tbody/tr[7]/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GarantieVehicule_NCNIRC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbee16c5-7c5b-4fad-aa6d-cd76083425f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>50d583cf-a737-4e77-b2c0-8e1be4a16460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9929e97c-e96c-4e8f-8e7d-c9a95a75a5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1883fd11-08a5-4f8d-b4c9-6d9bbdc0bbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>N° CNIE/RC est obligatoire</value>
      <webElementGuid>36c29326-77b9-45d4-b881-d3085ee13840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieVehicule_NCNIRC</value>
      <webElementGuid>2f71c036-a720-432d-9940-deb2fc9e6931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieVehicule.NCNIRC</value>
      <webElementGuid>cdd95d35-874b-4395-a0e1-b7217b28e191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieVehicule_NCNIRC&quot;)</value>
      <webElementGuid>1466511c-834e-4630-8361-d808072efc28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieVehicule_NCNIRC']</value>
      <webElementGuid>e0f89911-e544-497d-b05b-354532ada6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>1342ab00-fb9c-4598-95a1-70bd75e5380c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>c63f04b9-a355-41e5-95b7-83e3a722dde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GarantieVehicule_NCNIRC' and @name = 'GarantieVehicule.NCNIRC']</value>
      <webElementGuid>0823651e-7d09-47c3-8c66-ccc18c17d040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
