<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Declarant.Nom</name>
   <tag></tag>
   <elementGuidId>f55eecae-263e-445c-9488-1994ed2237e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Declarant_Nom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_Nom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f340a16-9c07-4483-834d-dbe4c2c1f345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b401c72-96ed-4936-841b-aff8e9cf25e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c77286e-fe4c-47e2-b65e-2ac7b9b4b28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le nom</value>
      <webElementGuid>f58c5de5-1a3d-4566-b73a-12b94bdc2ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_Nom</value>
      <webElementGuid>78e86315-1f99-465a-98e2-1f57da25e861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.Nom</value>
      <webElementGuid>bc9aea1f-7f29-43fb-8d00-af0f78935851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_Nom&quot;)</value>
      <webElementGuid>2aee106d-421d-40bb-9d4f-c89d40cbd6b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_Nom']</value>
      <webElementGuid>fb673e33-355f-4f79-8ab9-b645acd2d67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div/div/input</value>
      <webElementGuid>c5db06c9-ec1f-411e-9a1a-e3785a680950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/input</value>
      <webElementGuid>ffd3f428-8219-4f06-bba0-9266efc6b8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_Nom' and @name = 'Declarant.Nom']</value>
      <webElementGuid>9ddf7332-9049-421d-8de2-fcddb980bfcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
