<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N de lattestation_GarantieVehicule.NA_f65e9c</name>
   <tag></tag>
   <elementGuidId>fc174c7c-de8f-4a44-a4b3-377fadb5be0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GarantieVehicule_NAttestation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieVehicule_NAttestation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8f56b88-e72e-4f71-ad97-6c46735d1a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AD321</value>
      <webElementGuid>9b56a93f-e8ca-4488-bd9f-a25e426e6c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>2c494506-e322-4c8a-85bd-4fedd8da16d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>702dfde9-98ea-4d35-b03d-6dba5ebae97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieVehicule_NAttestation</value>
      <webElementGuid>8a3eb46a-6348-4d52-a2fd-64f3c42edd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieVehicule.NAttestation</value>
      <webElementGuid>4e8d7f88-99e6-446e-8800-ebf50680aa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieVehicule_NAttestation&quot;)</value>
      <webElementGuid>a8a24760-3bc9-4b51-a701-9d64df97a09a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieVehicule_NAttestation']</value>
      <webElementGuid>bae56153-3426-45dd-bece-721e9d474316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>a99b3d8c-0cc6-4ba1-96e5-6558e3f14fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>6333d0a9-0c13-4079-86a3-8296271eec07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GarantieVehicule_NAttestation' and @name = 'GarantieVehicule.NAttestation']</value>
      <webElementGuid>9c3ffd09-ec13-44bf-8061-b394ede66d2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
