<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Adresse</name>
   <tag></tag>
   <elementGuidId>5760bdb8-8b2f-4d69-98e8-336fcd0ca4c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Adresse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Adresse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>846d4005-cec1-4ad5-9aab-96df03c22ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>caacdef9-74e2-4cd1-a48d-c415e422168e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>794524c6-7930-4b0b-9576-58adf49f0349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>64c42b2d-de80-40e8-81bb-6d6e49080098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11931c99-c5d3-400e-89db-14d7018afb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'adresse du lieu de sinistre</value>
      <webElementGuid>7723f3fe-02fd-4f45-b016-b7bfce33d430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Adresse</value>
      <webElementGuid>67fec0aa-49cc-4358-9d08-f8ba5099e579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Adresse</value>
      <webElementGuid>a7079392-efe5-4f35-842d-fa9e46ccade4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>6df7b475-317f-442f-9b53-b445a9d4cf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Adresse-error</value>
      <webElementGuid>f26b08e1-388c-4cfc-a59b-a377d21bd3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Adresse&quot;)</value>
      <webElementGuid>df14bfe3-7c27-4fe7-b19f-6329c69313c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Adresse']</value>
      <webElementGuid>c8c02c81-78c5-4ea0-a3c2-a466862e18c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existInfo']/div[3]/div/textarea</value>
      <webElementGuid>38e14ffe-11ef-42cd-aa4c-73be39753e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c1a46780-0bab-4ebd-a511-6305a4ddc8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Adresse' and @name = 'Adresse']</value>
      <webElementGuid>fe74564d-dadc-46b8-9e41-114160a3977c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
