<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date deffet_GarantieResidentiel.DateEffet</name>
   <tag></tag>
   <elementGuidId>5885ad63-70da-4003-b842-6d635fd71907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieResidentiel_DateEffet']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GarantieResidentiel_DateEffet</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76c7afb7-1beb-49af-9666-620aa88f03ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput</value>
      <webElementGuid>e911e8e4-413d-43eb-84c8-ab24046652d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ae6c3c07-febb-4171-92cd-6909ff2d26ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f24d111-1656-40fb-a7b4-0ffb0cf28d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'Date d’effet' is invalid.</value>
      <webElementGuid>2aa736c0-59a4-4408-8a6c-59c5f3a2472e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.DateEffet,*.DateSinistre</value>
      <webElementGuid>203b3ce7-8101-44c9-8fb7-e517cf1654ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>89675117-0775-4cad-afac-6706c533b216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/Date-compare/compare-dates-effet-sinistre</value>
      <webElementGuid>ea405097-e2c1-4165-9608-1aacc50a2db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Date d'effet est obligatoire</value>
      <webElementGuid>3199d74e-0916-4a34-b38a-85716290fa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieResidentiel_DateEffet</value>
      <webElementGuid>0e308bb7-4ced-42d6-bb92-de9408600842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieResidentiel.DateEffet</value>
      <webElementGuid>6296aa9e-cf07-42cd-9e14-13952e095b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieResidentiel_DateEffet&quot;)</value>
      <webElementGuid>600e3bd0-5ae1-4b49-8324-546388a50395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieResidentiel_DateEffet']</value>
      <webElementGuid>62b144e5-4a70-4412-9dc7-54d9969ccf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>9ab12a62-c714-4bd9-b7c0-1f5a89055e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>584608b7-7be6-4358-98ce-2533f01ca986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'GarantieResidentiel_DateEffet' and @name = 'GarantieResidentiel.DateEffet']</value>
      <webElementGuid>285b1bef-f837-4f78-9486-f68893deea4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
