<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>File_element</name>
   <tag></tag>
   <elementGuidId>b52a74ed-4f6d-4037-b8f0-fffbbfcc31f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;MissionFiles&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-files-MissionFiles > li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b3235bf9-ece1-490e-b9a4-6879ac21f890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>815a9573-72ac-42c1-9bd2-7729c8c90a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test plate forme.pdf 182.76 KB</value>
      <webElementGuid>459cf1a0-a579-4652-9adf-6d26b9c1cfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-files-MissionFiles&quot;)/li[1]</value>
      <webElementGuid>df3e4d9a-8f90-47c7-9dd1-8aa9cf6e4ac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='list-files-MissionFiles']/li</value>
      <webElementGuid>48749f9e-10ba-466f-b088-777fc113837b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Les fichiers selectionnés'])[1]/following::li[1]</value>
      <webElementGuid>57e6b14e-3c54-46be-a179-7aee54067944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parcourir'])[1]/following::li[1]</value>
      <webElementGuid>dad59f2d-4d38-4704-bbe5-4158f2f5bda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Créer'])[1]/preceding::li[1]</value>
      <webElementGuid>bf0f0efd-748f-49bc-bb7c-bc7b2ac7bd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lignes par page :'])[1]/preceding::li[1]</value>
      <webElementGuid>e4a87e63-8422-46c2-b162-df7c354031c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test plate forme.pdf']/parent::*</value>
      <webElementGuid>15c6bc76-3e35-4c2c-a230-7f91d6bb8c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li</value>
      <webElementGuid>0ca89ba3-6807-4ecd-9b24-2e2f5217bbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Test plate forme.pdf 182.76 KB' or . = 'Test plate forme.pdf 182.76 KB')]</value>
      <webElementGuid>b6169c88-417c-47c4-9dea-914a3e749ed5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
