<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Connexion_Input.Login</name>
   <tag></tag>
   <elementGuidId>b495e9f9-ba67-4112-9438-a410ee0ee4a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_Login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Input_Login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73eaac5b-6970-4644-a838-13be84db8524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e8de13c8-7645-49cd-9933-570701cc6e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da6a905a-43c9-4812-a293-9d8db559de75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36a5874b-e56c-4df5-b385-7964a63a8336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Login field is required.</value>
      <webElementGuid>29838a71-4ce8-48b9-a579-9955b50878ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Login</value>
      <webElementGuid>f9b33d35-67c9-4fe2-b5d8-0a7d65d68858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Login</value>
      <webElementGuid>8f3a7700-98ed-40a2-a2a7-247d796475c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_Login&quot;)</value>
      <webElementGuid>f7e34fd0-b68c-4403-9d62-4ed477423fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_Login']</value>
      <webElementGuid>92d3416d-5120-449c-ab63-06693d76701e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>e63c5074-e3e4-4924-abf7-cc32b6baada1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1293b162-8683-4e43-8a9d-cfdb579e402c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Login' and @type = 'text' and @id = 'Input_Login' and @name = 'Input.Login']</value>
      <webElementGuid>35cf1c94-8b21-45b1-9dd0-f85cd1752057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
