<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Administration</name>
   <tag></tag>
   <elementGuidId>bbb8b927-a365-4bf4-858f-b6438f2624ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(7) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jquery-accordion-menu']/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44f263d2-fd15-40e8-98d0-e85e166ba842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3916937c-dd54-4571-b18e-2331c847ddb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Administration
                    ▾</value>
      <webElementGuid>6225c8d7-279d-414d-9c02-826e542883cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jquery-accordion-menu&quot;)/ul[1]/li[7]/a[1]</value>
      <webElementGuid>5a3dfec5-0dc4-4205-8f95-395844e8eff6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jquery-accordion-menu']/ul/li[7]/a</value>
      <webElementGuid>2c75f7e4-0aa2-41d9-8c83-c77a02efe18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des honoraires'])[1]/following::a[2]</value>
      <webElementGuid>887134dd-c085-47bd-83b1-5c0dca78c586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des évènements'])[1]/preceding::a[1]</value>
      <webElementGuid>81b0842d-eeaf-4086-b6ac-c9ab67cd0427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administration']/parent::*</value>
      <webElementGuid>f7557c7b-8e5d-4648-b546-3894939fc556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>be98e6b7-44d7-43d0-a783-ea1d8ca9e304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>e9467f0d-c0a9-4b3c-88f5-9efbe83449d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                        
                        Administration
                    ▾' or . = '
                        
                        Administration
                    ▾')]</value>
      <webElementGuid>f639d983-8b7a-4f3c-9ced-16d77e88490c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
