<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filtrer</name>
   <tag></tag>
   <elementGuidId>268517fd-d04f-4366-b3da-2425fe5b6b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnfilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnfilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e6e9881-0828-4b02-9261-aa0879796a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnfilter</value>
      <webElementGuid>8046339e-9738-4eaf-8ba8-10c071db1464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>e59daf49-fa45-4390-993e-95a112532b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filtrer 
                                        </value>
      <webElementGuid>922eeeea-e8a0-438b-a815-991add07a007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnfilter&quot;)</value>
      <webElementGuid>275dbd99-e448-454c-a215-4a8c81db4c98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnfilter']</value>
      <webElementGuid>f08ae556-452c-40fc-a894-84ef8ed0dc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dossierFilsForm']/div/div/div[2]/div/button</value>
      <webElementGuid>5535a5b0-317a-4301-a111-bcb58584d390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dar bouazza'])[2]/following::button[1]</value>
      <webElementGuid>2e14af19-87c9-41d0-99d3-8eb7398084b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bouskoura'])[2]/following::button[1]</value>
      <webElementGuid>7fc69d87-747e-4f52-a51f-1e5c0f2bcb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tableau de consultation :'])[1]/preceding::button[1]</value>
      <webElementGuid>fd9c6bbc-4fff-48bd-85a6-8a8d2bd87f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lignes par page :'])[1]/preceding::button[1]</value>
      <webElementGuid>a7b032f6-6f41-4514-8e20-69c53f56d76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filtrer']/parent::*</value>
      <webElementGuid>a1614432-5ddc-4619-a0ec-0dc04b65873e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ccbdf741-c43b-4386-ba8e-1d52d7edee61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnfilter' and (text() = 'Filtrer 
                                        ' or . = 'Filtrer 
                                        ')]</value>
      <webElementGuid>cdf0922b-100b-443f-a4d2-64ea6bbffd17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
