<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre des rsidences sinistrs_EtatByT_cd2b5f</name>
   <tag></tag>
   <elementGuidId>8214fccb-142f-4637-b5ca-9d1f238ae3b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EtatByTypeDommage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EtatByTypeDommage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cee88e97-30fa-4cd3-93f4-e1b40ad0c3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EtatByTypeDommage</value>
      <webElementGuid>b1d6cf37-ade3-46c3-b956-6790f6711225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54c76128-b63f-4560-8bf1-42402f5c4ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EtatByTypeDommage</value>
      <webElementGuid>6bdf23ce-003b-42b2-83a3-df063a282a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>c2cf49e4-0ba6-4ff5-97f3-5bd5785b1533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4cd494d4-bf1a-4136-8de1-36943e918993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a323f684-2b2a-4358-ab98-bbf6ea282203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-url</name>
      <type>Main</type>
      <value>/get-table-res</value>
      <webElementGuid>5e577cca-db71-43b8-85e5-5ccb81c13fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>030dd888-c82e-4e3a-9240-7c808cf512ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>reloadJsPJInput</value>
      <webElementGuid>0e84104c-62b4-4695-8d0e-a60abd58b1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-success</name>
      <type>Main</type>
      <value>resetTablePagination</value>
      <webElementGuid>d9623648-5c5f-4382-a571-b994c68e256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-loading</name>
      <type>Main</type>
      <value>#cover-spin</value>
      <webElementGuid>a410520a-9cc3-4bdd-b245-9b33d8a8bb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#tableData</value>
      <webElementGuid>6802c91e-a085-4105-b008-514144d77469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>1d4e5c31-b892-4212-a859-85e249f52d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nested-partial</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f819442-dc68-4254-a3a4-3a5ca9e6deec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>EtatByTypeDommage</value>
      <webElementGuid>cf63da47-345c-436e-93a2-0266594617e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f2bfb860-6319-48d8-9cd7-1b862bba25b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8fe6810-804f-4ebe-8b6e-a12291ff574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez selectionner un type de dommage</value>
      <webElementGuid>0d7c6807-f610-4fe6-9629-93c99a5bfe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error ajaxValue</value>
      <webElementGuid>8a6ab5f2-248e-487c-9d7f-055e13555ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>EtatByTypeDommage-error</value>
      <webElementGuid>adc8f078-1720-4218-877c-88c1af6446cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;etat&quot;)/div[@class=&quot;row sous-blc-rad&quot;]/div[@class=&quot;col-lg-6&quot;]/label[@class=&quot;my-radio&quot;]/input[@id=&quot;EtatByTypeDommage&quot;]</value>
      <webElementGuid>1c0edfae-a570-4b3c-aad9-65c942d6fcd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EtatByTypeDommage']</value>
      <webElementGuid>0d3902a4-d10e-426c-922f-c3e2d8d86f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='etat']/div/div/label/input</value>
      <webElementGuid>9403d0be-0715-4ad5-bffc-cab0d21b283a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/input</value>
      <webElementGuid>3a9f6173-78be-48b1-90be-83d772359231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EtatByTypeDommage' and @name = 'EtatByTypeDommage' and @type = 'radio']</value>
      <webElementGuid>8d7186b4-bf45-4dc6-8813-e7826d442c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
