<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_D.EVCAT15032022</name>
   <tag></tag>
   <elementGuidId>edf1cf8b-3cd6-4e74-a729-1400ec4a587f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_RefEVCATId']/div/div/div[2]/div[2]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown-option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2d971330-6956-41d3-8f2d-96e2a074d0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option</value>
      <webElementGuid>3a3d0a18-7c18-45b5-91ac-eca64b77da66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>1d3044a2-462d-465e-bf59-966e7d405981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>70fb7e9f-d36a-4c4b-b671-64b9b1d95751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>D.EVCAT15032022</value>
      <webElementGuid>13c010aa-65b3-4897-bab3-f8d281688a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_RefEVCATId&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;tail-select no-classes deselect active&quot;]/div[@class=&quot;select-dropdown&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;dropdown-optgroup&quot;]/li[@class=&quot;dropdown-option&quot;]</value>
      <webElementGuid>bf041057-267c-4ba9-8014-7c2e61812431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_RefEVCATId']/div/div/div[2]/div[2]/ul/li</value>
      <webElementGuid>658e5844-4f41-466e-b520-76f2379af081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choisissez une option...'])[1]/following::li[1]</value>
      <webElementGuid>080a12e6-3311-449a-9353-5918100557b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Référence de l', &quot;'&quot;, 'EVCAT')])[1]/following::li[1]</value>
      <webElementGuid>c391a21f-670c-44f3-9432-a316b0ed8bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D.CRU.EVCAT30032022'])[2]/preceding::li[1]</value>
      <webElementGuid>68eb4a45-1ac6-4d9b-a70b-6d980318ae27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D.INN.EVCAT11042022'])[2]/preceding::li[2]</value>
      <webElementGuid>1275088f-dcaa-4dac-9928-0d8ed8f2b650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/ul/li</value>
      <webElementGuid>a5e8d3de-ab85-4a70-9d44-43696e9708cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'D.EVCAT15032022' or . = 'D.EVCAT15032022')]</value>
      <webElementGuid>077ac7a5-eeb9-4c25-8136-a55fd1b09192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
