<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rsidentiel_checkmark</name>
   <tag></tag>
   <elementGuidId>502784b8-bb42-480d-95cc-49963ab41f50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagedContent']/div/div[2]/div/div/div[3]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9bcebde8-24b9-4857-8a4c-10be0fb92753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>44678720-621d-4fde-b439-749fa1e8a9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagedContent&quot;)/div[@class=&quot;work-space&quot;]/div[@class=&quot;withe-space&quot;]/div[@class=&quot;formulaire&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-3&quot;]/div[@class=&quot;blc-rad&quot;]/label[@class=&quot;my-radio&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>93edaf7b-7621-406a-b5bd-559e17080351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/div/div[3]/div/label/span</value>
      <webElementGuid>34f8d457-a9ef-4f47-9d12-16ef2c30f538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label/span</value>
      <webElementGuid>0da3963c-1d3e-4467-adef-5f0c0adcdf22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
