<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accueil</name>
   <tag></tag>
   <elementGuidId>b03b350f-951b-4461-ad45-a7bb1118ef71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.home > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Accueil')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01b51e24-4c36-483c-a967-f34c3c6095c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>1e6beaf4-3a06-4809-9a13-e597788e4830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accueil</value>
      <webElementGuid>6a5c6e04-6155-4058-9730-a3de5182038e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-content&quot;]/div[@class=&quot;sidebar&quot;]/div[@class=&quot;home&quot;]/a[1]</value>
      <webElementGuid>14949e28-7032-4710-8c7c-ad65f0d62db9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accueil')]</value>
      <webElementGuid>be94d26e-df6e-4a09-a6a1-2fe29e83250a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs (HangFire)'])[1]/following::a[2]</value>
      <webElementGuid>d36c768c-974f-4dce-878c-80ff2bb42dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::a[3]</value>
      <webElementGuid>a10a0034-d93c-4a1a-9a26-e6315627cf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▾'])[1]/preceding::a[1]</value>
      <webElementGuid>df4abb86-04c4-47df-88a9-86e205fc7228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ouverture des dossiers sinistres'])[1]/preceding::a[2]</value>
      <webElementGuid>3fb1a63d-7291-47a5-a33f-44bb4abf4fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accueil']/parent::*</value>
      <webElementGuid>d9222ece-20c8-45d8-97f6-e1d80b09e073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[5]</value>
      <webElementGuid>8e97a301-edea-4854-81f3-4b9521da7d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>7d80a687-8b9d-41d0-9b27-3fbc5c4665cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Accueil' or . = 'Accueil')]</value>
      <webElementGuid>ea0a0249-f1bf-4625-9469-08a6da5a1e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
