<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GSM</name>
   <tag></tag>
   <elementGuidId>32f9cfda-6c74-435e-9a8f-de0629703def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GSM']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GSM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94efe9c3-559a-4cfe-b433-f381f20d4d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30ceb081-5783-4db6-bff5-846ceeace98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>a37dff0e-685c-4c90-bc62-b01dc7da1f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b801326-974b-45a0-b3b3-f917ae961a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Numéro de GSM non valide</value>
      <webElementGuid>a9b7fef9-5cdd-4b21-868c-bbdd63b17d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(?:(?:\+|0)?|0)[1-9](?:(?:[\s]?\d{2}){4}|\d{2}(?:\d{3}){2})$</value>
      <webElementGuid>caf9ab3e-b7ee-4ad2-9e51-d62ab6be63f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir GSM</value>
      <webElementGuid>97e99f1d-02f6-45e7-b097-f5968b72b4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GSM</value>
      <webElementGuid>7c0eada0-418b-4cfd-9a4a-bce42efb41fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GSM</value>
      <webElementGuid>62759958-f7a5-45cf-95b7-082e1e44120e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c604d3e-9252-49ed-ab20-c35f1c90ef17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__ __ __ __ __</value>
      <webElementGuid>3be002d8-dc82-431f-8908-a29cee763f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GSM&quot;)</value>
      <webElementGuid>443cc32d-f12f-4742-9119-145cae4d1864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GSM']</value>
      <webElementGuid>f1d1049e-ff8f-4313-bd72-1bc7006da45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagedContent']/div/div[2]/div/form/div/div[8]/div/input</value>
      <webElementGuid>1eea5b9c-0a12-4d64-9118-7e364a7d17ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>c2ccf559-4fd9-4454-8d74-5d45a773da2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GSM' and @name = 'GSM' and @placeholder = '__ __ __ __ __']</value>
      <webElementGuid>7726b752-af0d-4d3b-bd9e-d8c1479e47a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
