<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lignes par page_searchString</name>
   <tag></tag>
   <elementGuidId>244ed51f-1ff4-43f7-8920-94989750f95a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchString&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c8363e2-767a-4f25-b5db-a7925a7c6eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06559c7b-2ffc-4f24-8679-fdd84c77ada7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>8b040b7a-8f49-4e94-9d71-9762c9f8b98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchString</value>
      <webElementGuid>111454c2-7009-476c-bb1a-79ce305e8853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExperCatForm&quot;)/div[@class=&quot;row ExpertTable&quot;]/div[@class=&quot;col-sm-6 6 mt-1 barre-tab&quot;]/input[1]</value>
      <webElementGuid>641b5f01-f824-41e5-bf47-73e64ffb600e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchString']</value>
      <webElementGuid>d7adfe21-ba3f-41e5-a3f1-bc392645cd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ExperCatForm']/div/div[3]/input</value>
      <webElementGuid>96ee97c6-448a-4881-ae0c-49edc1b9a635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3173f9e9-a234-419b-84b9-4c2f4182b7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Rechercher' and @name = 'searchString']</value>
      <webElementGuid>d1b9221c-08f4-4ffb-b82b-cbdca7ef551e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
