<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_La dclaration avec la rfrence suivante _c2b635</name>
   <tag></tag>
   <elementGuidId>e201b2da-a365-4175-b8a0-dd39b24da63d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.toast-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6aaac57b-ef7f-4512-9d16-fe21de8cfed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast-message</value>
      <webElementGuid>f453a903-fdc9-40ca-9489-0c185ca607fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>La déclaration avec la référence suivante : &quot;Test-1304/DC2_MAT&quot; est créée</value>
      <webElementGuid>81bebf2a-390c-4b0f-8ec9-041f8548ab2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;toast toast-success&quot;]/div[@class=&quot;toast-message&quot;]</value>
      <webElementGuid>de374e99-b601-47eb-a882-fa4f85f6c21b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div/div[2]</value>
      <webElementGuid>9804d08d-a065-4590-a926-92e732713c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::div[1]</value>
      <webElementGuid>45fd63b1-8b85-4982-8c95-376eb42d1efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[2]</value>
      <webElementGuid>0df25d89-e595-4ac1-b852-dde7ce95abeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='La déclaration avec la référence suivante : &quot;Test-1304/DC2_MAT&quot; est créée']/parent::*</value>
      <webElementGuid>760da083-b361-4b1a-91fc-a96e4a36668c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>94fb49ab-d2ad-4e30-8568-6423366c415a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'La déclaration avec la référence suivante : &quot;Test-1304/DC2_MAT&quot; est créée' or . = 'La déclaration avec la référence suivante : &quot;Test-1304/DC2_MAT&quot; est créée')]</value>
      <webElementGuid>08536f37-49c3-431f-9bfc-3679fa84442a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
