<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Attachement.FichierDeclaration</name>
   <tag></tag>
   <elementGuidId>0bb0a834-283d-4a7a-991a-d2512c296729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Attachement_FichierDeclaration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.upload-file > #Attachement_FichierDeclaration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0a494b5-0183-4f8e-9402-9186f1efc24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68ed9f0d-7d5e-4ece-80e3-759bf9d6773b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-name</value>
      <webElementGuid>321e0d59-a733-41e2-84eb-bc3c2805d454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ca9805c1-7eea-49de-884d-3c6ac2670a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachement_FichierDeclaration</value>
      <webElementGuid>c270cb92-3ed4-4e20-9836-e33d42fef1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attachement.FichierDeclaration</value>
      <webElementGuid>4541f32f-03c8-48e1-8b85-be6dc1d7c55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSinistre&quot;)/div[@class=&quot;formulaire&quot;]/div[@class=&quot;documents-form&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;upload-file&quot;]/input[@id=&quot;Attachement_FichierDeclaration&quot;]</value>
      <webElementGuid>fcbd4c49-1c15-4af6-bd21-ad18b148f807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Attachement_FichierDeclaration'])[2]</value>
      <webElementGuid>d893dac7-fa8c-45ae-8506-48a53860025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[5]/div/div/div/div/input</value>
      <webElementGuid>4a392aa2-89c3-4b59-ba2b-7695a0986658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>af64d253-5aa7-4ada-ac5f-c6f12325473b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Attachement_FichierDeclaration' and @name = 'Attachement.FichierDeclaration']</value>
      <webElementGuid>cab39b45-622f-49be-a09b-4f9956c4b08a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
