<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IF du dclarant_Declarant.IF</name>
   <tag></tag>
   <elementGuidId>8ad5255d-4ac5-477f-a896-c4488e691ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_IF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Declarant_IF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2818104-3ad4-45fa-85a0-98e33dc2d534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>caf0f837-659e-4e56-a15f-40638b0a3f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_IF</value>
      <webElementGuid>d6392139-60d5-4ade-a236-7215000f8eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.IF</value>
      <webElementGuid>7965fdea-083c-4820-a5b4-71cf4149081d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_IF&quot;)</value>
      <webElementGuid>0b5e9b08-c53e-4abb-abe7-23ea5e7986d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_IF']</value>
      <webElementGuid>7f275e80-6308-47ed-b847-a6bc571465ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>f650f61b-8e59-4e56-9e7e-e5d436017a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>74e7c013-fb1d-4052-8805-0266f15570ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_IF' and @name = 'Declarant.IF']</value>
      <webElementGuid>cb4b3b59-ad12-42d0-8ae5-2de74ebbc873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
