<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N CNIERC_GarantieVehicule.NCNIRC</name>
   <tag></tag>
   <elementGuidId>cfe21b8f-c7d7-4293-b165-af841a798e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GarantieVehicule_NCNIRC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GarantieVehicule_NCNIRC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f3e5d3c-45ba-4a88-9e92-5dbf9272872d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableInput valid</value>
      <webElementGuid>72e531b3-03a3-4ec1-930f-0b5d98fb1aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54c1ae19-4b03-4e45-82ec-3ef61cd204b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07816b6c-22b7-4429-a9b6-4cd0ba54ea53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>N° CNIE/RC est obligatoire</value>
      <webElementGuid>adf3fed6-249e-4e1c-970b-dc762beecddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GarantieVehicule_NCNIRC</value>
      <webElementGuid>2362f09e-14c1-4a78-acda-be3f8093bc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GarantieVehicule.NCNIRC</value>
      <webElementGuid>2eb5e388-9519-4e1a-9b40-740c0971b2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>GarantieVehicule_NCNIRC-error</value>
      <webElementGuid>cca6a7f9-d9cc-41e4-a849-2f3e2d864054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GarantieVehicule_NCNIRC&quot;)</value>
      <webElementGuid>09b36674-7709-4159-b924-784271f42a68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GarantieVehicule_NCNIRC']</value>
      <webElementGuid>6de7a1cd-6899-4de3-90fc-a6524df687ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div/div/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>f9b8a5c0-5130-4d4f-9d82-53bfb06dfa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>867b565d-ef90-4962-bc15-97b98395a79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GarantieVehicule_NCNIRC' and @name = 'GarantieVehicule.NCNIRC']</value>
      <webElementGuid>5eeed7b2-b464-41dd-82bc-643a1fb059a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
