<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Declarant.N_Type_Doc</name>
   <tag></tag>
   <elementGuidId>f1eee80e-2feb-47f2-86dd-77e54d8ae4e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Declarant_N_Type_Doc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Declarant_N_Type_Doc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3321af16-123e-4203-9b5a-4dcddbbf0590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2965a61-233f-4dc5-b1a6-4cd7b5821981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c323a1d-480e-4e42-92a2-fa5d39fc5466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N_Type_Doc' is invalid.</value>
      <webElementGuid>d745b1ce-12d9-43a4-89a5-b13fcf509142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Type_Doc,*.Type_Doc_Id,*.Ref_Event_Id,*.Type_DocSinistre_Id,*.CompanyId,*.NatureDommageId,*.Type_Dommage_Id</value>
      <webElementGuid>04cc8248-5aeb-4460-be9b-c9fa1b705784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>382f76ab-d7f8-4d12-b440-6da956cba439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/exist-dossier/get-exist-dossier</value>
      <webElementGuid>f559db16-ff4b-4e2c-8b1c-1aa96e187d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir l'identifiant du document</value>
      <webElementGuid>90d41771-5b08-4a15-adc9-774b1de8692f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Declarant_N_Type_Doc</value>
      <webElementGuid>b4c3dc11-9a2d-4fbc-9b8b-62d7419cd4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Declarant.N_Type_Doc</value>
      <webElementGuid>b6186593-8cda-4c5c-8cce-e56916972668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Declarant_N_Type_Doc&quot;)</value>
      <webElementGuid>743047e2-9f67-4d00-9ab0-d72f84a4b70a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Declarant_N_Type_Doc']</value>
      <webElementGuid>fcbbac03-3c7d-4aed-b9e0-f418e906a056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSinistre']/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>d0310b8b-928e-4f57-ad41-76faca5b762e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>1fed92d2-d3ba-4d2f-82e1-33dbc34b169c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Declarant_N_Type_Doc' and @name = 'Declarant.N_Type_Doc']</value>
      <webElementGuid>cbf969a3-cafc-486f-9124-151668773afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
