<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ville sinistre_checkbox</name>
   <tag></tag>
   <elementGuidId>d3e6e5d2-6d8f-4199-9910-8bdd85ff1e5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/section/div[1]/div/div/div/div/div[2]/form/div[2]/div/div[2]/div[5]/div[1]/div[2]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81ba7b46-4707-46ff-9757-67ca16e94669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ba57bce1-93a7-48ee-a5af-a592a8d8ce19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box read-ville</value>
      <webElementGuid>58b2173b-ef27-4207-ac05-42463799752c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6e221e7d-164b-4f2b-bc83-b3c0cf069027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbc5f00e-526a-4e52-88e4-384f95bec215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existInfo&quot;)/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-sm-6&quot;]/label[@class=&quot;label-check-box&quot;]/input[@class=&quot;check-box read-ville&quot;]</value>
      <webElementGuid>a8311ae2-5cd8-4d92-a8fb-2d4d114e7882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='checkbox']</value>
      <webElementGuid>3135be89-643f-439c-82bd-2ddabe4e039c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existInfo']/div/div[2]/label/input</value>
      <webElementGuid>4507595e-e46c-44c8-a693-3647a295c2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>27efb241-7f4d-41ed-b221-d72850184b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkbox']</value>
      <webElementGuid>641a7b9e-8faa-48f9-a315-fd109f17e1c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
