<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__N_Immatriculation</name>
   <tag></tag>
   <elementGuidId>77a6e2b6-c100-41c3-af59-ba84c55d76ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='N_Immatriculation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#N_Immatriculation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7985244c-e5da-4bef-9099-1d95c46682b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>405a6e85-95fd-4b08-a731-bb52d0285cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxValue masked </value>
      <webElementGuid>efa1c8ec-1f74-4796-b1c9-72cb6cee2c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form</name>
      <type>Main</type>
      <value>tableDeclarationForm</value>
      <webElementGuid>46a04fb0-9855-42a2-b75d-d0c589771b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^([0-9]{1,5}-[A-Za-z]-[0-9]{1,2})$</value>
      <webElementGuid>ada51e9b-028d-4804-a3d0-f1a9be8a363b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-charset</name>
      <type>Main</type>
      <value>XXXXX-_-XX</value>
      <webElementGuid>bd86db34-721f-4625-be3d-7c9daa3c3d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fbdbbcb1-6f02-456f-8779-e02c992f60fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote</name>
      <type>Main</type>
      <value>'N° Immatriculation' is invalid.</value>
      <webElementGuid>c6bcb28c-85bc-461e-8c88-44bd22a0fdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-additionalfields</name>
      <type>Main</type>
      <value>*.N_Immatriculation,*.ImmatriculationFormatId,*.Ref_Event_Id,*.Type_DocSinistre_Id,*.Type_Dommage_Id,*.NatureDommageId,*.Type_Garantie_Id</value>
      <webElementGuid>31ef8397-fe71-4e9b-bfd2-889897e93991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-type</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>3fc5e0b5-e11a-412c-8e17-c44c219fa303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-remote-url</name>
      <type>Main</type>
      <value>/FieldVerification/RegexImmat_Verify_GA</value>
      <webElementGuid>dc9b521d-8ebb-429f-bc2a-272776901e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Veuillez saisir le numéro d'immatriculation</value>
      <webElementGuid>c4af858c-0fc0-4330-bd07-fc1fb9fa5544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N_Immatriculation</value>
      <webElementGuid>931c4b9b-8635-47ba-a018-cd6ecb079c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>N_Immatriculation</value>
      <webElementGuid>87c3d6d7-802a-4d36-926d-ad91230e2d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f169f03c-b531-46b4-97fa-a7116dcd7316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>XXXXX-X-XX</value>
      <webElementGuid>f658e17d-6610-464d-a1d1-d832d7383e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;N_Immatriculation&quot;)</value>
      <webElementGuid>ce9a7324-7dd4-4c60-874d-920d26544577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='N_Immatriculation']</value>
      <webElementGuid>b823875a-6595-44a4-ba77-492d397f8719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imma']/span/input</value>
      <webElementGuid>302c8234-ea0c-40d2-a816-79b003858884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7092af6e-bbf1-4c50-be31-0b0be6ba04f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'N_Immatriculation' and @name = 'N_Immatriculation']</value>
      <webElementGuid>359f27c6-0503-4cf0-90a5-98cc195b5862</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
